#include "engine/gameplay/CombatSystem.h"
#include "engine/core/Paths.h"
#include "engine/ecs/Registry.h"
#include "engine/gameplay/GameplayComponents.h"
#include <algorithm>
#include <filesystem>
namespace engine {namespace{std::string Resolve(const std::string&p){const std::filesystem::path path(p);if(std::filesystem::exists(path))return path.string();const std::filesystem::path e(ExecutableDir());for(const auto&c:{e/path,e/"Content"/path,e.parent_path()/path})if(std::filesystem::exists(c))return c.string();return p;}void Push(CombatComponent&c,CombatEventType t,ecs::Entity source,ecs::Entity target,const std::string&name={},const std::string&type={},float v=0,const std::string&path={}){c.events.push_back({t,source,target,name,type,path,v,c.comboStep});}const CombatDamageType*Type(const CombatAssetData&a,const std::string&name){for(const auto&t:a.damageTypes)if(t.name==name)return&t;return nullptr;}float Resistance(const CombatAssetData&a,const std::string&name){for(const auto&r:a.resistances)if(r.damageType==name)return std::max(r.multiplier,0.f);return 1.f;}}
const char* CombatResultName(CombatResult result){switch(result){case CombatResult::Miss:return "Miss";case CombatResult::Hit:return "Hit";case CombatResult::Blocked:return "Blocked";case CombatResult::Parried:return "Parried";case CombatResult::Immune:return "Immune";case CombatResult::Friendly:return "Friendly";}return "Miss";}
bool ConfigureCombat(ecs::Registry&r,ecs::Entity o,const std::string&p,std::string*e){CombatAssetData a;if(!LoadCombatAsset(Resolve(p),&a,e))return false;return ConfigureCombat(r,o,a,p);}bool ConfigureCombat(ecs::Registry&r,ecs::Entity o,const CombatAssetData&source,const std::string&p){if(!r.Valid(o))return false;CombatAssetData a=source;NormalizeCombatAsset(a);if(!ValidateCombatAsset(a))return false;if(auto*c=r.TryGet<CombatComponent>(o))*c={p,std::move(a)};else r.Add<CombatComponent>(o,{p,std::move(a)});return true;}
void SetCombatBlocking(ecs::Registry&r,ecs::Entity o,bool blocking){if(auto*c=r.TryGet<CombatComponent>(o)){if(blocking&&!c->blocking)c->blockTime=0;c->blocking=blocking;}}
bool StartCombatCombo(ecs::Registry&r,ecs::Entity o,ecs::Entity target){auto*c=r.TryGet<CombatComponent>(o);if(!c||c->asset.combo.empty()||c->staggerRemaining>0)return false;c->comboStep=0;c->comboTime=0;c->target=target;c->hitWindowEmitted=false;const auto&s=c->asset.combo[0];Push(*c,CombatEventType::ComboStarted,o,target,s.name,s.damageType,s.damage,s.actionClipPath);return true;}
bool AdvanceCombatCombo(ecs::Registry&r,ecs::Entity o){auto*c=r.TryGet<CombatComponent>(o);if(!c||c->comboStep<0)return false;const auto&current=c->asset.combo[static_cast<std::size_t>(c->comboStep)];if(c->comboTime<current.inputWindowStart||c->comboTime>current.inputWindowEnd||c->comboStep+1>=static_cast<int>(c->asset.combo.size()))return false;++c->comboStep;c->comboTime=0;c->hitWindowEmitted=false;const auto&s=c->asset.combo[static_cast<std::size_t>(c->comboStep)];Push(*c,CombatEventType::ComboAdvanced,o,c->target,s.name,s.damageType,s.damage,s.actionClipPath);return true;}
CombatResult ApplyCombatDamage(ecs::Registry&r,ecs::Entity source,ecs::Entity target,float damage,const std::string&typeName){auto*t=r.TryGet<CombatComponent>(target);auto*s=r.TryGet<CombatComponent>(source);if(!r.Valid(target))return CombatResult::Miss;if(t&&t->immunityRemaining>0)return CombatResult::Immune;if(s&&t&&s->asset.team!=0&&s->asset.team==t->asset.team&&!s->asset.friendlyFire)return CombatResult::Friendly;float finalDamage=std::max(damage,0.f);float staggerDamage=finalDamage;const CombatDamageType*type=s?Type(s->asset,typeName):nullptr;if(type){finalDamage*=std::max(type->damageMultiplier,0.f);staggerDamage*=std::max(type->staggerMultiplier,0.f);}if(t){finalDamage*=Resistance(t->asset,typeName);if(t->blocking){if(t->blockTime<=t->asset.parryWindow){Push(*t,CombatEventType::Parried,source,target,{},typeName);if(s){s->staggerRemaining=std::max(s->staggerRemaining,s->asset.staggerRecovery);Push(*s,CombatEventType::Staggered,target,source);}return CombatResult::Parried;}finalDamage*=1.f-t->asset.blockReduction;Push(*t,CombatEventType::Blocked,source,target,{},typeName,finalDamage);}}
    auto*h=r.TryGet<Health>(target);if(!h||!h->alive)return CombatResult::Miss;h->Damage(finalDamage);if(t){t->immunityRemaining=t->asset.immunityAfterHit;t->stagger+=staggerDamage;if(t->asset.poise>0&&t->stagger>=t->asset.poise){t->stagger=0;t->staggerRemaining=t->asset.staggerRecovery;Push(*t,CombatEventType::Staggered,source,target,{},typeName,finalDamage);}Push(*t,CombatEventType::Hit,source,target,{},typeName,finalDamage);}if(s)Push(*s,CombatEventType::Hit,source,target,{},typeName,finalDamage);return t&&t->blocking?CombatResult::Blocked:CombatResult::Hit;}
CombatResult ExecuteCombatHit(ecs::Registry&r,ecs::Entity o,ecs::Entity target){auto*c=r.TryGet<CombatComponent>(o);if(!c||c->comboStep<0)return CombatResult::Miss;if(target==ecs::kNull)target=c->target;const auto&s=c->asset.combo[static_cast<std::size_t>(c->comboStep)];const auto result=ApplyCombatDamage(r,o,target,s.damage,s.damageType);if(result==CombatResult::Hit||result==CombatResult::Blocked){Push(*c,CombatEventType::Reaction,o,target,s.hitReaction,s.damageType,s.damage,s.particlePath);if(!s.audioPath.empty())Push(*c,CombatEventType::Reaction,o,target,"Audio",s.damageType,s.damage,s.audioPath);}return result;}
void UpdateCombat(ecs::Registry&r,float dt){r.view<CombatComponent>().each([&](ecs::Entity o,CombatComponent&c){const float step=std::max(dt,0.f);c.immunityRemaining=std::max(0.f,c.immunityRemaining-step);c.staggerRemaining=std::max(0.f,c.staggerRemaining-step);if(c.blocking)c.blockTime+=step;else c.blockTime=0;if(c.staggerRemaining<=0)c.stagger=std::max(0.f,c.stagger-c.asset.poise*step*.25f);if(c.comboStep<0)return;c.comboTime+=step;const auto&s=c.asset.combo[static_cast<std::size_t>(c.comboStep)];if(!c.hitWindowEmitted&&c.comboTime>=s.hitTime){c.hitWindowEmitted=true;Push(c,CombatEventType::AttackWindow,o,c.target,s.name,s.damageType,s.damage,s.actionClipPath);}if(c.comboTime>=s.duration){Push(c,CombatEventType::ComboEnded,o,c.target,s.name);c.comboStep=-1;c.comboTime=0;c.target=ecs::kNull;}});}
bool IsCombatStaggered(const ecs::Registry&r,ecs::Entity o){const auto*c=r.TryGet<CombatComponent>(o);return c&&c->staggerRemaining>0;}int CombatComboStep(const ecs::Registry&r,ecs::Entity o){const auto*c=r.TryGet<CombatComponent>(o);return c?c->comboStep:-1;}std::vector<CombatEvent>ConsumeCombatEvents(ecs::Registry&r,ecs::Entity o){auto*c=r.TryGet<CombatComponent>(o);if(!c)return{};auto e=std::move(c->events);c->events.clear();return e;}
} // namespace engine
