#include "engine/gameplay/DialogueSystem.h"
#include "engine/core/Paths.h"
#include "engine/ecs/Registry.h"

#include <algorithm>
#include <filesystem>
#include <iomanip>
#include <sstream>

namespace engine { namespace {
std::string Resolve(const std::string& path){const std::filesystem::path p(path);if(std::filesystem::exists(p))return p.string();const std::filesystem::path e(ExecutableDir());for(const auto& c:{e/p,e/"Content"/p,e.parent_path()/p})if(std::filesystem::exists(c))return c.string();return path;}
bool Conditions(const std::vector<DialogueCondition>& values,const std::unordered_map<std::string,bool>& flags){for(const auto& c:values){auto i=flags.find(c.flag);if((i!=flags.end()&&i->second)!=c.expected)return false;}return true;}
DialogueNode* Find(DialogueAssetData& asset,const std::string& id){for(auto& n:asset.nodes)if(n.id==id)return &n;return nullptr;}
const DialogueNode* Find(const DialogueAssetData& asset,const std::string& id){for(const auto& n:asset.nodes)if(n.id==id)return &n;return nullptr;}
void Push(DialogueSessionComponent& s,DialogueEventType type,const std::string& node={},const std::string& name={},int choice=-1){s.events.push_back({type,s.asset.name,node,name,choice});}
bool Enter(DialogueSessionComponent& s,const std::string& id){auto* node=Find(s.asset,id);if(!node||!Conditions(node->conditions,s.flags))return false;s.currentNode=id;s.history.push_back(id);Push(s,DialogueEventType::NodeEntered,id);if(!node->enterEvent.empty())Push(s,DialogueEventType::ScriptEvent,id,node->enterEvent);if(!node->cameraHook.empty())Push(s,DialogueEventType::CameraHook,id,node->cameraHook);return true;}
void End(DialogueSessionComponent& s){s.active=false;s.currentNode.clear();Push(s,DialogueEventType::Ended);}
}

bool ConfigureDialogueSource(ecs::Registry& r,ecs::Entity source,const std::string& path,std::string* error){if(!r.Valid(source))return false;DialogueAssetData asset;if(!LoadDialogueAsset(Resolve(path),&asset,error))return false;if(auto* c=r.TryGet<DialogueSourceComponent>(source))*c={path,std::move(asset)};else r.Add<DialogueSourceComponent>(source,{path,std::move(asset)});return true;}
bool StartDialogue(ecs::Registry& r,ecs::Entity listener,const std::string& path,ecs::Entity source,std::string* error){if(!r.Valid(listener))return false;DialogueAssetData asset;if(!LoadDialogueAsset(Resolve(path),&asset,error))return false;auto* s=r.TryGet<DialogueSessionComponent>(listener);if(!s)s=&r.Add<DialogueSessionComponent>(listener,{});const auto flags=std::move(s->flags);*s={};s->assetPath=path;s->asset=std::move(asset);s->source=source;s->flags=flags;s->active=true;Push(*s,DialogueEventType::Started);if(!Enter(*s,s->asset.entryNode)){s->active=false;if(error)*error="Dialogue entry node conditions are not met.";return false;}return true;}
bool StartDialogue(ecs::Registry& r,ecs::Entity listener,ecs::Entity source,std::string* error){const auto* c=r.TryGet<DialogueSourceComponent>(source);return c&&StartDialogue(r,listener,c->assetPath,source,error);}
std::vector<int> AvailableDialogueChoices(const ecs::Registry& r,ecs::Entity listener){std::vector<int> out;const auto* s=r.TryGet<DialogueSessionComponent>(listener);if(!s||!s->active)return out;const auto* node=Find(s->asset,s->currentNode);if(!node)return out;for(std::size_t i=0;i<node->choices.size();++i)if(Conditions(node->choices[i].conditions,s->flags))out.push_back(static_cast<int>(i));return out;}
bool ChooseDialogueOption(ecs::Registry& r,ecs::Entity listener,int index){auto* s=r.TryGet<DialogueSessionComponent>(listener);if(!s||!s->active)return false;auto* node=Find(s->asset,s->currentNode);if(!node||index<0||index>=static_cast<int>(node->choices.size())||!Conditions(node->choices[static_cast<std::size_t>(index)].conditions,s->flags))return false;const std::string old=node->id;const DialogueChoice choice=node->choices[static_cast<std::size_t>(index)];if(!node->exitEvent.empty())Push(*s,DialogueEventType::ScriptEvent,old,node->exitEvent);Push(*s,DialogueEventType::NodeExited,old);Push(*s,DialogueEventType::ChoiceSelected,old,choice.text,index);if(!choice.event.empty())Push(*s,DialogueEventType::ScriptEvent,old,choice.event,index);if(choice.nextNode.empty()){End(*s);return true;}if(!Enter(*s,choice.nextNode)){End(*s);return false;}return true;}
bool ContinueDialogue(ecs::Registry& r,ecs::Entity listener){const auto available=AvailableDialogueChoices(r,listener);if(available.size()!=1)return false;return ChooseDialogueOption(r,listener,available.front());}
bool CancelDialogue(ecs::Registry& r,ecs::Entity listener){auto* s=r.TryGet<DialogueSessionComponent>(listener);if(!s||!s->active)return false;s->active=false;s->currentNode.clear();Push(*s,DialogueEventType::Cancelled);return true;}
bool SetDialogueFlag(ecs::Registry& r,ecs::Entity listener,const std::string& flag,bool value){if(!r.Valid(listener)||flag.empty())return false;auto* s=r.TryGet<DialogueSessionComponent>(listener);if(!s)s=&r.Add<DialogueSessionComponent>(listener,{});s->flags[flag]=value;return true;}
bool IsDialogueActive(const ecs::Registry& r,ecs::Entity listener){const auto* s=r.TryGet<DialogueSessionComponent>(listener);return s&&s->active;}
const DialogueNode* CurrentDialogueNode(const ecs::Registry& r,ecs::Entity listener){const auto* s=r.TryGet<DialogueSessionComponent>(listener);return s&&s->active?Find(s->asset,s->currentNode):nullptr;}
std::vector<DialogueRuntimeEvent> ConsumeDialogueEvents(ecs::Registry& r,ecs::Entity listener){auto* s=r.TryGet<DialogueSessionComponent>(listener);if(!s)return{};auto out=std::move(s->events);s->events.clear();return out;}
std::string SerializeDialogueState(const ecs::Registry& r,ecs::Entity listener){const auto* s=r.TryGet<DialogueSessionComponent>(listener);if(!s)return{};std::ostringstream out;out<<"DIALOGUE_STATE 1 "<<std::quoted(s->assetPath)<<' '<<std::quoted(s->currentNode)<<' '<<s->active<<' '<<s->flags.size();for(const auto& f:s->flags)out<<' '<<std::quoted(f.first)<<' '<<f.second;return out.str();}
bool RestoreDialogueState(ecs::Registry& r,ecs::Entity listener,const std::string& data){std::istringstream in(data);std::string magic,path,node;int version=0;bool active=false;std::size_t count=0;if(!(in>>magic>>version>>std::quoted(path)>>std::quoted(node)>>active>>count)||magic!="DIALOGUE_STATE"||version!=1)return false;std::string error;if(!path.empty()&&!StartDialogue(r,listener,path,ecs::kNull,&error))return false;auto* s=r.TryGet<DialogueSessionComponent>(listener);if(!s)s=&r.Add<DialogueSessionComponent>(listener,{});for(std::size_t i=0;i<count;++i){std::string flag;bool value=false;in>>std::quoted(flag)>>value;s->flags[flag]=value;}s->active=active;if(active&&!node.empty()&&Find(s->asset,node))s->currentNode=node;else if(!active)s->currentNode.clear();s->events.clear();return static_cast<bool>(in);}
} // namespace engine
