#include "engine/gameplay/InventorySystem.h"
#include "engine/core/Paths.h"
#include "engine/ecs/Registry.h"

#include <algorithm>
#include <filesystem>
#include <iomanip>
#include <sstream>

namespace engine { namespace {std::string Resolve(const std::string& path){const std::filesystem::path p(path);if(std::filesystem::exists(p))return p.string();const std::filesystem::path e(ExecutableDir());for(const auto& c:{e/p,e/"Content"/p,e.parent_path()/p})if(std::filesystem::exists(c))return c.string();return path;}InventoryStack* Find(InventoryComponent& inventory,const std::string& name){for(auto& s:inventory.items)if(s.asset.name==name||s.assetPath==name)return &s;return nullptr;}const InventoryStack* Find(const InventoryComponent& inventory,const std::string& name){for(const auto& s:inventory.items)if(s.asset.name==name||s.assetPath==name)return &s;return nullptr;}void Push(InventoryComponent& i,InventoryEventType t,const ItemAssetData& a,const std::string& p,int count=0,EquipmentSlot slot=EquipmentSlot::None,const std::string& event={},float magnitude=0){i.events.push_back({t,a.name,event,p,count,magnitude,slot});}}
bool AddItem(ecs::Registry& r,ecs::Entity o,const std::string& path,int count,std::string* error){ItemAssetData a;if(!LoadItemAsset(Resolve(path),&a,error))return false;return AddItem(r,o,a,count,path);}
bool AddItem(ecs::Registry& r,ecs::Entity o,const ItemAssetData& source,int count,const std::string& path){if(!r.Valid(o)||count<=0)return false;ItemAssetData a=source;NormalizeItemAsset(a);if(!ValidateItemAsset(a))return false;auto* inventory=r.TryGet<InventoryComponent>(o);if(!inventory)inventory=&r.Add<InventoryComponent>(o,{});if(a.unique&&Find(*inventory,a.name))return false;const float available=std::max(0.0f,inventory->maximumWeight-InventoryWeight(r,o));if(a.weight>0)count=std::min(count,static_cast<int>(available/a.weight));if(count<=0){Push(*inventory,InventoryEventType::Rejected,a,path);return false;}int remaining=count;for(auto& stack:inventory->items)if(stack.asset.name==a.name&&stack.count<a.maximumStack){const int add=std::min(remaining,a.maximumStack-stack.count);stack.count+=add;remaining-=add;if(!remaining)break;}while(remaining>0&&static_cast<int>(inventory->items.size())<inventory->maximumSlots){const int add=std::min(remaining,a.maximumStack);inventory->items.push_back({path,a,add,false});remaining-=add;}const int added=count-remaining;if(added)Push(*inventory,InventoryEventType::Added,a,path,added);return remaining==0;}
int RemoveItem(ecs::Registry& r,ecs::Entity o,const std::string& name,int count){auto* i=r.TryGet<InventoryComponent>(o);if(!i||count<=0)return 0;int removed=0;for(auto it=i->items.begin();it!=i->items.end()&&removed<count;){if(it->asset.name!=name&&it->assetPath!=name){++it;continue;}const int take=std::min(count-removed,it->count);const ItemAssetData asset=it->asset;const std::string path=it->assetPath;it->count-=take;removed+=take;Push(*i,InventoryEventType::Removed,asset,path,take);if(it->count<=0)it=i->items.erase(it);else ++it;}return removed;}
bool UseItem(ecs::Registry& r,ecs::Entity o,const std::string& name){auto* i=r.TryGet<InventoryComponent>(o);if(!i)return false;auto* s=Find(*i,name);if(!s)return false;const ItemAssetData asset=s->asset;const std::string path=s->assetPath;Push(*i,InventoryEventType::Used,asset,path,1);for(const auto& effect:asset.effects)Push(*i,InventoryEventType::Used,asset,effect.assetPath,1,EquipmentSlot::None,effect.event,effect.magnitude);if(asset.consumable)RemoveItem(r,o,name,1);return true;}
bool EquipItem(ecs::Registry& r,ecs::Entity o,const std::string& name){auto* i=r.TryGet<InventoryComponent>(o);if(!i)return false;auto* s=Find(*i,name);if(!s||s->asset.equipmentSlot==EquipmentSlot::None)return false;const auto slot=s->asset.equipmentSlot;for(auto& other:i->items)if(other.equipped&&other.asset.equipmentSlot==slot){other.equipped=false;Push(*i,InventoryEventType::Unequipped,other.asset,other.assetPath,other.count,slot);}s=Find(*i,name);s->equipped=true;Push(*i,InventoryEventType::Equipped,s->asset,s->assetPath,s->count,slot);return true;}
bool UnequipSlot(ecs::Registry& r,ecs::Entity o,EquipmentSlot slot){auto* i=r.TryGet<InventoryComponent>(o);if(!i)return false;for(auto& s:i->items)if(s.equipped&&s.asset.equipmentSlot==slot){s.equipped=false;Push(*i,InventoryEventType::Unequipped,s.asset,s.assetPath,s.count,slot);return true;}return false;}
int ItemCount(const ecs::Registry& r,ecs::Entity o,const std::string& name){const auto* i=r.TryGet<InventoryComponent>(o);if(!i)return 0;int total=0;for(const auto& s:i->items)if(s.asset.name==name||s.assetPath==name)total+=s.count;return total;}
bool HasItem(const ecs::Registry& r,ecs::Entity o,const std::string& name,int count){return ItemCount(r,o,name)>=std::max(count,1);}
float InventoryWeight(const ecs::Registry& r,ecs::Entity o){const auto* i=r.TryGet<InventoryComponent>(o);if(!i)return 0;float total=0;for(const auto& s:i->items)total+=s.asset.weight*s.count;return total;}
std::vector<InventoryEvent> ConsumeInventoryEvents(ecs::Registry& r,ecs::Entity o){auto* i=r.TryGet<InventoryComponent>(o);if(!i)return{};auto e=std::move(i->events);i->events.clear();return e;}
std::string SerializeInventory(const ecs::Registry& r,ecs::Entity o){const auto* i=r.TryGet<InventoryComponent>(o);if(!i)return{};std::ostringstream out;out<<"INVENTORY_STATE 1 "<<i->maximumSlots<<' '<<i->maximumWeight<<' '<<i->items.size();for(const auto& s:i->items)out<<' '<<std::quoted(s.assetPath)<<' '<<s.count<<' '<<s.equipped;return out.str();}
bool RestoreInventory(ecs::Registry& r,ecs::Entity o,const std::string& data){std::istringstream in(data);std::string magic;int version=0,slots=0;float weight=0;std::size_t count=0;if(!(in>>magic>>version>>slots>>weight>>count)||magic!="INVENTORY_STATE"||version!=1||count>10000)return false;auto* inventory=r.TryGet<InventoryComponent>(o);if(!inventory)inventory=&r.Add<InventoryComponent>(o,{});inventory->maximumSlots=std::max(slots,1);inventory->maximumWeight=std::max(weight,0.0f);inventory->items.clear();for(std::size_t n=0;n<count;++n){std::string path;int amount=0;bool equipped=false;in>>std::quoted(path)>>amount>>equipped;std::string error;if(!AddItem(r,o,path,amount,&error))return false;auto* stack=Find(*inventory,path);if(stack)stack->equipped=equipped;}inventory->events.clear();return static_cast<bool>(in);}
} // namespace engine
