#include "engine/gameplay/QuestSystem.h"
#include "engine/core/Paths.h"
#include "engine/ecs/Registry.h"

#include <algorithm>
#include <filesystem>
#include <iomanip>
#include <sstream>

namespace engine { namespace {
std::string Resolve(const std::string& path){const std::filesystem::path p(path);if(std::filesystem::exists(p))return p.string();const std::filesystem::path e(ExecutableDir());for(const auto& c:{e/p,e/"Content"/p,e.parent_path()/p})if(std::filesystem::exists(c))return c.string();return path;}
QuestRuntimeEntry* Find(QuestLogComponent& log,const std::string& name){auto i=std::find_if(log.quests.begin(),log.quests.end(),[&](const auto& q){return q.asset.name==name;});return i==log.quests.end()?nullptr:&*i;}
const QuestRuntimeEntry* Find(const QuestLogComponent& log,const std::string& name){auto i=std::find_if(log.quests.begin(),log.quests.end(),[&](const auto& q){return q.asset.name==name;});return i==log.quests.end()?nullptr:&*i;}
bool Conditions(const QuestLogComponent& log,const QuestAssetData& asset){for(const auto& c:asset.startConditions){auto i=log.flags.find(c.flag);if((i!=log.flags.end()&&i->second)!=c.expected)return false;}return true;}
void Push(QuestLogComponent& log,QuestEventType type,const std::string& quest,const std::string& objective={},const std::string& name={},int amount=0,const std::string& path={}){log.events.push_back({type,quest,objective,name,path,amount});}
bool ObjectiveUnlocked(const QuestRuntimeEntry& q,const QuestObjective& objective,const QuestLogComponent& log){if(!objective.requiredFlag.empty()){auto i=log.flags.find(objective.requiredFlag);if(i==log.flags.end()||!i->second)return false;}if(objective.requiredObjective.empty())return true;for(std::size_t i=0;i<q.asset.objectives.size();++i)if(q.asset.objectives[i].id==objective.requiredObjective)return q.progress[i]>=q.asset.objectives[i].requiredCount;return false;}
void CheckComplete(QuestLogComponent& log,QuestRuntimeEntry& q){for(std::size_t i=0;i<q.asset.objectives.size();++i)if(!q.asset.objectives[i].optional&&q.progress[i]<q.asset.objectives[i].requiredCount)return;q.state=QuestState::Completed;Push(log,QuestEventType::Completed,q.asset.name);for(const auto& reward:q.asset.rewards)Push(log,QuestEventType::Reward,q.asset.name,{},reward.name,reward.amount,reward.assetPath);}
}
const char* QuestStateName(QuestState s){switch(s){case QuestState::Inactive:return "Inactive";case QuestState::Active:return "Active";case QuestState::Completed:return "Completed";case QuestState::Failed:return "Failed";}return "Inactive";}
bool GrantQuest(ecs::Registry& r,ecs::Entity o,const std::string& p,std::string* e){QuestAssetData a;if(!LoadQuestAsset(Resolve(p),&a,e))return false;return GrantQuest(r,o,a,p);}
bool GrantQuest(ecs::Registry& r,ecs::Entity o,const QuestAssetData& source,const std::string& p){if(!r.Valid(o))return false;QuestAssetData a=source;NormalizeQuestAsset(a);if(!ValidateQuestAsset(a))return false;auto* log=r.TryGet<QuestLogComponent>(o);if(!log)log=&r.Add<QuestLogComponent>(o,{});if(Find(*log,a.name))return false;QuestRuntimeEntry q;q.assetPath=p;q.asset=std::move(a);q.progress.assign(q.asset.objectives.size(),0);log->quests.push_back(std::move(q));if(log->quests.back().asset.autoStart)StartQuest(r,o,log->quests.back().asset.name);return true;}
bool StartQuest(ecs::Registry& r,ecs::Entity o,const std::string& n){auto* l=r.TryGet<QuestLogComponent>(o);if(!l)return false;auto* q=Find(*l,n);if(!q||!Conditions(*l,q->asset))return false;if(q->state==QuestState::Completed&&q->asset.repeatable)std::fill(q->progress.begin(),q->progress.end(),0);else if(q->state!=QuestState::Inactive)return false;q->state=QuestState::Active;Push(*l,QuestEventType::Started,n);return true;}
bool AdvanceQuest(ecs::Registry& r,ecs::Entity o,const std::string& n,const std::string& id,int amount){auto* l=r.TryGet<QuestLogComponent>(o);if(!l)return false;auto* q=Find(*l,n);if(!q||q->state!=QuestState::Active)return false;for(std::size_t i=0;i<q->asset.objectives.size();++i){auto& objective=q->asset.objectives[i];if(objective.id!=id||!ObjectiveUnlocked(*q,objective,*l))continue;const int before=q->progress[i];q->progress[i]=std::clamp(before+std::max(amount,0),0,objective.requiredCount);if(q->progress[i]==before)return false;Push(*l,QuestEventType::ObjectiveAdvanced,n,id,{},q->progress[i]);if(q->progress[i]>=objective.requiredCount&&before<objective.requiredCount){Push(*l,QuestEventType::ObjectiveCompleted,n,id);if(objective.checkpoint)Push(*l,QuestEventType::Checkpoint,n,id);if(!objective.dialogueTrigger.empty())Push(*l,QuestEventType::Dialogue,n,id,objective.dialogueTrigger);}CheckComplete(*l,*q);return true;}return false;}
bool FailQuest(ecs::Registry& r,ecs::Entity o,const std::string& n){auto* l=r.TryGet<QuestLogComponent>(o);if(!l)return false;auto* q=Find(*l,n);if(!q||q->state!=QuestState::Active)return false;q->state=QuestState::Failed;Push(*l,QuestEventType::Failed,n);return true;}
bool SetQuestFlag(ecs::Registry& r,ecs::Entity o,const std::string& f,bool v){if(!r.Valid(o)||f.empty())return false;auto* l=r.TryGet<QuestLogComponent>(o);if(!l)l=&r.Add<QuestLogComponent>(o,{});l->flags[f]=v;return true;}
QuestState GetQuestState(const ecs::Registry& r,ecs::Entity o,const std::string& n){const auto* l=r.TryGet<QuestLogComponent>(o);if(!l)return QuestState::Inactive;const auto* q=Find(*l,n);return q?q->state:QuestState::Inactive;}
int GetQuestProgress(const ecs::Registry& r,ecs::Entity o,const std::string& n,const std::string& id){const auto* l=r.TryGet<QuestLogComponent>(o);if(!l)return 0;const auto* q=Find(*l,n);if(!q)return 0;for(std::size_t i=0;i<q->asset.objectives.size();++i)if(q->asset.objectives[i].id==id)return q->progress[i];return 0;}
std::vector<QuestRuntimeEvent> ConsumeQuestEvents(ecs::Registry& r,ecs::Entity o){auto* l=r.TryGet<QuestLogComponent>(o);if(!l)return{};auto e=std::move(l->events);l->events.clear();return e;}
std::string SerializeQuestState(const ecs::Registry& r,ecs::Entity o){const auto* l=r.TryGet<QuestLogComponent>(o);if(!l)return{};std::ostringstream out;out<<"QUEST_STATE 1 "<<l->flags.size();for(const auto& f:l->flags)out<<' '<<std::quoted(f.first)<<' '<<f.second;out<<' '<<l->quests.size();for(const auto& q:l->quests){out<<' '<<std::quoted(q.asset.name)<<' '<<static_cast<int>(q.state)<<' '<<q.progress.size();for(int p:q.progress)out<<' '<<p;}return out.str();}
bool RestoreQuestState(ecs::Registry& r,ecs::Entity o,const std::string& data){auto* l=r.TryGet<QuestLogComponent>(o);if(!l)return false;std::istringstream in(data);std::string magic;int version=0;std::size_t count=0;if(!(in>>magic>>version>>count)||magic!="QUEST_STATE"||version!=1)return false;for(std::size_t i=0;i<count;++i){std::string f;bool v=false;in>>std::quoted(f)>>v;l->flags[f]=v;}in>>count;for(std::size_t i=0;i<count;++i){std::string n;int s=0;std::size_t pc=0;in>>std::quoted(n)>>s>>pc;auto* q=Find(*l,n);for(std::size_t p=0;p<pc;++p){int v=0;in>>v;if(q&&p<q->progress.size())q->progress[p]=v;}if(q)q->state=static_cast<QuestState>(std::clamp(s,0,3));}return static_cast<bool>(in);}
} // namespace engine
