#include <engine/animation/AnimatedModel.h>
#include <engine/assets/AssetRegistry.h>
#include <engine/assets/EquipmentAsset.h>
#include <engine/ecs/Registry.h>
#include <engine/gameplay/EquipmentSystem.h>
#include <filesystem>
#include <iostream>
namespace{int failures=0;void Check(bool v,const char*m){if(!v){++failures;std::cerr<<"FAIL: "<<m<<'\n';}}}
int main(){engine::EquipmentAssetData set;set.header.id=engine::AssetHandle::Generate();set.name="WizardGear";set.characterId=engine::AssetHandle::Generate();set.characterPath="GameAssets/Characters/Wizard.3dgcharacter";engine::EquipmentItem staff;staff.name="OakStaff";staff.slot="RightHand";staff.socketName="StaffTip";staff.modelPath="GameAssets/Meshes/OakStaff.3dgmesh";staff.modelId=engine::AssetHandle::Generate();staff.position={.1f,.2f,.3f};staff.tags={"weapon","magic","magic"};set.items.push_back(staff);engine::NormalizeEquipmentAsset(set);Check(set.items[0].tags.size()==2,"tags normalize");Check(set.header.dependencies.size()==2,"dependencies normalize");std::string error;Check(engine::ValidateEquipmentAsset(set,&error),"valid equipment");const auto root=std::filesystem::temp_directory_path()/"3dg_equipment_test";std::filesystem::create_directories(root);const auto path=root/"Wizard.3dgequipment";Check(engine::SaveEquipmentAsset(path.string(),set,&error),"save equipment");engine::EquipmentAssetData loaded;Check(engine::LoadEquipmentAsset(path.string(),&loaded,&error),"load equipment");Check(engine::FindEquipmentItem(loaded,"OakStaff")&&loaded.items[0].socketName=="StaffTip","item round trip");engine::AssetRegistry registry;Check(registry.RebuildFromContent(root.string(),&error),"registry scan");const auto*entry=registry.Find(set.header.id);Check(entry&&entry->type==engine::AssetType::EquipmentSet&&entry->dependencies.size()==2,"registry type and dependencies");engine::ecs::Registry ecs;const auto e=ecs.Create();engine::AnimatedModel animated;engine::ModelAttachment permanent;animated.attachments.push_back(permanent);engine::ModelAttachment equipped;equipped.equipmentSlot="RightHand";equipped.equipmentItem="OakStaff";animated.attachments.push_back(equipped);ecs.Add<engine::AnimatedModel>(e,std::move(animated));Check(engine::EquippedItem(ecs,e,"RightHand")=="OakStaff","equipped query");Check(engine::UnequipSlot(ecs,e,"RightHand"),"unequip slot");Check(ecs.Get<engine::AnimatedModel>(e).attachments.size()==1,"permanent attachment preserved");std::filesystem::remove_all(root);if(failures)return 1;std::cout<<"Equipment asset tests passed\n";return 0;}
