#include <engine/assets/AssetRegistry.h>
#include <engine/assets/ItemAsset.h>
#include <engine/ecs/Registry.h>
#include <engine/gameplay/InventorySystem.h>

#include <filesystem>
#include <iostream>

namespace {int failures=0;void Check(bool v,const char* m){if(!v){++failures;std::cerr<<"FAILED: "<<m<<'\n';}}}
int main(){const auto root=std::filesystem::temp_directory_path()/"3dg_inventory_test";std::string error;
    engine::ItemAssetData potion;potion.header.id=engine::AssetHandle::Generate();potion.name="HealthPotion";potion.displayName="Health Potion";potion.type=engine::ItemType::Consumable;potion.maximumStack=5;potion.weight=.5f;potion.value=25;potion.consumable=true;potion.iconId=engine::AssetHandle::Generate();potion.iconPath="Textures/Potion.3dgtex";potion.statistics={{"Healing",25}};potion.effects={{"Heal",25,{},{}}};potion.tags={"Potion","Healing"};const auto potionPath=root/"HealthPotion.3dgitem";Check(engine::SaveItemAsset(potionPath.string(),potion,&error),"potion saves");engine::ItemAssetData loaded;Check(engine::LoadItemAsset(potionPath.string(),&loaded,&error),"potion loads");Check(loaded.maximumStack==5&&loaded.effects.size()==1&&loaded.statistics.size()==1,"item fields round trip");
    engine::ItemAssetData sword;sword.header.id=engine::AssetHandle::Generate();sword.name="WizardSword";sword.displayName="Wizard Sword";sword.type=engine::ItemType::Weapon;sword.equipmentSlot=engine::EquipmentSlot::MainHand;sword.unique=true;sword.weight=3;sword.statistics={{"Damage",12}};const auto swordPath=root/"WizardSword.3dgitem";Check(engine::SaveItemAsset(swordPath.string(),sword,&error),"weapon saves");
    engine::AssetRegistry assets;Check(assets.RebuildFromContent(root.string(),&error),"registry scans items");const auto* entry=assets.Find(potion.header.id);Check(entry&&entry->type==engine::AssetType::Item,"registry identifies item");
    engine::ecs::Registry world;const auto owner=world.Create();auto& inventory=world.Add<engine::InventoryComponent>(owner,{});inventory.maximumSlots=8;inventory.maximumWeight=10;Check(engine::AddItem(world,owner,potionPath.string(),7,&error),"stacked consumables add");Check(inventory.items.size()==2&&engine::ItemCount(world,owner,"HealthPotion")==7,"items split across stacks");Check(engine::AddItem(world,owner,swordPath.string(),1,&error),"weapon adds");Check(!engine::AddItem(world,owner,swordPath.string(),1,&error),"unique duplicate rejected");Check(engine::EquipItem(world,owner,"WizardSword"),"weapon equips");Check(inventory.items.back().equipped,"equipment state stored");Check(engine::InventoryWeight(world,owner)==6.5f,"inventory weight calculated");Check(engine::UseItem(world,owner,"HealthPotion"),"consumable used");Check(engine::ItemCount(world,owner,"HealthPotion")==6,"consumable decremented");auto events=engine::ConsumeInventoryEvents(world,owner);bool used=false,healed=false,equipped=false;for(const auto& e:events){used|=e.type==engine::InventoryEventType::Used&&e.item=="HealthPotion";healed|=e.event=="Heal"&&e.magnitude==25;equipped|=e.type==engine::InventoryEventType::Equipped;}Check(used&&healed&&equipped,"use and equipment events emitted");
    const std::string state=engine::SerializeInventory(world,owner);engine::ecs::Registry restored;const auto restoredOwner=restored.Create();Check(engine::RestoreInventory(restored,restoredOwner,state),"inventory restores");Check(engine::ItemCount(restored,restoredOwner,"HealthPotion")==6&&engine::HasItem(restored,restoredOwner,"WizardSword"),"restored contents match");auto* restoredInventory=restored.TryGet<engine::InventoryComponent>(restoredOwner);bool restoredEquipped=false;for(const auto& stack:restoredInventory->items)if(stack.asset.name=="WizardSword")restoredEquipped=stack.equipped;Check(restoredEquipped,"equipped state restores");
    std::error_code ec;std::filesystem::remove_all(root,ec);if(failures)return 1;std::cout<<"Inventory system regression tests passed\n";return 0;}
