#include <engine/assets/AssetRegistry.h>
#include <engine/assets/SpawnAsset.h>
#include <engine/ecs/Components.h>
#include <engine/ecs/Registry.h>
#include <engine/gameplay/GameplayComponents.h>
#include <engine/gameplay/SpawnSystem.h>
#include <filesystem>
#include <iostream>
namespace{int failures=0;void Check(bool v,const char*m){if(!v){++failures;std::cerr<<"FAILED: "<<m<<'\n';}}}
int main(){const auto root=std::filesystem::temp_directory_path()/"3dg_spawn_test";std::error_code ec;std::filesystem::remove_all(root,ec);std::string error;
 engine::SpawnAssetData asset;asset.header.id=engine::AssetHandle::Generate();asset.name="WizardAmbush";asset.autoStart=false;asset.maximumConcurrent=4;asset.maximumTotal=8;asset.recycleDead=true;asset.entries={{"Apprentice","Enemies","EasyPrototype",{},engine::AssetHandle::Generate(),1,0,2,4,4},{"Archmage","Enemies","HardPrototype",{},engine::AssetHandle{},1,3,10,4,4}};asset.waves={{"Opening","Enemies",2,0,0,0,false}};const auto path=root/"WizardAmbush.3dgspawn";
 Check(engine::SaveSpawnAsset(path.string(),asset,&error),"spawn asset saves");engine::SpawnAssetData loaded;Check(engine::LoadSpawnAsset(path.string(),&loaded,&error),"spawn asset loads");Check(loaded.entries.size()==2&&loaded.waves.size()==1&&loaded.maximumConcurrent==4,"spawn fields round trip");Check(loaded.header.dependencies.size()==1,"prefab dependency is stored");engine::AssetRegistry assets;Check(assets.RebuildFromContent(root.string(),&error),"registry scans spawn assets");const auto*entry=assets.Find(asset.header.id);Check(entry&&entry->type==engine::AssetType::Spawn,"registry identifies spawn asset");
 engine::ecs::Registry world;const auto easy=world.Create();world.Add<engine::ecs::RuntimeName>(easy,{"EasyPrototype"});world.Add<engine::ecs::Transform>(easy,{});world.Add<engine::Health>(easy,{50,50,true,false});const auto hard=world.Create();world.Add<engine::ecs::RuntimeName>(hard,{"HardPrototype"});world.Add<engine::ecs::Transform>(hard,{});world.Add<engine::Health>(hard,{100,100,true,false});const auto manager=world.Create();world.Add<engine::ecs::RuntimeName>(manager,{"AmbushManager"});world.Add<engine::ecs::Transform>(manager,{{4,0,2}});
 Check(engine::ConfigureSpawnManager(world,manager,loaded),"spawn manager configures");Check(engine::StartSpawnEncounter(world,manager,5),"encounter starts");engine::UpdateSpawnManagers(world,0);engine::UpdateSpawnManagers(world,0);Check(engine::SpawnAliveCount(world,manager)==2,"wave spawns requested count");auto*component=world.TryGet<engine::SpawnManagerComponent>(manager);Check(component&&component->managed.size()==2,"manager tracks spawned entities");for(auto e:component->managed){const auto*n=world.TryGet<engine::ecs::RuntimeName>(e);Check(n&&n->value.rfind("Archmage_",0)==0,"difficulty selects eligible weighted group entry");const auto*t=world.TryGet<engine::ecs::Transform>(e);Check(t&&t->position.x>=-4&&t->position.x<=12,"spawn lies inside authored volume");}
 engine::UpdateSpawnManagers(world,.01f);Check(!engine::SpawnEncounterRunning(world,manager),"encounter completes after final wave");auto events=engine::ConsumeSpawnEvents(world,manager);bool started=false,wave=false,spawned=false,completed=false;for(const auto&e:events){started|=e.type==engine::SpawnEventType::EncounterStarted;wave|=e.type==engine::SpawnEventType::WaveStarted;spawned|=e.type==engine::SpawnEventType::EntitySpawned;completed|=e.type==engine::SpawnEventType::EncounterCompleted;}Check(started&&wave&&spawned&&completed,"encounter lifecycle events emit");
 const auto recycled=component->managed.front();world.Get<engine::Health>(recycled).alive=false;engine::ResetSpawnEncounter(world,manager);Check(engine::TriggerSpawnWave(world,manager,0),"manual wave trigger works");engine::UpdateSpawnManagers(world,0);Check(world.Valid(recycled)&&world.Get<engine::Health>(recycled).alive,"dead pooled entity is recycled");
 component->asset.entries[1].poolLimit=0;world.Get<engine::Health>(recycled).alive=false;engine::UpdateSpawnManagers(world,0);Check(!world.Valid(recycled),"zero pool limit destroys dead managed entity");
 std::filesystem::remove_all(root,ec);if(failures)return 1;std::cout<<"Spawn system regression tests passed\n";return 0;}
