#include "CaveTunnelPanel.h"
#include "EditorPanels.h"
#include <engine/math/Spline.h>
#include <imgui.h>
#include <algorithm>
#include <cstdio>
#include <filesystem>

namespace { const EditorScene::Object* Spline(const EditorScene&s,const std::string&n){for(auto&o:s.Objects())if(o.isSpline&&o.name==n&&o.splinePoints.size()>1)return&o;return nullptr;} }
void CaveTunnelPanel::New(const std::string&root){m_cave={};m_cave.name="NewCave";m_cave.header.id=engine::AssetHandle::Generate();m_path=(std::filesystem::path(root)/"GameAssets"/"Caves"/"NewCave.3dgcave").string();m_dirty=true;}
bool CaveTunnelPanel::AssetCombo(const char*l,std::string&p,engine::AssetHandle&id,EditorAssets&a){bool c=false;const auto list=a.ContentAssetPaths(EditorAssets::Type::Material);const std::string preview=p.empty()?"Default":std::filesystem::path(p).filename().string();if(ImGui::BeginCombo(l,preview.c_str())){if(ImGui::Selectable("Default",p.empty())){p.clear();id={};c=true;}for(auto&x:list){const std::string n=std::filesystem::path(x).filename().string();if(ImGui::Selectable(n.c_str(),x==p)){p=x;id=a.AssetIdForPath(x);c=true;}}ImGui::EndCombo();}return c;}
void CaveTunnelPanel::Preview()const{const ImVec2 size(ImGui::GetContentRegionAvail().x,std::max(190.f,ImGui::GetContentRegionAvail().y));ImGui::InvisibleButton("##CavePreview",size);auto*d=ImGui::GetWindowDrawList();const ImVec2 p=ImGui::GetItemRectMin();d->AddRectFilled(p,{p.x+size.x,p.y+size.y},IM_COL32(18,20,24,255));if(m_cave.points.size()<2)return;glm::vec3 mn=m_cave.points[0],mx=mn;for(auto&v:m_cave.points){mn=glm::min(mn,v);mx=glm::max(mx,v);}const float sx=size.x/std::max(mx.x-mn.x,1.f),sz=size.y/std::max(mx.z-mn.z,1.f),scale=.8f*std::min(sx,sz);auto map=[&](glm::vec3 v){return ImVec2(p.x+size.x*.5f+(v.x-(mn.x+mx.x)*.5f)*scale,p.y+size.y*.5f+(v.z-(mn.z+mx.z)*.5f)*scale);};for(size_t i=1;i<m_cave.points.size();++i)d->AddLine(map(m_cave.points[i-1]),map(m_cave.points[i]),IM_COL32(190,145,92,255),std::max(3.f,m_cave.width*scale));for(auto&c:m_cave.chambers)if(c.pointIndex>=0&&c.pointIndex<(int)m_cave.points.size())d->AddCircle(map(m_cave.points[c.pointIndex]),m_cave.width*.5f*c.radiusScale*scale,IM_COL32(255,196,96,255),32,2);}
CaveTunnelPanel::Result CaveTunnelPanel::Draw(const EditorScene&scene,EditorAssets&assets,const std::string&root,bool*open){Result result;if(!m_cave.header.id.Valid())New(root);if(!m_pendingOpen.empty()){std::string e;if(engine::LoadCaveAsset(m_pendingOpen,&m_cave,&e)){m_path=m_pendingOpen;m_dirty=false;m_status="Loaded "+m_path;}else m_status=e;m_pendingOpen.clear();}if(!ImGui::Begin(EditorPanels::Name(EditorPanels::Panel::CaveTunnel),open)){ImGui::End();return result;}std::vector<const EditorScene::Object*>splines;for(auto&o:scene.Objects())if(o.isSpline&&o.splinePoints.size()>1)splines.push_back(&o);if(!Spline(scene,m_splineName)&&!splines.empty())m_splineName=splines.front()->name;
if(ImGui::Button("New"))New(root);ImGui::SameLine();if(ImGui::Button("Capture Spline")){if(auto*s=Spline(scene,m_splineName)){m_cave.points=s->splinePoints;m_cave.closed=s->splineClosed;m_dirty=true;}}ImGui::SameLine();if(ImGui::Button("Save")){std::string e;if(engine::SaveCaveAsset(m_path,m_cave,&e)){m_dirty=false;result.saved=true;result.message="Saved cave: "+m_path;}else result.message=e;}ImGui::SameLine();if(ImGui::Button("Build / Rebuild"))result.build=true;ImGui::SameLine();if(ImGui::Button("Delete Generated"))result.remove=true;
char name[128]{};std::snprintf(name,sizeof(name),"%s",m_cave.name.c_str());if(ImGui::InputText("Name",name,sizeof(name))){m_cave.name=name;m_dirty=true;}if(ImGui::BeginCombo("Source Spline",m_splineName.empty()?"No spline":m_splineName.c_str())){for(auto*s:splines)if(ImGui::Selectable(s->name.c_str(),s->name==m_splineName))m_splineName=s->name;ImGui::EndCombo();}
m_dirty|=ImGui::DragFloat("Width",&m_cave.width,.1f,.5f,100,"%.2f m");m_dirty|=ImGui::DragFloat("Height",&m_cave.height,.1f,.5f,100,"%.2f m");m_dirty|=ImGui::DragFloat("Wall Thickness",&m_cave.wallThickness,.02f,.01f,10,"%.2f m");m_dirty|=ImGui::DragFloat("Curve Resolution",&m_cave.sampleSpacing,.05f,.1f,20,"%.2f m");m_dirty|=ImGui::SliderInt("Radial Segments",&m_cave.radialSegments,6,64);m_dirty|=ImGui::Checkbox("End Caps",&m_cave.endCaps);ImGui::SameLine();m_dirty|=ImGui::Checkbox("Collision",&m_cave.createCollision);ImGui::SameLine();m_dirty|=ImGui::Checkbox("Navigation Floor",&m_cave.createNavigation);m_dirty|=ImGui::Checkbox("Terrain Entrances",&m_cave.terrainEntrances);
if(ImGui::Button("Add Chamber")&&!m_cave.points.empty()){m_cave.chambers.push_back({(int)m_cave.points.size()/2,2,1.5f});m_dirty=true;}for(int i=0;i<(int)m_cave.chambers.size();++i){ImGui::PushID(i);auto&c=m_cave.chambers[i];ImGui::SeparatorText("Chamber");m_dirty|=ImGui::SliderInt("Point",&c.pointIndex,0,std::max(0,(int)m_cave.points.size()-1));m_dirty|=ImGui::DragFloat("Radius",&c.radiusScale,.1f,1,8,"%.2fx");m_dirty|=ImGui::DragFloat("Length",&c.lengthScale,.1f,.25f,8,"%.2fx");ImGui::SameLine();if(ImGui::Button("Remove")){m_cave.chambers.erase(m_cave.chambers.begin()+i--);m_dirty=true;}ImGui::PopID();}
ImGui::SeparatorText("Materials");m_dirty|=AssetCombo("Walls",m_cave.wallMaterialPath,m_cave.wallMaterialId,assets);m_dirty|=AssetCombo("Floor",m_cave.floorMaterialPath,m_cave.floorMaterialId,assets);m_dirty|=AssetCombo("Ceiling",m_cave.ceilingMaterialPath,m_cave.ceilingMaterialId,assets);m_dirty|=AssetCombo("Trim",m_cave.trimMaterialPath,m_cave.trimMaterialId,assets);
engine::CaveGenerationStats stats;engine::StaticMeshAssetData mesh;std::string e;if(engine::BuildCaveStaticMesh(m_cave,&mesh,&stats,&e))ImGui::Text("%.1f m | %zu vertices | %zu triangles",stats.length,stats.vertices,stats.triangles);else ImGui::TextDisabled("%s",e.c_str());ImGui::Separator();Preview();if(m_dirty)ImGui::TextColored({1,.7f,.2f,1},"Unsaved changes");if(!m_status.empty())ImGui::TextWrapped("%s",m_status.c_str());ImGui::End();return result;}
