#include "CharacterEquipmentPanel.h"
#include "EditorPanels.h"
#include <imgui.h>
#include <glm/gtc/type_ptr.hpp>
#include <algorithm>
#include <cmath>
#include <cctype>
#include <cstdio>
#include <filesystem>
#include <sstream>
namespace{std::string Full(const std::string&r,const std::string&p){if(p.empty())return{};std::filesystem::path v(p);return v.is_absolute()?v.string():(std::filesystem::path(r)/v).string();}std::string Safe(std::string v){for(char&c:v)if(!std::isalnum((unsigned char)c)&&c!='_'&&c!='-')c='_';return v.empty()?"NewEquipmentSet":v;}bool Text(const char*l,std::string&v){char b[256]{};std::snprintf(b,sizeof(b),"%s",v.c_str());if(!ImGui::InputText(l,b,sizeof(b)))return false;v=b;return true;}std::string Join(const std::vector<std::string>&v){std::string o;for(const auto&s:v){if(!o.empty())o+=", ";o+=s;}return o;}std::vector<std::string>Split(const std::string&t){std::vector<std::string>o;std::stringstream s(t);std::string v;while(std::getline(s,v,',')){auto a=v.find_first_not_of(" \t"),b=v.find_last_not_of(" \t");if(a!=std::string::npos)o.push_back(v.substr(a,b-a+1));}return o;}
bool AssetCombo(const char*label,std::string&path,engine::AssetHandle&id,EditorAssets&assets,std::initializer_list<EditorAssets::Type>types){bool changed=false;const auto preview=path.empty()?"None":std::filesystem::path(path).filename().string();if(ImGui::BeginCombo(label,preview.c_str())){if(ImGui::Selectable("None",path.empty())){path.clear();id={};changed=true;}for(auto type:types)for(const auto&p:assets.ContentAssetPaths(type)){ImGui::PushID(p.c_str());if(ImGui::Selectable(std::filesystem::path(p).filename().string().c_str(),p==path)){path=p;id=assets.AssetIdForPath(p);changed=true;}ImGui::PopID();}ImGui::EndCombo();}return changed;}}
void CharacterEquipmentPanel::New(const std::string&root){m_asset={};m_asset.header.id=engine::AssetHandle::Generate();m_path=(std::filesystem::path(root)/"GameAssets"/"Equipment"/"NewEquipmentSet.3dgequipment").string();m_selected=-1;m_characterLoaded=false;m_dirty=true;m_status.clear();}
bool CharacterEquipmentPanel::LoadCharacter(const std::string&root,std::string*error){m_characterLoaded=m_character.Load(Full(root,m_asset.characterPath),error);return m_characterLoaded;}
bool CharacterEquipmentPanel::Load(const std::string&p,const std::string&root,std::string*e){if(!engine::LoadEquipmentAsset(p,&m_asset,e))return false;m_path=p;m_selected=m_asset.items.empty()?-1:0;m_dirty=false;LoadCharacter(root,e);return true;}
bool CharacterEquipmentPanel::SaveForShutdown(const std::string&root,std::string*e){if(m_path.empty())New(root);if(!engine::SaveEquipmentAsset(m_path,m_asset,e))return false;m_dirty=false;return true;}
void CharacterEquipmentPanel::DrawPreview(){const ImVec2 size(std::max(260.f,ImGui::GetContentRegionAvail().x),330.f);ImGui::InvisibleButton("##EquipmentPreview",size);auto*d=ImGui::GetWindowDrawList();const auto mn=ImGui::GetItemRectMin(),mx=ImGui::GetItemRectMax();d->AddRectFilled(mn,mx,IM_COL32(13,17,23,255));const ImVec2 c((mn.x+mx.x)*.5f,(mn.y+mx.y)*.5f);d->AddCircle(c,55,IM_COL32(80,115,145,255),32,2);d->AddLine({c.x,c.y+55},{c.x,c.y+175},IM_COL32(80,115,145,255),3);d->AddLine({c.x-70,c.y+95},{c.x+70,c.y+95},IM_COL32(80,115,145,255),3);if(!m_characterLoaded){d->AddText({mn.x+12,mn.y+12},IM_COL32(190,190,195,255),"Choose a Character asset to validate its sockets.");return;}for(std::size_t i=0;i<m_character.sockets.size();++i){const auto&s=m_character.sockets[i];const float angle=6.28318f*(float)i/std::max(1.f,(float)m_character.sockets.size());const ImVec2 p(c.x+std::cos(angle)*95,c.y+100+std::sin(angle)*75);const bool active=m_selected>=0&&m_selected<(int)m_asset.items.size()&&m_asset.items[(std::size_t)m_selected].socketName==s.name;d->AddCircleFilled(p,active?7:4,active?IM_COL32(255,180,35,255):IM_COL32(65,210,235,255));d->AddText({p.x+7,p.y-7},IM_COL32(190,205,220,255),s.name.c_str());}}
CharacterEquipmentPanel::Result CharacterEquipmentPanel::Draw(EditorAssets&assets,const std::string&root,bool*open){Result result;if(!m_asset.header.id.Valid())New(root);if(!m_pendingOpen.empty()){std::string e;if(!Load(m_pendingOpen,root,&e))m_status=e;else m_status="Loaded "+m_pendingOpen;m_pendingOpen.clear();}if(!ImGui::Begin(EditorPanels::Name(EditorPanels::Panel::CharacterEquipment),open)){ImGui::End();return result;}if(ImGui::Button("New"))New(root);ImGui::SameLine();if(ImGui::Button("Save")){if(m_path.empty())m_path=(std::filesystem::path(root)/"GameAssets"/"Equipment"/(Safe(m_asset.name)+".3dgequipment")).string();std::string e;if(engine::SaveEquipmentAsset(m_path,m_asset,&e)){m_dirty=false;result.saved=true;result.message="Saved equipment set: "+m_path;}else result.message=e;}ImGui::SameLine();ImGui::TextUnformatted(m_path.c_str());m_dirty|=Text("Set Name",m_asset.name);
 const auto charPreview=m_asset.characterPath.empty()?"Choose character...":std::filesystem::path(m_asset.characterPath).filename().string();if(ImGui::BeginCombo("Compatible Character",charPreview.c_str())){for(const auto&p:assets.ContentAssetPaths(EditorAssets::Type::Character)){ImGui::PushID(p.c_str());if(ImGui::Selectable(std::filesystem::path(p).filename().string().c_str(),p==m_asset.characterPath)){m_asset.characterPath=p;m_asset.characterId=assets.AssetIdForPath(p);std::string e;if(!LoadCharacter(root,&e))m_status=e;m_dirty=true;}ImGui::PopID();}ImGui::EndCombo();}
 ImGui::Columns(2,"##EquipmentColumns",true);ImGui::SeparatorText("Items");Text("Search",m_search);for(std::size_t i=0;i<m_asset.items.size();++i){const auto&item=m_asset.items[i];const std::string hay=item.name+" "+item.slot+" "+Join(item.tags);if(!m_search.empty()&&hay.find(m_search)==std::string::npos)continue;ImGui::PushID((int)i);if(ImGui::Selectable((item.name+" ["+item.slot+"]").c_str(),m_selected==(int)i))m_selected=(int)i;ImGui::PopID();}if(ImGui::Button("Add Item")){m_asset.items.emplace_back();m_asset.items.back().name="Item_"+std::to_string(m_asset.items.size());if(m_characterLoaded&&!m_character.sockets.empty())m_asset.items.back().socketName=m_character.sockets.front().name;m_selected=(int)m_asset.items.size()-1;m_dirty=true;}ImGui::SameLine();if(ImGui::Button("Duplicate")&&m_selected>=0){auto copy=m_asset.items[(std::size_t)m_selected];copy.name+="_Copy";m_asset.items.push_back(std::move(copy));m_selected=(int)m_asset.items.size()-1;m_dirty=true;}ImGui::SameLine();if(ImGui::Button("Delete")&&m_selected>=0){m_asset.items.erase(m_asset.items.begin()+m_selected);m_selected=std::min(m_selected,(int)m_asset.items.size()-1);m_dirty=true;}
 ImGui::NextColumn();ImGui::SeparatorText("Character Preview");DrawPreview();if(m_selected>=0&&m_selected<(int)m_asset.items.size()){ImGui::PushID(m_selected);auto&i=m_asset.items[(std::size_t)m_selected];m_dirty|=Text("Item Name",i.name);m_dirty|=Text("Equipment Slot",i.slot);const auto socket=i.socketName.empty()?"Choose socket...":i.socketName;if(ImGui::BeginCombo("Character Socket",socket.c_str())){for(const auto&s:m_character.sockets)if(ImGui::Selectable(s.name.c_str(),s.name==i.socketName)){i.socketName=s.name;m_dirty=true;}ImGui::EndCombo();}m_dirty|=AssetCombo("Mesh",i.modelPath,i.modelId,assets,{EditorAssets::Type::Model});m_dirty|=AssetCombo("Material",i.materialPath,i.materialId,assets,{EditorAssets::Type::Material});m_dirty|=AssetCombo("Equip Sound",i.equipAudioPath,i.audioId,assets,{EditorAssets::Type::Audio});m_dirty|=AssetCombo("Equip Effect",i.equipEffectPath,i.effectId,assets,{EditorAssets::Type::Particle,EditorAssets::Type::ParticleEffect});m_dirty|=ImGui::DragFloat3("Position",glm::value_ptr(i.position),.005f);m_dirty|=ImGui::DragFloat3("Rotation",glm::value_ptr(i.eulerDegrees),.25f);m_dirty|=ImGui::DragFloat3("Scale",glm::value_ptr(i.scale),.005f,.0001f,100.0f);std::string tags=Join(i.tags);if(Text("Tags",tags)){i.tags=Split(tags);m_dirty=true;}const bool socketOk=std::any_of(m_character.sockets.begin(),m_character.sockets.end(),[&](const CharacterSocket&s){return s.name==i.socketName;});if(m_characterLoaded&&!socketOk)ImGui::TextColored({1,.3f,.2f,1},"Missing socket on selected character");ImGui::PopID();}ImGui::Columns(1);engine::NormalizeEquipmentAsset(m_asset);if(m_dirty)ImGui::TextColored({1,.7f,.2f,1},"Unsaved changes");if(!m_status.empty())ImGui::TextWrapped("%s",m_status.c_str());ImGui::End();return result;}
