#include "DestructionAuthoringPanel.h"
#include "EditorPanels.h"

#include <imgui.h>

#include <algorithm>
#include <cstdio>
#include <filesystem>

void DestructionAuthoringPanel::New(const std::string& root){m_asset={};m_asset.header.id=engine::AssetHandle::Generate();m_asset.name="NewDestructible";m_path=(std::filesystem::path(root)/"GameAssets"/"Destruction"/"NewDestructible.3dgdestruction").string();m_status.clear();m_dirty=true;}
bool DestructionAuthoringPanel::SaveForShutdown(const std::string& root,std::string* error){if(m_path.empty())New(root);if(!engine::SaveDestructionAsset(m_path,m_asset,error))return false;m_dirty=false;return true;}
void DestructionAuthoringPanel::Capture(const EditorScene::Object& object,const engine::ecs::Transform& transform){m_asset.sourceMeshPath=object.modelAssetPath;m_asset.sourceMeshId=object.modelAssetId;m_asset.sourceMaterialPath=object.materialAssetPath;m_asset.sourceMaterialId=object.materialAssetId;m_asset.bounds=glm::max(glm::abs(transform.scale),glm::vec3(.02f));m_status="Captured "+object.name+". Adjust bounds if the imported mesh size differs.";m_dirty=true;}
bool DestructionAuthoringPanel::AssetCombo(const char* label,EditorAssets::Type type,std::string& path,engine::AssetHandle& id,EditorAssets& assets,const char* empty){bool changed=false;const std::string preview=path.empty()?empty:std::filesystem::path(path).filename().string();if(ImGui::BeginCombo(label,preview.c_str())){if(ImGui::Selectable(empty,path.empty())){path.clear();id={};changed=true;}for(const auto& candidate:assets.ContentAssetPaths(type)){const std::string name=std::filesystem::path(candidate).filename().string();if(ImGui::Selectable(name.c_str(),candidate==path)){path=candidate;id=assets.AssetIdForPath(candidate);changed=true;}}ImGui::EndCombo();}return changed;}
void DestructionAuthoringPanel::DrawPreview()const{const ImVec2 size(ImGui::GetContentRegionAvail().x,std::max(240.f,ImGui::GetContentRegionAvail().y));ImGui::InvisibleButton("##DestructionPreview",size);auto* draw=ImGui::GetWindowDrawList();const ImVec2 o=ImGui::GetItemRectMin();draw->AddRectFilled(o,{o.x+size.x,o.y+size.y},IM_COL32(18,20,24,255));const auto chunks=engine::GenerateDestructionChunks(m_asset);const float scale=.72f*std::min(size.x/std::max(m_asset.bounds.x,.01f),size.y/std::max(m_asset.bounds.y,.01f));for(const auto& chunk:chunks){const ImVec2 a{o.x+size.x*.5f+(chunk.localCenter.x-chunk.size.x*.5f)*scale,o.y+size.y*.5f-(chunk.localCenter.y+chunk.size.y*.5f)*scale};const ImVec2 b{o.x+size.x*.5f+(chunk.localCenter.x+chunk.size.x*.5f)*scale,o.y+size.y*.5f-(chunk.localCenter.y-chunk.size.y*.5f)*scale};const unsigned shade=static_cast<unsigned>(110+(chunk.index*37u)%90u);draw->AddRectFilled(a,b,IM_COL32(shade,125,90,230));draw->AddRect(a,b,IM_COL32(235,180,75,255));}draw->AddText({o.x+10,o.y+10},IM_COL32(210,215,225,255),(std::to_string(chunks.size())+" deterministic fracture chunks").c_str());}
DestructionAuthoringPanel::Result DestructionAuthoringPanel::Draw(const EditorScene& scene,EditorAssets& assets,const std::string& root,bool* open){Result result;if(!m_asset.header.id.Valid())New(root);if(!m_pendingOpen.empty()){std::string error;if(engine::LoadDestructionAsset(m_pendingOpen,&m_asset,&error)){m_path=m_pendingOpen;m_dirty=false;m_status="Loaded "+m_path;}else m_status=error;m_pendingOpen.clear();}if(!ImGui::Begin(EditorPanels::Name(EditorPanels::Panel::DestructionAuthoring),open)){ImGui::End();return result;}
    if(ImGui::Button("New"))New(root);ImGui::SameLine();if(ImGui::Button("Capture Selected Mesh"))result.captureSelected=true;ImGui::SameLine();if(ImGui::Button("Save")){std::string error;if(engine::SaveDestructionAsset(m_path,m_asset,&error)){m_dirty=false;result.saved=true;result.message="Saved destruction asset: "+m_path;}else result.message=error;}ImGui::SameLine();if(ImGui::Button("Preview Break in Level"))result.buildPreview=true;ImGui::SameLine();if(ImGui::Button("Clear Preview"))result.removePreview=true;
    char name[128]{};std::snprintf(name,sizeof(name),"%s",m_asset.name.c_str());if(ImGui::InputText("Name",name,sizeof(name))){m_asset.name=name;m_dirty=true;}
    ImGui::SeparatorText("Source and Damage States");m_dirty|=AssetCombo("Intact Mesh",EditorAssets::Type::Model,m_asset.sourceMeshPath,m_asset.sourceMeshId,assets,"Use selected primitive");m_dirty|=AssetCombo("Intact Material",EditorAssets::Type::Material,m_asset.sourceMaterialPath,m_asset.sourceMaterialId,assets,"Keep current");
    if(ImGui::Button("Add Damage State")){engine::DestructionDamageState state;state.name="Damaged "+std::to_string(m_asset.states.size()+1);state.healthFraction=.5f;m_asset.states.push_back(state);m_dirty=true;}
    for(int i=0;i<static_cast<int>(m_asset.states.size());++i){ImGui::PushID(i);auto&s=m_asset.states[static_cast<std::size_t>(i)];ImGui::Separator();char stateName[96]{};std::snprintf(stateName,sizeof(stateName),"%s",s.name.c_str());if(ImGui::InputText("State Name",stateName,sizeof(stateName))){s.name=stateName;m_dirty=true;}m_dirty|=ImGui::SliderFloat("Enter Below Health",&s.healthFraction,.01f,.99f,"%.0f%%",ImGuiSliderFlags_AlwaysClamp);m_dirty|=AssetCombo("Mesh",EditorAssets::Type::Model,s.meshPath,s.meshId,assets,"Keep intact mesh");m_dirty|=AssetCombo("Material",EditorAssets::Type::Material,s.materialPath,s.materialId,assets,"Keep material");m_dirty|=AssetCombo("Particles",EditorAssets::Type::Particle,s.particlePath,s.particleId,assets,"None");m_dirty|=AssetCombo("Sound",EditorAssets::Type::Audio,s.audioPath,s.audioId,assets,"None");if(ImGui::Button("Remove State")){m_asset.states.erase(m_asset.states.begin()+i--);m_dirty=true;}ImGui::PopID();}
    ImGui::SeparatorText("Fracture");m_dirty|=ImGui::DragFloat3("Object Bounds",&m_asset.bounds.x,.05f,.02f,10000,"%.2f m");m_dirty|=ImGui::SliderInt("Chunks X",&m_asset.chunksX,1,16);m_dirty|=ImGui::SliderInt("Chunks Y",&m_asset.chunksY,1,16);m_dirty|=ImGui::SliderInt("Chunks Z",&m_asset.chunksZ,1,16);int seed=static_cast<int>(m_asset.seed);if(ImGui::InputInt("Seed",&seed)){m_asset.seed=static_cast<std::uint32_t>(std::max(seed,0));m_dirty=true;}m_dirty|=ImGui::SliderFloat("Chunk Gap",&m_asset.gap,0,.25f,"%.3f");m_dirty|=AssetCombo("Debris Mesh Override",EditorAssets::Type::Model,m_asset.debrisMeshPath,m_asset.debrisMeshId,assets,"Generated chunk proxy");m_dirty|=AssetCombo("Debris Material",EditorAssets::Type::Material,m_asset.debrisMaterialPath,m_asset.debrisMaterialId,assets,"Use intact material");
    ImGui::SeparatorText("Damage and Physics");m_dirty|=ImGui::DragFloat("Maximum Health",&m_asset.maxHealth,1,.001f,1000000);m_dirty|=ImGui::DragFloat("Minimum Damage",&m_asset.minimumDamage,.1f,0,1000000);m_dirty|=ImGui::DragFloat("Impact Threshold",&m_asset.impactThreshold,.1f,0,1000000);m_dirty|=ImGui::DragFloat("Total Debris Mass",&m_asset.debrisMass,.1f,.001f,100000);m_dirty|=ImGui::DragFloat("Impact Impulse Scale",&m_asset.impulseScale,.05f,0,1000);m_dirty|=ImGui::DragFloat("Outward Scatter",&m_asset.scatterImpulse,.05f,0,1000);m_dirty|=ImGui::DragFloat("Angular Impulse",&m_asset.angularImpulse,.05f,0,1000);m_dirty|=ImGui::DragFloat("Debris Lifetime",&m_asset.debrisLifetime,.1f,0,3600,"%.1f s");m_dirty|=ImGui::Checkbox("Debris Collision",&m_asset.debrisCollision);ImGui::SameLine();m_dirty|=ImGui::Checkbox("Hide Source when Broken",&m_asset.removeSourceOnBreak);
    ImGui::SeparatorText("Break Effects");m_dirty|=AssetCombo("Break Particles",EditorAssets::Type::Particle,m_asset.breakParticlePath,m_asset.breakParticleId,assets,"None");m_dirty|=AssetCombo("Break Sound",EditorAssets::Type::Audio,m_asset.breakAudioPath,m_asset.breakAudioId,assets,"None");
    engine::NormalizeDestructionAsset(m_asset);const int count=m_asset.chunksX*m_asset.chunksY*m_asset.chunksZ;ImGui::Text("%d chunks | %.2f kg each | threshold %.1f",count,m_asset.debrisMass/std::max(count,1),m_asset.impactThreshold);ImGui::Separator();DrawPreview();if(m_dirty)ImGui::TextColored({1,.7f,.2f,1},"Unsaved changes");if(!m_status.empty())ImGui::TextWrapped("%s",m_status.c_str());ImGui::End();return result;}
