#include "DialogueEditorPanel.h"
#include "EditorPanels.h"

#include <imgui.h>

#include <algorithm>
#include <cstdio>
#include <filesystem>
#include <vector>

namespace {
bool Text(const char* label,std::string& value,std::size_t size=1024){std::vector<char> b(size);std::snprintf(b.data(),b.size(),"%s",value.c_str());if(!ImGui::InputText(label,b.data(),b.size()))return false;value=b.data();return true;}
bool Conditions(const std::vector<engine::DialogueCondition>& values,const std::unordered_map<std::string,bool>& flags){for(const auto& c:values){auto i=flags.find(c.flag);if((i!=flags.end()&&i->second)!=c.expected)return false;}return true;}
engine::DialogueNode* Node(engine::DialogueAssetData& asset,const std::string& id){for(auto& n:asset.nodes)if(n.id==id)return &n;return nullptr;}
void DrawConditions(const char* id,std::vector<engine::DialogueCondition>& values,bool& dirty){ImGui::PushID(id);for(std::size_t i=0;i<values.size();++i){ImGui::PushID(static_cast<int>(i));dirty|=Text("Flag",values[i].flag);ImGui::SameLine();dirty|=ImGui::Checkbox("Expected",&values[i].expected);ImGui::SameLine();if(ImGui::SmallButton("Remove")){values.erase(values.begin()+static_cast<std::ptrdiff_t>(i));dirty=true;ImGui::PopID();break;}ImGui::PopID();}if(ImGui::SmallButton("Add Condition")){values.push_back({});dirty=true;}ImGui::PopID();}
}

void DialogueEditorPanel::New(const std::string& root){m_asset={};m_asset.header.id=engine::AssetHandle::Generate();m_asset.name="NewDialogue";m_asset.speakers.push_back({});m_asset.nodes.push_back({});m_path=(std::filesystem::path(root)/"GameAssets"/"Dialogues"/"NewDialogue.3dgdialogue").string();m_selectedSpeaker=m_selectedNode=0;m_previewActive=false;m_previewNode.clear();m_dirty=true;m_status.clear();}
bool DialogueEditorPanel::SaveForShutdown(const std::string& root,std::string* error){if(m_path.empty())New(root);if(!engine::SaveDialogueAsset(m_path,m_asset,error))return false;m_dirty=false;return true;}
bool DialogueEditorPanel::AssetCombo(const char* label,EditorAssets::Type type,std::string& path,engine::AssetHandle& id,EditorAssets& assets){bool changed=false;const std::string preview=path.empty()?"None":std::filesystem::path(path).filename().string();if(ImGui::BeginCombo(label,preview.c_str())){if(ImGui::Selectable("None",path.empty())){path.clear();id={};changed=true;}for(const auto& candidate:assets.ContentAssetPaths(type)){ImGui::PushID(candidate.c_str());const std::string name=std::filesystem::path(candidate).filename().string();if(ImGui::Selectable(name.c_str(),candidate==path)){path=candidate;id=assets.AssetIdForPath(candidate);changed=true;}ImGui::PopID();}ImGui::EndCombo();}return changed;}

void DialogueEditorPanel::DrawFlowPreview(){ImGui::SeparatorText("Conversation Flow");const ImVec2 origin=ImGui::GetCursorScreenPos();const ImVec2 size(std::max(380.0f,ImGui::GetContentRegionAvail().x),220.0f);ImGui::InvisibleButton("DialogueFlowCanvas",size);auto* draw=ImGui::GetWindowDrawList();draw->AddRectFilled(origin,{origin.x+size.x,origin.y+size.y},IM_COL32(18,22,28,255));const float width=145,height=48,gapX=45,gapY=16;for(std::size_t i=0;i<m_asset.nodes.size();++i){const float x=origin.x+12+(i%4)*(width+gapX),y=origin.y+12+(i/4)*(height+gapY);const auto& n=m_asset.nodes[i];for(const auto& c:n.choices){auto it=std::find_if(m_asset.nodes.begin(),m_asset.nodes.end(),[&](const auto& target){return target.id==c.nextNode;});if(it==m_asset.nodes.end())continue;const std::size_t j=static_cast<std::size_t>(std::distance(m_asset.nodes.begin(),it));const ImVec2 a{x+width,y+height*.5f};const ImVec2 b{origin.x+12+(j%4)*(width+gapX),origin.y+12+(j/4)*(height+gapY)+height*.5f};draw->AddLine(a,b,IM_COL32(90,145,190,210),2);}}
    for(std::size_t i=0;i<m_asset.nodes.size();++i){const float x=origin.x+12+(i%4)*(width+gapX),y=origin.y+12+(i/4)*(height+gapY);const bool selected=static_cast<int>(i)==m_selectedNode;draw->AddRectFilled({x,y},{x+width,y+height},selected?IM_COL32(48,101,145,255):IM_COL32(37,55,72,255),5.0f);draw->AddRect({x,y},{x+width,y+height},m_asset.nodes[i].id==m_asset.entryNode?IM_COL32(90,220,130,255):IM_COL32(100,170,220,255),5.0f,ImDrawFlags_None,2.0f);draw->AddText({x+7,y+6},IM_COL32_WHITE,m_asset.nodes[i].id.c_str());draw->AddText({x+7,y+25},IM_COL32(185,205,220,255),m_asset.nodes[i].speaker.c_str());}
}

void DialogueEditorPanel::DrawDebugger(){if(ImGui::Button(m_previewActive?"Restart Conversation":"Start Conversation")){m_previewActive=true;m_previewNode=m_asset.entryNode;}ImGui::SameLine();if(ImGui::Button("Stop")){m_previewActive=false;m_previewNode.clear();}if(!m_previewActive){ImGui::TextDisabled("Conversation inactive");return;}auto* node=Node(m_asset,m_previewNode);if(!node){ImGui::TextColored({1,.3f,.3f,1},"Missing preview node");return;}ImGui::Text("%s",node->speaker.c_str());ImGui::TextWrapped("%s",node->text.c_str());if(!node->localizationKey.empty())ImGui::TextDisabled("Localization: %s",node->localizationKey.c_str());if(!node->voicePath.empty())ImGui::TextDisabled("Voice: %s",std::filesystem::path(node->voicePath).filename().string().c_str());for(std::size_t i=0;i<node->choices.size();++i){const auto choice=node->choices[i];if(!Conditions(choice.conditions,m_previewFlags))continue;ImGui::PushID(static_cast<int>(i));if(ImGui::Button(choice.text.c_str())){if(choice.nextNode.empty()){m_previewActive=false;m_previewNode.clear();}else m_previewNode=choice.nextNode;}ImGui::PopID();}}

DialogueEditorPanel::Result DialogueEditorPanel::Draw(EditorAssets& assets,const std::string& root,bool* open){Result result;if(!m_asset.header.id.Valid())New(root);if(!m_pendingOpen.empty()){std::string error;if(engine::LoadDialogueAsset(m_pendingOpen,&m_asset,&error)){m_path=m_pendingOpen;m_dirty=false;m_status="Loaded "+m_path;m_selectedNode=m_selectedSpeaker=0;}else m_status=error;m_pendingOpen.clear();}
    if(!ImGui::Begin(EditorPanels::Name(EditorPanels::Panel::DialogueEditor),open)){ImGui::End();return result;}
    if(ImGui::Button("New"))New(root);ImGui::SameLine();if(ImGui::Button("Save")){std::string error;if(engine::SaveDialogueAsset(m_path,m_asset,&error)){m_dirty=false;result.saved=true;result.message="Saved dialogue asset: "+m_path;}else result.message=error;}ImGui::SameLine();if(ImGui::Button("Assign to Selected"))result.assignSelected=true;ImGui::SameLine();ImGui::TextUnformatted(m_path.c_str());
    m_dirty|=Text("Internal Name",m_asset.name);m_dirty|=ImGui::Checkbox("Skippable",&m_asset.skippable);ImGui::SameLine();m_dirty|=ImGui::Checkbox("Pause Gameplay",&m_asset.pauseGameplay);ImGui::SameLine();m_dirty|=ImGui::Checkbox("Duck Music",&m_asset.duckMusic);
    ImGui::SeparatorText("Speakers");ImGui::BeginChild("DialogueSpeakerList",{190,145},true);for(std::size_t i=0;i<m_asset.speakers.size();++i){ImGui::PushID(static_cast<int>(i));if(ImGui::Selectable(m_asset.speakers[i].id.c_str(),m_selectedSpeaker==static_cast<int>(i)))m_selectedSpeaker=static_cast<int>(i);ImGui::PopID();}if(ImGui::Button("Add Speaker")){engine::DialogueSpeaker s;s.id="Speaker"+std::to_string(m_asset.speakers.size()+1);s.displayName=s.id;m_asset.speakers.push_back(std::move(s));m_selectedSpeaker=static_cast<int>(m_asset.speakers.size()-1);m_dirty=true;}ImGui::EndChild();ImGui::SameLine();ImGui::BeginGroup();if(!m_asset.speakers.empty()){m_selectedSpeaker=std::clamp(m_selectedSpeaker,0,static_cast<int>(m_asset.speakers.size()-1));auto& s=m_asset.speakers[static_cast<std::size_t>(m_selectedSpeaker)];ImGui::PushID("SpeakerDetails");m_dirty|=Text("Speaker ID",s.id);m_dirty|=Text("Display Name",s.displayName);m_dirty|=Text("Name Localization Key",s.localizationKey);m_dirty|=AssetCombo("Portrait",EditorAssets::Type::Texture,s.portraitPath,s.portraitId,assets);if(ImGui::Button("Delete Speaker")&&m_asset.speakers.size()>1){m_asset.speakers.erase(m_asset.speakers.begin()+m_selectedSpeaker);m_selectedSpeaker=std::max(0,m_selectedSpeaker-1);m_dirty=true;}ImGui::PopID();}ImGui::EndGroup();
    ImGui::SeparatorText("Dialogue Nodes");ImGui::BeginChild("DialogueNodeList",{220,340},true);for(std::size_t i=0;i<m_asset.nodes.size();++i){ImGui::PushID(static_cast<int>(i));std::string label=(m_asset.nodes[i].id==m_asset.entryNode?"[Entry] ":"")+m_asset.nodes[i].id;if(ImGui::Selectable(label.c_str(),m_selectedNode==static_cast<int>(i)))m_selectedNode=static_cast<int>(i);ImGui::PopID();}if(ImGui::Button("Add Node")){engine::DialogueNode n;n.id="Node"+std::to_string(m_asset.nodes.size()+1);n.speaker=m_asset.speakers.front().id;m_asset.nodes.push_back(std::move(n));m_selectedNode=static_cast<int>(m_asset.nodes.size()-1);m_dirty=true;}ImGui::EndChild();ImGui::SameLine();ImGui::BeginGroup();if(!m_asset.nodes.empty()){m_selectedNode=std::clamp(m_selectedNode,0,static_cast<int>(m_asset.nodes.size()-1));auto& n=m_asset.nodes[static_cast<std::size_t>(m_selectedNode)];ImGui::PushID("NodeDetails");m_dirty|=Text("Node ID",n.id);if(ImGui::BeginCombo("Speaker",n.speaker.c_str())){for(const auto& s:m_asset.speakers)if(ImGui::Selectable(s.id.c_str(),n.speaker==s.id)){n.speaker=s.id;m_dirty=true;}ImGui::EndCombo();}m_dirty|=Text("Line",n.text,4096);m_dirty|=Text("Line Localization Key",n.localizationKey);m_dirty|=AssetCombo("Voice Clip",EditorAssets::Type::Audio,n.voicePath,n.voiceId,assets);m_dirty|=Text("Camera Hook",n.cameraHook);m_dirty|=Text("Enter Event",n.enterEvent);m_dirty|=Text("Exit Event",n.exitEvent);if(ImGui::Button("Set as Entry")){m_asset.entryNode=n.id;m_dirty=true;}ImGui::SameLine();if(ImGui::Button("Delete Node")&&m_asset.nodes.size()>1){m_asset.nodes.erase(m_asset.nodes.begin()+m_selectedNode);m_selectedNode=std::max(0,m_selectedNode-1);m_dirty=true;ImGui::PopID();ImGui::EndGroup();engine::NormalizeDialogueAsset(m_asset);DrawFlowPreview();ImGui::End();return result;}ImGui::SeparatorText("Node Conditions");DrawConditions("NodeConditions",n.conditions,m_dirty);ImGui::SeparatorText("Choices");for(std::size_t i=0;i<n.choices.size();++i){auto& c=n.choices[i];ImGui::PushID(static_cast<int>(i));m_dirty|=Text("Choice Text",c.text);m_dirty|=Text("Choice Localization Key",c.localizationKey);const char* next=c.nextNode.empty()?"End Conversation":c.nextNode.c_str();if(ImGui::BeginCombo("Next Node",next)){if(ImGui::Selectable("End Conversation",c.nextNode.empty())){c.nextNode.clear();m_dirty=true;}for(const auto& candidate:m_asset.nodes)if(candidate.id!=n.id&&ImGui::Selectable(candidate.id.c_str(),c.nextNode==candidate.id)){c.nextNode=candidate.id;m_dirty=true;}ImGui::EndCombo();}m_dirty|=Text("Choice Event",c.event);DrawConditions("ChoiceConditions",c.conditions,m_dirty);if(ImGui::Button("Remove Choice")){n.choices.erase(n.choices.begin()+static_cast<std::ptrdiff_t>(i));m_dirty=true;ImGui::PopID();break;}ImGui::Separator();ImGui::PopID();}if(ImGui::Button("Add Choice")){n.choices.push_back({});m_dirty=true;}ImGui::PopID();}ImGui::EndGroup();
    engine::NormalizeDialogueAsset(m_asset);DrawFlowPreview();ImGui::SeparatorText("Live Conversation Debugger");DrawDebugger();std::string validation;if(!engine::ValidateDialogueAsset(m_asset,&validation))ImGui::TextColored({1,.4f,.3f,1},"%s",validation.c_str());if(m_dirty)ImGui::TextColored({1,.7f,.2f,1},"Unsaved changes");if(!m_status.empty())ImGui::TextWrapped("%s",m_status.c_str());ImGui::End();return result;}
