#include "InventoryItemEditorPanel.h"
#include "EditorPanels.h"

#include <imgui.h>
#include <imgui_stdlib.h>

#include <algorithm>
#include <cctype>
#include <filesystem>

namespace {std::string Safe(std::string value){for(char& c:value)if(!(std::isalnum(static_cast<unsigned char>(c))||c=='_'||c=='-'))c='_';return value.empty()?"Item":value;}template<class E>bool EnumCombo(const char* label,E& value,int count,const char*(*name)(E)){bool changed=false;if(ImGui::BeginCombo(label,name(value))){for(int i=0;i<count;++i){const auto v=static_cast<E>(i);if(ImGui::Selectable(name(v),value==v)){value=v;changed=true;}}ImGui::EndCombo();}return changed;}}
void InventoryItemEditorPanel::New(const std::string& root){m_asset={};m_asset.header.id=engine::AssetHandle::Generate();m_asset.name="NewItem";m_asset.displayName="New Item";m_path=(std::filesystem::path(root)/"GameAssets"/"Items"/"NewItem.3dgitem").string();m_dirty=true;m_status.clear();m_previewStacks.clear();}
bool InventoryItemEditorPanel::SaveForShutdown(const std::string& root,std::string* error){if(m_path.empty())New(root);if(!engine::SaveItemAsset(m_path,m_asset,error))return false;m_dirty=false;return true;}
bool InventoryItemEditorPanel::AssetCombo(const char* label,EditorAssets::Type type,std::string& path,engine::AssetHandle& id,EditorAssets& assets,bool allowNone){bool changed=false;const std::string preview=path.empty()?"None":std::filesystem::path(path).filename().string();if(ImGui::BeginCombo(label,preview.c_str())){if(allowNone&&ImGui::Selectable("None",path.empty())){path.clear();id={};changed=true;}for(const auto& candidate:assets.ContentAssetPaths(type)){ImGui::PushID(candidate.c_str());const auto name=std::filesystem::path(candidate).filename().string();if(ImGui::Selectable(name.c_str(),candidate==path)){path=candidate;id=assets.AssetIdForPath(candidate);changed=true;}ImGui::PopID();}ImGui::EndCombo();}return changed;}
InventoryItemEditorPanel::Result InventoryItemEditorPanel::Draw(EditorAssets& assets,const std::string& root,bool* open){Result result;if(!m_asset.header.id.Valid())New(root);if(!m_pendingOpen.empty()){std::string error;if(engine::LoadItemAsset(m_pendingOpen,&m_asset,&error)){m_path=m_pendingOpen;m_dirty=false;m_status="Loaded "+m_path;}else m_status=error;m_pendingOpen.clear();}if(!ImGui::Begin(EditorPanels::Name(EditorPanels::Panel::InventoryItemEditor),open)){ImGui::End();return result;}
    if(ImGui::Button("New Item"))New(root);ImGui::SameLine();if(ImGui::Button("Save")){std::string error;if(m_path.empty())m_path=(std::filesystem::path(root)/"GameAssets"/"Items"/(Safe(m_asset.name)+".3dgitem")).string();if(engine::SaveItemAsset(m_path,m_asset,&error)){m_dirty=false;result.saved=true;result.message="Saved item asset: "+m_path;}else result.message=error;}ImGui::SameLine();if(ImGui::Button("Add to Selected Inventory")){result.addSelected=true;result.count=m_addCount;result.maximumSlots=m_inventorySlots;result.maximumWeight=m_inventoryWeight;}ImGui::SameLine();ImGui::TextUnformatted(m_path.c_str());
    if(ImGui::BeginTabBar("InventoryItemTabs")){if(ImGui::BeginTabItem("Item Asset")){m_dirty|=ImGui::InputText("Internal Name",&m_asset.name);m_dirty|=ImGui::InputText("Display Name",&m_asset.displayName);m_dirty|=ImGui::InputTextMultiline("Description",&m_asset.description,{0,65});m_dirty|=ImGui::InputText("Localization Key",&m_asset.localizationKey);m_dirty|=EnumCombo("Item Type",m_asset.type,7,engine::ItemTypeName);m_dirty|=EnumCombo("Equipment Slot",m_asset.equipmentSlot,9,engine::EquipmentSlotName);m_dirty|=ImGui::DragInt("Maximum Stack",&m_asset.maximumStack,1,1,100000000);m_dirty|=ImGui::DragInt("Shop Value",&m_asset.value,1,0,100000000);m_dirty|=ImGui::DragFloat("Weight",&m_asset.weight,.05f,0,100000,"%.2f kg");m_dirty|=ImGui::Checkbox("Consumable",&m_asset.consumable);ImGui::SameLine();m_dirty|=ImGui::Checkbox("Droppable",&m_asset.droppable);ImGui::SameLine();m_dirty|=ImGui::Checkbox("Unique",&m_asset.unique);
        ImGui::SeparatorText("Presentation and Gameplay Assets");m_dirty|=AssetCombo("Icon",EditorAssets::Type::Texture,m_asset.iconPath,m_asset.iconId,assets);m_dirty|=AssetCombo("World Mesh",EditorAssets::Type::Model,m_asset.meshPath,m_asset.meshId,assets);m_dirty|=AssetCombo("Pickup Prefab",EditorAssets::Type::Prefab,m_asset.pickupPrefabPath,m_asset.pickupPrefabId,assets);m_dirty|=AssetCombo("Granted Ability",EditorAssets::Type::Ability,m_asset.abilityPath,m_asset.abilityId,assets);m_dirty|=AssetCombo("Use Animation",EditorAssets::Type::AnimationClip,m_asset.useAnimation,m_asset.useAnimationId,assets);m_dirty|=AssetCombo("Use Audio",EditorAssets::Type::Audio,m_asset.useAudio,m_asset.useAudioId,assets);m_dirty|=AssetCombo("Use Particle",EditorAssets::Type::Particle,m_asset.useParticle,m_asset.useParticleId,assets);
        ImGui::SeparatorText("Statistics");for(std::size_t i=0;i<m_asset.statistics.size();++i){ImGui::PushID(static_cast<int>(i));m_dirty|=ImGui::InputText("Name",&m_asset.statistics[i].name);ImGui::SameLine();m_dirty|=ImGui::DragFloat("Value",&m_asset.statistics[i].value,.1f,-1000000,1000000);ImGui::SameLine();if(ImGui::SmallButton("Remove")){m_asset.statistics.erase(m_asset.statistics.begin()+static_cast<std::ptrdiff_t>(i));m_dirty=true;ImGui::PopID();break;}ImGui::PopID();}if(ImGui::Button("Add Statistic")){m_asset.statistics.push_back({"Stat",0});m_dirty=true;}
        ImGui::SeparatorText("Use Effects");for(std::size_t i=0;i<m_asset.effects.size();++i){auto& effect=m_asset.effects[i];ImGui::PushID(static_cast<int>(i));m_dirty|=ImGui::InputText("Event",&effect.event);m_dirty|=ImGui::DragFloat("Magnitude",&effect.magnitude,.1f,-1000000,1000000);m_dirty|=AssetCombo("Effect Asset",EditorAssets::Type::Particle,effect.assetPath,effect.assetId,assets);if(ImGui::Button("Remove Effect")){m_asset.effects.erase(m_asset.effects.begin()+static_cast<std::ptrdiff_t>(i));m_dirty=true;ImGui::PopID();break;}ImGui::Separator();ImGui::PopID();}if(ImGui::Button("Add Effect")){m_asset.effects.push_back({});m_dirty=true;}
        ImGui::SeparatorText("Tags");for(std::size_t i=0;i<m_asset.tags.size();++i){ImGui::PushID(static_cast<int>(i));m_dirty|=ImGui::InputText("Tag",&m_asset.tags[i]);ImGui::SameLine();if(ImGui::SmallButton("Remove")){m_asset.tags.erase(m_asset.tags.begin()+static_cast<std::ptrdiff_t>(i));m_dirty=true;ImGui::PopID();break;}ImGui::PopID();}if(ImGui::Button("Add Tag")){m_asset.tags.push_back("Tag");m_dirty=true;}ImGui::EndTabItem();}
        if(ImGui::BeginTabItem("Inventory Setup and Debug")){ImGui::DragInt("Starting Count",&m_addCount,1,1,100000000);ImGui::DragInt("Maximum Slots",&m_inventorySlots,1,1,10000);ImGui::DragFloat("Maximum Weight",&m_inventoryWeight,.5f,0,1000000,"%.1f kg");ImGui::SeparatorText("Stacking Preview");if(ImGui::Button("Add Preview Item")){int remaining=m_addCount;for(auto& count:m_previewStacks){const int add=std::min(remaining,std::max(1,m_asset.maximumStack)-count);count+=add;remaining-=add;if(!remaining)break;}while(remaining>0&&static_cast<int>(m_previewStacks.size())<m_inventorySlots){const int add=std::min(remaining,std::max(1,m_asset.maximumStack));m_previewStacks.push_back(add);remaining-=add;}}ImGui::SameLine();if(ImGui::Button("Clear Preview"))m_previewStacks.clear();float weight=0;int total=0;for(std::size_t i=0;i<m_previewStacks.size();++i){total+=m_previewStacks[i];weight+=m_previewStacks[i]*m_asset.weight;ImGui::Text("Slot %d: %s x%d%s",static_cast<int>(i+1),m_asset.displayName.c_str(),m_previewStacks[i],m_asset.equipmentSlot==engine::EquipmentSlot::None?"":" [equipable]");}ImGui::Text("%d item(s), %d / %d slots, %.2f / %.2f kg",total,static_cast<int>(m_previewStacks.size()),m_inventorySlots,weight,m_inventoryWeight);if(weight>m_inventoryWeight)ImGui::TextColored({1,.35f,.25f,1},"Preview exceeds maximum weight.");ImGui::EndTabItem();}ImGui::EndTabBar();}
    engine::NormalizeItemAsset(m_asset);std::string validation;if(!engine::ValidateItemAsset(m_asset,&validation))ImGui::TextColored({1,.35f,.25f,1},"%s",validation.c_str());else ImGui::TextColored({.35f,1,.55f,1},"Item is valid.");if(m_dirty)ImGui::TextColored({1,.7f,.2f,1},"Unsaved changes");if(!m_status.empty())ImGui::TextWrapped("%s",m_status.c_str());ImGui::End();return result;}
