#include "MeshGeometryOperations.h"

#include <glm/glm.hpp>

#include <algorithm>
#include <cmath>
#include <limits>
#include <map>
#include <set>
#include <iterator>

namespace {
constexpr std::size_t S=engine::kStaticMeshVertexStride;
glm::vec3 P(const engine::StaticMeshSubMeshData& m,std::uint32_t i){const std::size_t o=static_cast<std::size_t>(i)*S;return {m.vertices[o],m.vertices[o+1],m.vertices[o+2]};}
void Set3(engine::StaticMeshSubMeshData& m,std::uint32_t i,std::size_t o,const glm::vec3& v){const std::size_t at=static_cast<std::size_t>(i)*S+o;m.vertices[at]=v.x;m.vertices[at+1]=v.y;m.vertices[at+2]=v.z;}
std::uint32_t AddVertex(engine::StaticMeshSubMeshData& m,const std::vector<std::pair<std::uint32_t,float>>& sources,const glm::vec3* position=nullptr){
    const std::uint32_t out=static_cast<std::uint32_t>(m.vertices.size()/S);for(std::size_t k=0;k<S;++k){float value=0;for(auto [i,w]:sources)value+=m.vertices[static_cast<std::size_t>(i)*S+k]*w;m.vertices.push_back(value);}if(position)Set3(m,out,0,*position);
    if(!m.vertexColors.empty())for(std::size_t k=0;k<4;++k){float value=0;for(auto [i,w]:sources)value+=m.vertexColors[static_cast<std::size_t>(i)*4+k]*w;m.vertexColors.push_back(value);}return out;
}
struct FaceRef{std::size_t sub=0;std::size_t offset=0;std::size_t global=0;};
std::vector<FaceRef> FaceRefs(const engine::StaticMeshAssetData& asset,const std::vector<std::size_t>& wanted){std::set<std::size_t> set(wanted.begin(),wanted.end());std::vector<FaceRef> refs;std::size_t global=0;for(std::size_t s=0;s<asset.subMeshes.size();++s)for(std::size_t i=0;i+2<asset.subMeshes[s].indices.size();i+=3,++global)if(set.count(global))refs.push_back({s,i,global});return refs;}
MeshGeometryOperations::Report Start(const engine::StaticMeshAssetData& a){MeshGeometryOperations::Report r;for(const auto&m:a.subMeshes){r.verticesBefore+=m.vertices.size()/S;r.trianglesBefore+=m.indices.size()/3;}return r;}
void Finish(const engine::StaticMeshAssetData&a,MeshGeometryOperations::Report&r){for(const auto&m:a.subMeshes){r.verticesAfter+=m.vertices.size()/S;r.trianglesAfter+=m.indices.size()/3;}}
}

MeshGeometryOperations::Report MeshGeometryOperations::ExtrudeFaces(engine::StaticMeshAssetData& a,const std::vector<std::size_t>& faces,float distance){auto r=Start(a);for(const auto& f:FaceRefs(a,faces)){auto&m=a.subMeshes[f.sub];const auto ia=m.indices[f.offset],ib=m.indices[f.offset+1],ic=m.indices[f.offset+2];const glm::vec3 pa=P(m,ia),pb=P(m,ib),pc=P(m,ic);glm::vec3 n=glm::cross(pb-pa,pc-pa);if(glm::dot(n,n)<1e-12f)continue;n=glm::normalize(n);const glm::vec3 pta=pa+n*distance,ptb=pb+n*distance,ptc=pc+n*distance;const auto ta=AddVertex(m,{{ia,1.0f}},&pta),tb=AddVertex(m,{{ib,1.0f}},&ptb),tc=AddVertex(m,{{ic,1.0f}},&ptc);m.indices[f.offset]=ta;m.indices[f.offset+1]=tb;m.indices[f.offset+2]=tc;const std::uint32_t sides[]={ia,ib,tb,ia,tb,ta,ib,ic,tc,ib,tc,tb,ic,ia,ta,ic,ta,tc};m.indices.insert(m.indices.end(),std::begin(sides),std::end(sides));++r.changed;}RecalculateNormalsAndTangents(a);RecalculateBounds(a);Finish(a,r);return r;}
MeshGeometryOperations::Report MeshGeometryOperations::InsetFaces(engine::StaticMeshAssetData& a,const std::vector<std::size_t>& faces,float amount){auto r=Start(a);amount=std::clamp(amount,0.001f,.999f);for(const auto& f:FaceRefs(a,faces)){auto&m=a.subMeshes[f.sub];const auto ia=m.indices[f.offset],ib=m.indices[f.offset+1],ic=m.indices[f.offset+2];const auto na=AddVertex(m,{{ia,1-amount},{ib,amount*.5f},{ic,amount*.5f}}),nb=AddVertex(m,{{ib,1-amount},{ia,amount*.5f},{ic,amount*.5f}}),nc=AddVertex(m,{{ic,1-amount},{ia,amount*.5f},{ib,amount*.5f}});m.indices[f.offset]=na;m.indices[f.offset+1]=nb;m.indices[f.offset+2]=nc;const std::uint32_t ring[]={ia,ib,nb,ia,nb,na,ib,ic,nc,ib,nc,nb,ic,ia,na,ic,na,nc};m.indices.insert(m.indices.end(),std::begin(ring),std::end(ring));++r.changed;}RecalculateNormalsAndTangents(a);RecalculateBounds(a);Finish(a,r);return r;}
MeshGeometryOperations::Report MeshGeometryOperations::SubdivideFaces(engine::StaticMeshAssetData& a,const std::vector<std::size_t>& faces){auto r=Start(a);for(const auto&f:FaceRefs(a,faces)){auto&m=a.subMeshes[f.sub];const auto ia=m.indices[f.offset],ib=m.indices[f.offset+1],ic=m.indices[f.offset+2];const auto ab=AddVertex(m,{{ia,.5f},{ib,.5f}}),bc=AddVertex(m,{{ib,.5f},{ic,.5f}}),ca=AddVertex(m,{{ic,.5f},{ia,.5f}});m.indices[f.offset]=ia;m.indices[f.offset+1]=ab;m.indices[f.offset+2]=ca;const std::uint32_t extra[]={ab,ib,bc,ca,bc,ic,ab,bc,ca};m.indices.insert(m.indices.end(),std::begin(extra),std::end(extra));++r.changed;}RecalculateNormalsAndTangents(a);RecalculateBounds(a);Finish(a,r);return r;}
MeshGeometryOperations::Report MeshGeometryOperations::DeleteFaces(engine::StaticMeshAssetData& a,const std::vector<std::size_t>& faces){auto r=Start(a);std::set<std::size_t>w(faces.begin(),faces.end());std::size_t global=0;for(auto&m:a.subMeshes){std::vector<std::uint32_t>keep;for(std::size_t i=0;i+2<m.indices.size();i+=3,++global)if(!w.count(global))keep.insert(keep.end(),{m.indices[i],m.indices[i+1],m.indices[i+2]});else++r.changed;m.indices=std::move(keep);}RecalculateBounds(a);Finish(a,r);return r;}
MeshGeometryOperations::Report MeshGeometryOperations::WeldVertices(engine::StaticMeshAssetData&a,float tolerance){auto r=Start(a);tolerance=std::max(tolerance,1e-7f);for(auto&m:a.subMeshes){const std::size_t count=m.vertices.size()/S;std::vector<std::uint32_t>remap(count);std::vector<float>verts,colors;for(std::uint32_t i=0;i<count;++i){std::uint32_t found=std::numeric_limits<std::uint32_t>::max();for(std::uint32_t j=0;j<verts.size()/S;++j){glm::vec3 q{verts[j*S],verts[j*S+1],verts[j*S+2]};if(glm::length(P(m,i)-q)<=tolerance){found=j;break;}}if(found==std::numeric_limits<std::uint32_t>::max()){found=static_cast<std::uint32_t>(verts.size()/S);verts.insert(verts.end(),m.vertices.begin()+i*S,m.vertices.begin()+(i+1)*S);if(!m.vertexColors.empty())colors.insert(colors.end(),m.vertexColors.begin()+i*4,m.vertexColors.begin()+(i+1)*4);}else++r.changed;remap[i]=found;}for(auto&i:m.indices)if(i<remap.size())i=remap[i];m.vertices=std::move(verts);m.vertexColors=std::move(colors);}RemoveDegenerate(a,1e-10f);RecalculateNormalsAndTangents(a);RecalculateBounds(a);Finish(a,r);return r;}
MeshGeometryOperations::Report MeshGeometryOperations::RemoveDegenerate(engine::StaticMeshAssetData&a,float tolerance){auto r=Start(a);for(auto&m:a.subMeshes){std::vector<std::uint32_t>keep;for(std::size_t i=0;i+2<m.indices.size();i+=3){const auto ia=m.indices[i],ib=m.indices[i+1],ic=m.indices[i+2];if(ia==ib||ib==ic||ic==ia||glm::length(glm::cross(P(m,ib)-P(m,ia),P(m,ic)-P(m,ia)))<=tolerance)++r.changed;else keep.insert(keep.end(),{ia,ib,ic});}m.indices=std::move(keep);}Finish(a,r);return r;}
MeshGeometryOperations::Report MeshGeometryOperations::BridgeLoops(engine::StaticMeshAssetData&a,std::size_t sub,const std::vector<std::uint32_t>&x,const std::vector<std::uint32_t>&y){auto r=Start(a);if(sub<a.subMeshes.size()&&x.size()==y.size()&&x.size()>=2){auto&m=a.subMeshes[sub];const auto count=m.vertices.size()/S;for(std::size_t i=0;i+1<x.size();++i)if(x[i]<count&&x[i+1]<count&&y[i]<count&&y[i+1]<count){m.indices.insert(m.indices.end(),{x[i],x[i+1],y[i+1],x[i],y[i+1],y[i]});++r.changed;}}RecalculateNormalsAndTangents(a);Finish(a,r);return r;}
void MeshGeometryOperations::RecalculateNormalsAndTangents(engine::StaticMeshAssetData&a){for(auto&m:a.subMeshes){const std::size_t count=m.vertices.size()/S;std::vector<glm::vec3>normals(count,glm::vec3(0)),tangents(count,glm::vec3(0));for(std::size_t i=0;i+2<m.indices.size();i+=3){const auto ia=m.indices[i],ib=m.indices[i+1],ic=m.indices[i+2];if(ia>=count||ib>=count||ic>=count)continue;const glm::vec3 pa=P(m,ia),pb=P(m,ib),pc=P(m,ic),n=glm::cross(pb-pa,pc-pa);normals[ia]+=n;normals[ib]+=n;normals[ic]+=n;const std::size_t oa=ia*S,ob=ib*S,oc=ic*S;glm::vec2 ua{m.vertices[oa+6],m.vertices[oa+7]},ub{m.vertices[ob+6],m.vertices[ob+7]},uc{m.vertices[oc+6],m.vertices[oc+7]};const glm::vec2 d1=ub-ua,d2=uc-ua;const float det=d1.x*d2.y-d1.y*d2.x;if(std::abs(det)>1e-10f){const glm::vec3 t=((pb-pa)*d2.y-(pc-pa)*d1.y)/det;tangents[ia]+=t;tangents[ib]+=t;tangents[ic]+=t;}}for(std::uint32_t i=0;i<count;++i){glm::vec3 n=normals[i],t=tangents[i];n=glm::dot(n,n)>1e-12f?glm::normalize(n):glm::vec3(0,1,0);t-=n*glm::dot(n,t);t=glm::dot(t,t)>1e-12f?glm::normalize(t):glm::vec3(1,0,0);Set3(m,i,3,n);Set3(m,i,8,t);}}}
void MeshGeometryOperations::RecalculateBounds(engine::StaticMeshAssetData&a){glm::vec3 mn(std::numeric_limits<float>::max()),mx(-std::numeric_limits<float>::max());bool any=false;for(const auto&m:a.subMeshes)for(std::uint32_t i=0;i<m.vertices.size()/S;++i){const glm::vec3 p=P(m,i);mn=glm::min(mn,p);mx=glm::max(mx,p);any=true;}if(!any)mn=mx=glm::vec3(0);a.minimum={mn.x,mn.y,mn.z};a.maximum={mx.x,mx.y,mx.z};}
MeshGeometryOperations::TopologyReport MeshGeometryOperations::AnalyzeTopology(const engine::StaticMeshAssetData&a,float tolerance){TopologyReport report;for(const auto&m:a.subMeshes){std::map<std::pair<std::uint32_t,std::uint32_t>,std::size_t>edges;const auto edge=[&](std::uint32_t x,std::uint32_t y){if(x>y)std::swap(x,y);++edges[{x,y}];};for(std::size_t i=0;i+2<m.indices.size();i+=3){const auto ia=m.indices[i],ib=m.indices[i+1],ic=m.indices[i+2];if(ia==ib||ib==ic||ic==ia||glm::length(glm::cross(P(m,ib)-P(m,ia),P(m,ic)-P(m,ia)))<=tolerance)++report.degenerateFaces;edge(ia,ib);edge(ib,ic);edge(ic,ia);}for(const auto&[unused,count]:edges){(void)unused;if(count==1)++report.boundaryEdges;else if(count>2)++report.nonManifoldEdges;}}return report;}
bool MeshGeometryOperations::Validate(const engine::StaticMeshAssetData&a,std::string* error){for(std::size_t s=0;s<a.subMeshes.size();++s){const auto&m=a.subMeshes[s];if(m.vertices.size()%S){if(error)*error="Submesh vertex buffer has an invalid stride.";return false;}const std::size_t count=m.vertices.size()/S;if(m.indices.size()%3){if(error)*error="Submesh index buffer is not triangular.";return false;}for(auto i:m.indices)if(i>=count){if(error)*error="Submesh contains an out-of-range index.";return false;}if(!m.vertexColors.empty()&&m.vertexColors.size()!=count*4){if(error)*error="Vertex color count does not match geometry.";return false;}}if(error)error->clear();return true;}
