#include "PoseLibraryPanel.h"
#include "EditorPanels.h"

#include <engine/animation/Animator.h>
#include <imgui.h>
#include <glm/gtc/type_ptr.hpp>

#include <algorithm>
#include <cctype>
#include <cstdio>
#include <filesystem>
#include <sstream>

namespace {
std::string Full(const std::string& root,const std::string& path){if(path.empty())return{};std::filesystem::path p(path);return p.is_absolute()?p.string():(std::filesystem::path(root)/p).string();}
std::string Safe(std::string v){for(char& c:v)if(!std::isalnum(static_cast<unsigned char>(c))&&c!='_'&&c!='-')c='_';return v.empty()?"NewPoseLibrary":v;}
bool Text(const char* label,std::string& v){char b[256]{};std::snprintf(b,sizeof(b),"%s",v.c_str());if(!ImGui::InputText(label,b,sizeof(b)))return false;v=b;return true;}
std::string Join(const std::vector<std::string>& values){std::string out;for(const auto& v:values){if(!out.empty())out+=", ";out+=v;}return out;}
std::vector<std::string> Split(const std::string& text){std::vector<std::string> out;std::stringstream s(text);std::string v;while(std::getline(s,v,',')){const auto a=v.find_first_not_of(" \t"),b=v.find_last_not_of(" \t");if(a!=std::string::npos)out.push_back(v.substr(a,b-a+1));}return out;}
engine::BoneLocal Bind(const glm::mat4& m){engine::BoneLocal o;o.pos=glm::vec3(m[3]);o.scale={glm::length(glm::vec3(m[0])),glm::length(glm::vec3(m[1])),glm::length(glm::vec3(m[2]))};glm::mat3 r(m);for(int i=0;i<3;++i)if(o.scale[i]>1e-6f)r[i]/=o.scale[i];o.rot=glm::normalize(glm::quat_cast(r));return o;}
}

void PoseLibraryPanel::New(const std::string& root){m_asset={};m_asset.header.id=engine::AssetHandle::Generate();m_path=(std::filesystem::path(root)/"GameAssets"/"PoseLibraries"/"NewPoseLibrary.3dgpose").string();m_skeletonLoaded=m_animationLoaded=false;m_selectedPose=m_selectedBone=-1;m_dirty=true;m_status.clear();}
bool PoseLibraryPanel::LoadSkeleton(const std::string& root,std::string* error){m_skeletonLoaded=engine::LoadSkeletonAsset(Full(root,m_asset.skeletonPath),&m_skeleton,error);if(m_skeletonLoaded)SampleSource();return m_skeletonLoaded;}
bool PoseLibraryPanel::LoadAnimation(const std::string& root,std::string* error){m_animationLoaded=engine::LoadAnimationAsset(Full(root,m_animationPath),&m_animation,error);if(m_animationLoaded)SampleSource();return m_animationLoaded;}
bool PoseLibraryPanel::Load(const std::string& path,const std::string& root,std::string* error){if(!engine::LoadPoseLibraryAsset(path,&m_asset,error))return false;m_path=path;m_selectedPose=m_asset.poses.empty()?-1:0;m_selectedBone=-1;m_dirty=false;LoadSkeleton(root,error);return true;}
bool PoseLibraryPanel::SaveForShutdown(const std::string& root,std::string* error){if(m_path.empty())New(root);if(!engine::SavePoseLibraryAsset(m_path,m_asset,error))return false;m_dirty=false;return true;}
void PoseLibraryPanel::SampleSource(){if(!m_skeletonLoaded)return;if(m_animationLoaded&&!m_animation.clips.empty())engine::Animator::SampleLocal(m_skeleton.skeleton,m_animation.clips.front().animation,m_time,m_sourcePose);else{m_sourcePose.resize(m_skeleton.skeleton.bones.size());for(std::size_t i=0;i<m_sourcePose.size();++i)m_sourcePose[i]=Bind(m_skeleton.skeleton.bones[i].localBind);}}

void PoseLibraryPanel::DrawPreview(){const ImVec2 size(std::max(280.f,ImGui::GetContentRegionAvail().x),420.f);ImGui::InvisibleButton("##PosePreview",size);auto* d=ImGui::GetWindowDrawList();const ImVec2 mn=ImGui::GetItemRectMin(),mx=ImGui::GetItemRectMax();d->AddRectFilled(mn,mx,IM_COL32(13,17,23,255));if(!m_skeletonLoaded){d->AddText({mn.x+12,mn.y+12},IM_COL32(190,190,195,255),"Choose a skeleton to preview poses.");return;}
    std::vector<engine::BoneLocal> local=m_sourcePose;if(m_selectedPose>=0&&m_selectedPose<(int)m_asset.poses.size()){std::vector<engine::BoneLocal> authored,mixed;engine::ResolvePoseForSkeleton(m_asset.poses[(std::size_t)m_selectedPose],m_skeleton.skeleton,authored);engine::Animator::BlendLocal(local,authored,m_previewBlend,mixed);local=std::move(mixed);}std::vector<glm::mat4>w(local.size());std::vector<glm::vec3>p(local.size());glm::vec2 lo(1e9f),hi(-1e9f);
    for(std::size_t i=0;i<local.size();++i){const auto&m=glm::translate(glm::mat4(1),local[i].pos)*glm::mat4_cast(local[i].rot)*glm::scale(glm::mat4(1),local[i].scale);const int parent=m_skeleton.skeleton.bones[i].parent;w[i]=parent>=0?w[(std::size_t)parent]*m:m;p[i]=glm::vec3(w[i][3]);lo=glm::min(lo,glm::vec2(p[i]));hi=glm::max(hi,glm::vec2(p[i]));}const glm::vec2 span=glm::max(hi-lo,glm::vec2(.01f));const float s=std::min((size.x-40)/span.x,(size.y-40)/span.y);auto project=[&](glm::vec3 v){return ImVec2(mn.x+20+(v.x-lo.x)*s,mx.y-20-(v.y-lo.y)*s);};
    for(std::size_t i=0;i<p.size();++i){const int parent=m_skeleton.skeleton.bones[i].parent;if(parent>=0)d->AddLine(project(p[(std::size_t)parent]),project(p[i]),IM_COL32(75,205,240,255),2);if((int)i==m_selectedBone)d->AddCircleFilled(project(p[i]),5,IM_COL32(255,180,35,255));}}

PoseLibraryPanel::Result PoseLibraryPanel::Draw(EditorAssets& assets,const std::string& root,bool* open){Result result;if(!m_asset.header.id.Valid())New(root);if(!m_pendingOpen.empty()){std::string e;if(!Load(m_pendingOpen,root,&e))m_status=e;else m_status="Loaded "+m_pendingOpen;m_pendingOpen.clear();}if(!ImGui::Begin(EditorPanels::Name(EditorPanels::Panel::PoseLibrary),open)){ImGui::End();return result;}
    if(ImGui::Button("New"))New(root);ImGui::SameLine();if(ImGui::Button("Save")){if(m_path.empty())m_path=(std::filesystem::path(root)/"GameAssets"/"PoseLibraries"/(Safe(m_asset.name)+".3dgpose")).string();std::string e;if(engine::SavePoseLibraryAsset(m_path,m_asset,&e)){m_dirty=false;result.saved=true;result.message="Saved pose library: "+m_path;}else result.message=e;}ImGui::SameLine();ImGui::TextUnformatted(m_path.c_str());m_dirty|=Text("Library Name",m_asset.name);
    const auto skeletonLabel=m_asset.skeletonPath.empty()?"Choose skeleton...":std::filesystem::path(m_asset.skeletonPath).filename().string();if(ImGui::BeginCombo("Skeleton",skeletonLabel.c_str())){for(const auto& p:assets.ContentAssetPaths(EditorAssets::Type::Skeleton)){ImGui::PushID(p.c_str());if(ImGui::Selectable(std::filesystem::path(p).filename().string().c_str(),p==m_asset.skeletonPath)){m_asset.skeletonPath=p;m_asset.skeletonId=assets.AssetIdForPath(p);std::string e;if(!LoadSkeleton(root,&e))m_status=e;m_dirty=true;}ImGui::PopID();}ImGui::EndCombo();}
    const auto animLabel=m_animationPath.empty()?"Bind pose":std::filesystem::path(m_animationPath).filename().string();if(ImGui::BeginCombo("Capture Source",animLabel.c_str())){if(ImGui::Selectable("Bind pose",m_animationPath.empty())){m_animationPath.clear();m_animationLoaded=false;SampleSource();}for(const auto&p:assets.ContentAssetPaths(EditorAssets::Type::Animation)){ImGui::PushID(p.c_str());if(ImGui::Selectable(std::filesystem::path(p).filename().string().c_str(),p==m_animationPath)){m_animationPath=p;std::string e;if(!LoadAnimation(root,&e))m_status=e;}ImGui::PopID();}ImGui::EndCombo();}
    if(m_animationLoaded&&!m_animation.clips.empty()){const auto& clip=m_animation.clips.front().animation;const float duration=engine::AnimationPlaybackSeconds(clip);if(ImGui::SliderFloat("Capture Time",&m_time,0,std::max(duration,.001f),"%.3f s"))SampleSource();}ImGui::SliderFloat("Preview Blend",&m_previewBlend,0,1);
    ImGui::Columns(2,"##PoseLibraryColumns",true);ImGui::SeparatorText("Poses");Text("Search",m_search);
    for(std::size_t i=0;i<m_asset.poses.size();++i){const auto&pose=m_asset.poses[i];std::string hay=pose.name+" "+Join(pose.tags);if(!m_search.empty()&&hay.find(m_search)==std::string::npos)continue;ImGui::PushID((int)i);if(ImGui::Selectable(pose.name.c_str(),m_selectedPose==(int)i)){m_selectedPose=(int)i;m_selectedBone=-1;}ImGui::PopID();}
    if(ImGui::Button("Capture Current")&&m_skeletonLoaded){engine::PoseLibraryPose pose;pose.name="Pose_"+std::to_string(m_asset.poses.size()+1);for(std::size_t i=0;i<m_sourcePose.size();++i)pose.bones.push_back({m_skeleton.skeleton.bones[i].name,m_sourcePose[i]});m_asset.poses.push_back(std::move(pose));m_selectedPose=(int)m_asset.poses.size()-1;m_dirty=true;}ImGui::SameLine();if(ImGui::Button("Mirror")&&m_selectedPose>=0){m_asset.poses.push_back(engine::MirrorPose(m_asset.poses[(std::size_t)m_selectedPose]));m_selectedPose=(int)m_asset.poses.size()-1;m_dirty=true;}ImGui::SameLine();if(ImGui::Button("Delete")&&m_selectedPose>=0){m_asset.poses.erase(m_asset.poses.begin()+m_selectedPose);m_selectedPose=std::min(m_selectedPose,(int)m_asset.poses.size()-1);m_dirty=true;}
    if(m_selectedPose>=0&&m_selectedPose<(int)m_asset.poses.size()){auto&pose=m_asset.poses[(std::size_t)m_selectedPose];m_dirty|=Text("Pose Name",pose.name);std::string tags=Join(pose.tags);if(Text("Tags",tags)){pose.tags=Split(tags);m_dirty=true;}ImGui::SeparatorText("Bones");for(std::size_t i=0;i<pose.bones.size();++i){ImGui::PushID((int)i);if(ImGui::Selectable(pose.bones[i].name.c_str(),m_selectedBone==(int)i))m_selectedBone=(int)i;ImGui::PopID();}}
    ImGui::NextColumn();ImGui::SeparatorText("Preview");DrawPreview();if(m_selectedPose>=0&&m_selectedPose<(int)m_asset.poses.size()&&m_selectedBone>=0&&m_selectedBone<(int)m_asset.poses[(std::size_t)m_selectedPose].bones.size()){auto&b=m_asset.poses[(std::size_t)m_selectedPose].bones[(std::size_t)m_selectedBone];glm::vec3 degrees=glm::degrees(glm::eulerAngles(b.local.rot));m_dirty|=ImGui::DragFloat3("Position",glm::value_ptr(b.local.pos),.005f);if(ImGui::DragFloat3("Rotation",glm::value_ptr(degrees),.25f)){b.local.rot=glm::quat(glm::radians(degrees));m_dirty=true;}m_dirty|=ImGui::DragFloat3("Scale",glm::value_ptr(b.local.scale),.005f,.0001f,100.f);}
    ImGui::Columns(1);engine::NormalizePoseLibraryAsset(m_asset);if(m_dirty)ImGui::TextColored({1,.7f,.2f,1},"Unsaved changes");if(!m_status.empty())ImGui::TextWrapped("%s",m_status.c_str());ImGui::End();return result;}
