#include "QuestEditorPanel.h"
#include "EditorPanels.h"

#include <imgui.h>

#include <algorithm>
#include <cstdio>
#include <filesystem>

namespace {
bool Text(const char* label,std::string& value,std::size_t size=512){std::vector<char> buffer(size);std::snprintf(buffer.data(),buffer.size(),"%s",value.c_str());if(!ImGui::InputText(label,buffer.data(),buffer.size()))return false;value=buffer.data();return true;}
template<class E>bool Combo(const char* label,E& value,int count,const char*(*name)(E)){bool changed=false;if(ImGui::BeginCombo(label,name(value))){for(int i=0;i<count;++i){const auto v=static_cast<E>(i);if(ImGui::Selectable(name(v),v==value)){value=v;changed=true;}}ImGui::EndCombo();}return changed;}
}

void QuestEditorPanel::New(const std::string& root){m_asset={};m_asset.header.id=engine::AssetHandle::Generate();m_asset.name="NewQuest";m_asset.title="New Quest";m_asset.objectives.push_back({});m_path=(std::filesystem::path(root)/"GameAssets"/"Quests"/"NewQuest.3dgquest").string();m_previewProgress.assign(1,0);m_previewActive=false;m_previewFailed=false;m_dirty=true;m_status.clear();}
bool QuestEditorPanel::SaveForShutdown(const std::string& root,std::string* error){if(m_path.empty())New(root);if(!engine::SaveQuestAsset(m_path,m_asset,error))return false;m_dirty=false;return true;}
bool QuestEditorPanel::AssetCombo(const char* label,EditorAssets::Type type,std::string& path,engine::AssetHandle& id,EditorAssets& assets){bool changed=false;const std::string preview=path.empty()?"None":std::filesystem::path(path).filename().string();if(ImGui::BeginCombo(label,preview.c_str())){if(ImGui::Selectable("None",path.empty())){path.clear();id={};changed=true;}for(const auto& candidate:assets.ContentAssetPaths(type)){ImGui::PushID(candidate.c_str());const std::string n=std::filesystem::path(candidate).filename().string();if(ImGui::Selectable(n.c_str(),candidate==path)){path=candidate;id=assets.AssetIdForPath(candidate);changed=true;}ImGui::PopID();}ImGui::EndCombo();}return changed;}

void QuestEditorPanel::DrawDebugger(){
    if(m_previewProgress.size()!=m_asset.objectives.size())m_previewProgress.resize(m_asset.objectives.size());
    if(ImGui::Button(m_previewActive?"Restart Quest":"Start Quest")){std::fill(m_previewProgress.begin(),m_previewProgress.end(),0);m_previewActive=true;m_previewFailed=false;}
    ImGui::SameLine();if(ImGui::Button("Fail Quest")){m_previewActive=false;m_previewFailed=true;}
    ImGui::SameLine();if(ImGui::Button("Reset")){std::fill(m_previewProgress.begin(),m_previewProgress.end(),0);m_previewActive=false;m_previewFailed=false;}
    bool complete=m_previewActive&&!m_asset.objectives.empty();for(std::size_t i=0;i<m_asset.objectives.size();++i)if(!m_asset.objectives[i].optional&&m_previewProgress[i]<m_asset.objectives[i].requiredCount)complete=false;
    const char* state=m_previewFailed?"Failed":complete?"Completed":m_previewActive?"Active":"Inactive";
    ImGui::Text("Runtime state: %s",state);
    for(std::size_t i=0;i<m_asset.objectives.size();++i){const auto& objective=m_asset.objectives[i];ImGui::PushID(static_cast<int>(i));const float fraction=static_cast<float>(m_previewProgress[i])/std::max(1,objective.requiredCount);const std::string label=objective.id+"  "+std::to_string(m_previewProgress[i])+" / "+std::to_string(objective.requiredCount);ImGui::ProgressBar(fraction,{-85,0},label.c_str());ImGui::SameLine();if(ImGui::SmallButton("Advance")&&m_previewActive)m_previewProgress[i]=std::min(objective.requiredCount,m_previewProgress[i]+1);ImGui::PopID();}
}

QuestEditorPanel::Result QuestEditorPanel::Draw(EditorAssets& assets,const std::string& root,bool* open){Result result;if(!m_asset.header.id.Valid())New(root);if(!m_pendingOpen.empty()){std::string error;if(engine::LoadQuestAsset(m_pendingOpen,&m_asset,&error)){m_path=m_pendingOpen;m_dirty=false;m_status="Loaded "+m_path;m_previewProgress.assign(m_asset.objectives.size(),0);}else m_status=error;m_pendingOpen.clear();}
    if(!ImGui::Begin(EditorPanels::Name(EditorPanels::Panel::QuestEditor),open)){ImGui::End();return result;}
    if(ImGui::Button("New"))New(root);ImGui::SameLine();if(ImGui::Button("Save")){std::string error;if(engine::SaveQuestAsset(m_path,m_asset,&error)){m_dirty=false;result.saved=true;result.message="Saved quest asset: "+m_path;}else result.message=error;}ImGui::SameLine();if(ImGui::Button("Grant to Selected"))result.grantSelected=true;ImGui::SameLine();ImGui::TextUnformatted(m_path.c_str());
    m_dirty|=Text("Internal Name",m_asset.name);m_dirty|=Text("Display Title",m_asset.title);m_dirty|=Text("Description",m_asset.description,2048);m_dirty|=ImGui::Checkbox("Auto Start",&m_asset.autoStart);ImGui::SameLine();m_dirty|=ImGui::Checkbox("Repeatable",&m_asset.repeatable);ImGui::SameLine();m_dirty|=ImGui::Checkbox("Hidden Until Started",&m_asset.hiddenUntilStarted);
    ImGui::SeparatorText("Start Conditions");for(std::size_t i=0;i<m_asset.startConditions.size();++i){auto& c=m_asset.startConditions[i];ImGui::PushID(static_cast<int>(i));m_dirty|=Text("Flag",c.flag);ImGui::SameLine();m_dirty|=ImGui::Checkbox("Expected",&c.expected);ImGui::SameLine();if(ImGui::SmallButton("Remove")){m_asset.startConditions.erase(m_asset.startConditions.begin()+static_cast<std::ptrdiff_t>(i));m_dirty=true;ImGui::PopID();break;}ImGui::PopID();}if(ImGui::Button("Add Start Condition")){m_asset.startConditions.push_back({});m_dirty=true;}
    ImGui::SeparatorText("Objectives");
    ImGui::BeginChild("QuestObjectiveList",{210,300},true);for(std::size_t i=0;i<m_asset.objectives.size();++i){ImGui::PushID(static_cast<int>(i));const std::string label=m_asset.objectives[i].id+"##objective";if(ImGui::Selectable(label.c_str(),m_selectedObjective==static_cast<int>(i)))m_selectedObjective=static_cast<int>(i);ImGui::PopID();}if(ImGui::Button("Add Objective")){engine::QuestObjective o;o.id="Objective"+std::to_string(m_asset.objectives.size()+1);m_asset.objectives.push_back(std::move(o));m_selectedObjective=static_cast<int>(m_asset.objectives.size()-1);m_dirty=true;}ImGui::EndChild();ImGui::SameLine();
    ImGui::BeginGroup();if(!m_asset.objectives.empty()){m_selectedObjective=std::clamp(m_selectedObjective,0,static_cast<int>(m_asset.objectives.size()-1));auto& o=m_asset.objectives[static_cast<std::size_t>(m_selectedObjective)];ImGui::PushID(m_selectedObjective);m_dirty|=Text("Objective ID",o.id);m_dirty|=Text("Objective Description",o.description);m_dirty|=Combo("Type",o.type,5,engine::QuestObjectiveTypeName);m_dirty|=Text("Target",o.target);m_dirty|=ImGui::DragInt("Required Count",&o.requiredCount,1,1,100000000);m_dirty|=ImGui::Checkbox("Optional",&o.optional);ImGui::SameLine();m_dirty|=ImGui::Checkbox("Checkpoint",&o.checkpoint);
        const char* prerequisite=o.requiredObjective.empty()?"None":o.requiredObjective.c_str();if(ImGui::BeginCombo("Required Objective",prerequisite)){if(ImGui::Selectable("None",o.requiredObjective.empty())){o.requiredObjective.clear();m_dirty=true;}for(const auto& candidate:m_asset.objectives)if(candidate.id!=o.id&&ImGui::Selectable(candidate.id.c_str(),candidate.id==o.requiredObjective)){o.requiredObjective=candidate.id;m_dirty=true;}ImGui::EndCombo();}m_dirty|=Text("Required Flag",o.requiredFlag);m_dirty|=Text("Dialogue Trigger",o.dialogueTrigger);if(ImGui::Button("Delete Objective")&&m_asset.objectives.size()>1){m_asset.objectives.erase(m_asset.objectives.begin()+m_selectedObjective);m_selectedObjective=std::max(0,m_selectedObjective-1);m_dirty=true;}ImGui::PopID();}ImGui::EndGroup();
    ImGui::SeparatorText("Rewards");for(std::size_t i=0;i<m_asset.rewards.size();++i){auto& reward=m_asset.rewards[i];ImGui::PushID(static_cast<int>(i));m_dirty|=Combo("Reward Type",reward.type,4,engine::QuestRewardTypeName);m_dirty|=Text("Reward Name",reward.name);m_dirty|=ImGui::DragInt("Amount",&reward.amount,1,1,100000000);if(reward.type==engine::QuestRewardType::Ability)m_dirty|=AssetCombo("Ability",EditorAssets::Type::Ability,reward.assetPath,reward.assetId,assets);if(ImGui::Button("Remove Reward")){m_asset.rewards.erase(m_asset.rewards.begin()+static_cast<std::ptrdiff_t>(i));m_dirty=true;ImGui::PopID();break;}ImGui::Separator();ImGui::PopID();}if(ImGui::Button("Add Reward")){m_asset.rewards.push_back({});m_dirty=true;}
    engine::NormalizeQuestAsset(m_asset);ImGui::SeparatorText("Live Quest Debugger");DrawDebugger();std::string validation;if(!engine::ValidateQuestAsset(m_asset,&validation))ImGui::TextColored({1,.4f,.3f,1},"%s",validation.c_str());if(m_dirty)ImGui::TextColored({1,.7f,.2f,1},"Unsaved changes");if(!m_status.empty())ImGui::TextWrapped("%s",m_status.c_str());ImGui::End();return result;}
