#include "UiLocalizationPreviewPanel.h"

#include "EditorPanels.h"

#include <engine/gameplay/Localization.h>
#include <engine/ui/TextShaping.h>
#include <imgui.h>

#include <algorithm>
#include <cctype>
#include <cmath>
#include <fstream>
#include <sstream>

namespace {
constexpr UiLocalizationPreviewPanel::Resolution kResolutions[] = {
    {"1280 x 720 (HD)",1280,720},{"1920 x 1080 (Full HD)",1920,1080},
    {"2560 x 1440 (QHD)",2560,1440},{"3440 x 1440 (Ultrawide)",3440,1440},
    {"3840 x 2160 (4K)",3840,2160},{"1080 x 1920 (Portrait)",1080,1920},
    {"1170 x 2532 (Phone)",1170,2532},{"Custom",0,0}
};
ImU32 Color(const glm::vec4& c){return IM_COL32(static_cast<int>(std::clamp(c.r,0.0f,1.0f)*255),static_cast<int>(std::clamp(c.g,0.0f,1.0f)*255),static_cast<int>(std::clamp(c.b,0.0f,1.0f)*255),static_cast<int>(std::clamp(c.a,0.0f,1.0f)*255));}
std::string Lower(std::string value){std::transform(value.begin(),value.end(),value.begin(),[](unsigned char c){return static_cast<char>(std::tolower(c));});return value;}
std::string Substitute(std::string value,const std::string& tokenValue){for(auto pos=value.find("{}");pos!=std::string::npos;pos=value.find("{}",pos+tokenValue.size()))value.replace(pos,2,tokenValue);return value;}
std::string Number(float value){std::ostringstream out;if(std::fabs(value-std::round(value))<0.001f)out<<static_cast<long long>(std::llround(value));else{out.setf(std::ios::fixed);out.precision(1);out<<value;}return out.str();}
bool Within(float x,float y,float w,float h,float left,float top,float right,float bottom){return x>=left&&y>=top&&x+w<=right&&y+h<=bottom;}
}

void UiLocalizationPreviewPanel::RefreshLocalizationAssets(const std::filesystem::path& root){m_localizationAssets.clear();std::error_code ec;if(std::filesystem::is_directory(root,ec))for(std::filesystem::recursive_directory_iterator it(root,std::filesystem::directory_options::skip_permission_denied,ec),end;!ec&&it!=end;it.increment(ec))if(it->is_regular_file(ec)&&Lower(it->path().extension().string())==".3dgloc")m_localizationAssets.push_back(it->path());std::sort(m_localizationAssets.begin(),m_localizationAssets.end());m_localizationIndex=-1;}
void UiLocalizationPreviewPanel::LoadLocalization(const std::filesystem::path& path){engine::LocalizationAssetData data;std::string error;if(engine::LoadLocalizationAsset(path.string(),&data,&error)){m_localization=std::move(data);m_hasLocalization=true;m_languageIndex=0;m_fonts.clear();m_status="Loaded "+path.string();}else{m_hasLocalization=false;m_status=error;}}
bool UiLocalizationPreviewPanel::IsRtlLanguage()const{if(!m_hasLocalization||m_localization.languages.empty())return false;const std::string language=Lower(m_localization.languages[static_cast<std::size_t>(std::clamp(m_languageIndex,0,static_cast<int>(m_localization.languages.size())-1))]);for(const char* prefix:{"ar","he","fa","ur","ps","dv","ku"})if(language==prefix||language.rfind(std::string(prefix)+"-",0)==0||language.rfind(std::string(prefix)+"_",0)==0)return true;return false;}
std::string UiLocalizationPreviewPanel::Expanded(std::string value)const{if(m_pseudoLocalization){std::string pseudo="[!! ";for(char c:value){pseudo+=c;if(std::string("aeiouAEIOU").find(c)!=std::string::npos)pseudo+=c;}value=pseudo+" !!]";}const std::size_t target=static_cast<std::size_t>(std::ceil(value.size()*std::clamp(m_expansion,1.0f,3.0f)));while(value.size()<target)value+='~';return value;}
std::string UiLocalizationPreviewPanel::LocalizedText(const engine::HudWidget& widget,const engine::HudContext& context,bool* missingKey,bool* missingTranslation)const{
    if(missingKey)*missingKey=false;if(missingTranslation)*missingTranslation=false;std::string value=widget.text;if(!widget.localizationKey.empty()){const auto entry=std::find_if(m_localization.entries.begin(),m_localization.entries.end(),[&](const auto& e){return e.key==widget.localizationKey;});if(!m_hasLocalization||entry==m_localization.entries.end()){if(missingKey)*missingKey=true;}else{const std::string language=m_localization.languages.empty()?m_localization.sourceLanguage:m_localization.languages[static_cast<std::size_t>(std::clamp(m_languageIndex,0,static_cast<int>(m_localization.languages.size())-1))];if(language==m_localization.sourceLanguage)value=entry->source;else{auto translated=entry->translations.find(language);if(translated!=entry->translations.end()&&!translated->second.empty())value=translated->second;else{if(missingTranslation)*missingTranslation=true;translated=entry->translations.find(m_localization.fallbackLanguage);value=translated!=entry->translations.end()&&!translated->second.empty()?translated->second:(!entry->source.empty()?entry->source:widget.text);}}}}
    switch(widget.binding){case engine::HudBinding::HealthText:value=Substitute(value,Number(context.health)+"/"+Number(context.maxHealth));break;case engine::HudBinding::NamedFloat:{auto it=context.floats.find(widget.bindKey);value=Substitute(value,Number(it==context.floats.end()?0.0f:it->second));break;}case engine::HudBinding::NamedString:{auto it=context.strings.find(widget.bindKey);value=Substitute(value,it==context.strings.end()?std::string{}:it->second);break;}default:break;}return Expanded(value);
}
const UiLocalizationPreviewPanel::FontCacheEntry* UiLocalizationPreviewPanel::Font(const std::string& path,const std::filesystem::path& root){if(path.empty())return nullptr;std::string authored=path;std::replace(authored.begin(),authored.end(),'\\','/');if(authored.rfind("/Game/",0)==0)authored.erase(0,6);else if(authored.rfind("Game/",0)==0)authored.erase(0,5);else if(authored.rfind("Content/",0)==0)authored.erase(0,8);std::filesystem::path resolved(authored);if(!resolved.is_absolute())resolved=root/resolved;const std::string key=resolved.lexically_normal().string();auto found=m_fonts.find(key);if(found!=m_fonts.end())return &found->second;FontCacheEntry entry;std::ifstream in(resolved,std::ios::binary);if(!in)entry.error="font file is missing";else entry.valid=entry.asset.Load(in,&entry.error);return &m_fonts.emplace(key,std::move(entry)).first->second;}
int UiLocalizationPreviewPanel::MissingGlyphs(const std::string& text,const engine::FontAsset& font)const{int count=0;for(auto cp:engine::text::DecodeUtf8(text))if(cp!='\n'&&cp!='\r'&&cp!='\t'&&!font.Find(cp))++count;return count;}

std::vector<UiLocalizationPreviewPanel::Issue> UiLocalizationPreviewPanel::Inspect(const engine::HudDocument& hud,const engine::HudContext& context,int width,int height,const std::filesystem::path& root){
    std::vector<Issue> issues;engine::HudDocument scaled=hud;scaled.designSize/=std::max(m_dpiScale,0.25f);const float safeLeft=width*m_safeAreaX,safeTop=height*m_safeAreaY,safeRight=width-safeLeft,safeBottom=height-safeTop;const bool rtl=m_forceRtl||(m_autoRtl&&IsRtlLanguage());std::string languageFont;if(m_hasLocalization&&!m_localization.languages.empty()){const auto& language=m_localization.languages[static_cast<std::size_t>(std::clamp(m_languageIndex,0,static_cast<int>(m_localization.languages.size())-1))];auto it=m_localization.languageFonts.find(language);if(it!=m_localization.languageFonts.end())languageFont=it->second;}
    for(const auto& widget:hud.widgets){if(!widget.visible)continue;float x,y,w,h;engine::HudWidgetRect(widget,scaled,width,height,x,y,w,h);if(rtl)x=width-x-w;if(x<0||y<0||x+w>width||y+h>height)issues.push_back({Issue::Severity::Error,widget.name,"extends outside the screen"});else if(!Within(x,y,w,h,safeLeft,safeTop,safeRight,safeBottom))issues.push_back({Issue::Severity::Warning,widget.name,"extends outside the configured safe area"});if(widget.type!=engine::HudWidgetType::Text&&widget.type!=engine::HudWidgetType::Button)continue;bool missingKey=false,missingTranslation=false;const std::string text=LocalizedText(widget,context,&missingKey,&missingTranslation);if(missingKey)issues.push_back({Issue::Severity::Error,widget.name,"localization key '"+widget.localizationKey+"' was not found"});else if(missingTranslation)issues.push_back({Issue::Severity::Warning,widget.name,"translation is missing; fallback text is shown"});const float textPx=std::max(widget.fontSize>0?widget.fontSize:widget.textScale*8.0f,8.0f)*(static_cast<float>(height)/std::max(scaled.designSize.y,1.0f));const float estimatedWidth=ImGui::CalcTextSize(text.c_str()).x*(textPx/std::max(ImGui::GetFontSize(),1.0f));if(estimatedWidth>w&&widget.wrapMode==0)issues.push_back({Issue::Severity::Warning,widget.name,"localized text is wider than its box"});const std::string fontPath=!widget.fontAssetPath.empty()?widget.fontAssetPath:languageFont;if(fontPath.empty()){for(auto cp:engine::text::DecodeUtf8(text))if(cp>127){issues.push_back({Issue::Severity::Warning,widget.name,"non-ASCII text is using the built-in fallback font"});break;}}else{const auto* font=Font(fontPath,root);if(!font||!font->valid)issues.push_back({Issue::Severity::Error,widget.name,"font cannot be loaded: "+fontPath});else{const int missing=MissingGlyphs(text,font->asset);if(missing>0)issues.push_back({Issue::Severity::Warning,widget.name,std::to_string(missing)+" character(s) are missing from the selected font atlas"});}}}
    return issues;
}

void UiLocalizationPreviewPanel::DrawPreview(const engine::HudDocument& hud,const engine::HudContext& context,const std::function<unsigned int(const std::string&)>& textureLookup,const std::filesystem::path& root,ImVec2 available){
    const Resolution& preset=kResolutions[std::clamp(m_resolutionIndex,0,static_cast<int>(std::size(kResolutions))-1)];const int width=preset.width?preset.width:m_customWidth,height=preset.height?preset.height:m_customHeight;const float aspect=static_cast<float>(width)/std::max(height,1);float canvasW=available.x,canvasH=canvasW/aspect;if(canvasH>available.y){canvasH=available.y;canvasW=canvasH*aspect;}canvasW=std::max(canvasW,32.0f);canvasH=std::max(canvasH,32.0f);const ImVec2 origin=ImGui::GetCursorScreenPos();ImDrawList* draw=ImGui::GetWindowDrawList();draw->AddRectFilled(origin,{origin.x+canvasW,origin.y+canvasH},IM_COL32(23,26,33,255));draw->AddRect(origin,{origin.x+canvasW,origin.y+canvasH},IM_COL32(105,112,128,255));ImGui::InvisibleButton("##ui_preview_canvas",{canvasW,canvasH});const float dx=canvasW/width,dy=canvasH/height;engine::HudDocument scaled=hud;scaled.designSize/=std::max(m_dpiScale,0.25f);const bool rtl=m_forceRtl||(m_autoRtl&&IsRtlLanguage());
    if(m_showSafeArea){const float sx=canvasW*m_safeAreaX,sy=canvasH*m_safeAreaY;draw->AddRect({origin.x+sx,origin.y+sy},{origin.x+canvasW-sx,origin.y+canvasH-sy},IM_COL32(70,210,145,230),0,0,2.0f);}
    const auto issues=Inspect(hud,context,width,height,root);for(const auto& widget:hud.widgets){if(!widget.visible)continue;float x,y,w,h;engine::HudWidgetRect(widget,scaled,width,height,x,y,w,h);if(rtl)x=width-x-w;ImVec2 p0{origin.x+x*dx,origin.y+y*dy},p1{origin.x+(x+w)*dx,origin.y+(y+h)*dy};switch(widget.type){case engine::HudWidgetType::Bar:{draw->AddRectFilled(p0,p1,Color(widget.bgColor));const float fraction=engine::ResolveHudFraction(widget,context);draw->AddRectFilled(p0,{p0.x+(p1.x-p0.x)*fraction,p1.y},Color(widget.fillColor));break;}case engine::HudWidgetType::Image:{const unsigned texture=textureLookup&&!widget.imageAsset.empty()?textureLookup(widget.imageAsset):0;if(texture)draw->AddImage((ImTextureID)(intptr_t)texture,p0,p1,{0,1},{1,0},Color(widget.color));else{draw->AddRectFilled(p0,p1,IM_COL32(62,66,78,255));draw->AddText({p0.x+3,p0.y+3},IM_COL32(180,185,198,255),"image");}break;}case engine::HudWidgetType::Text:case engine::HudWidgetType::Button:{if(widget.type==engine::HudWidgetType::Button)draw->AddRectFilled(p0,p1,Color(widget.color));bool mk=false,mt=false;const auto text=LocalizedText(widget,context,&mk,&mt);const float requested=std::clamp((widget.fontSize>0?widget.fontSize:widget.textScale*8.0f)*(static_cast<float>(height)/std::max(scaled.designSize.y,1.0f))*dy,6.0f,96.0f);const ImVec2 measured=ImGui::CalcTextSize(text.c_str());float tx=p0.x;if(widget.type==engine::HudWidgetType::Button||widget.hAlign==1)tx=p0.x+((p1.x-p0.x)-measured.x*(requested/ImGui::GetFontSize()))*.5f;else if(widget.hAlign==2||rtl)tx=p1.x-measured.x*(requested/ImGui::GetFontSize());float ty=widget.type==engine::HudWidgetType::Button?p0.y+((p1.y-p0.y)-requested)*.5f:p0.y;draw->PushClipRect(p0,p1,true);draw->AddText(ImGui::GetFont(),requested,{tx,ty},widget.type==engine::HudWidgetType::Text?Color(widget.color):IM_COL32(245,245,245,255),text.c_str());draw->PopClipRect();break;}default:draw->AddRectFilled(p0,p1,Color(widget.color));break;}const auto issue=std::find_if(issues.begin(),issues.end(),[&](const Issue& value){return value.widget==widget.name;});if(issue!=issues.end())draw->AddRect(p0,p1,issue->severity==Issue::Severity::Error?IM_COL32(255,70,65,255):IM_COL32(255,180,55,255),0,0,2.0f);}
}

void UiLocalizationPreviewPanel::Draw(const engine::HudDocument& hud,const std::string& hudPath,const std::filesystem::path& contentRoot,const engine::HudContext& context,const std::function<unsigned int(const std::string&)>& textureLookup,bool* open){
    if(!m_initialized||m_contentRoot!=contentRoot){m_initialized=true;m_contentRoot=contentRoot;RefreshLocalizationAssets(contentRoot);}if(!ImGui::Begin(EditorPanels::Name(EditorPanels::Panel::UiLocalizationPreview),open)){ImGui::End();return;}ImGui::Text("HUD: %s",hudPath.empty()?"unsaved active HUD":hudPath.c_str());ImGui::SameLine();if(ImGui::Button("Refresh Tables"))RefreshLocalizationAssets(contentRoot);
    const std::string tablePreview=m_localizationIndex>=0&&m_localizationIndex<static_cast<int>(m_localizationAssets.size())?m_localizationAssets[static_cast<std::size_t>(m_localizationIndex)].filename().string():"No localization table";if(ImGui::BeginCombo("Localization",tablePreview.c_str())){if(ImGui::Selectable("No localization table",m_localizationIndex<0)){m_localizationIndex=-1;m_hasLocalization=false;}for(std::size_t i=0;i<m_localizationAssets.size();++i){const auto label=std::filesystem::relative(m_localizationAssets[i],contentRoot).generic_string();if(ImGui::Selectable(label.c_str(),m_localizationIndex==static_cast<int>(i))){m_localizationIndex=static_cast<int>(i);LoadLocalization(m_localizationAssets[i]);}}ImGui::EndCombo();}
    if(m_hasLocalization&&!m_localization.languages.empty()){m_languageIndex=std::clamp(m_languageIndex,0,static_cast<int>(m_localization.languages.size())-1);if(ImGui::BeginCombo("Language",m_localization.languages[static_cast<std::size_t>(m_languageIndex)].c_str())){for(std::size_t i=0;i<m_localization.languages.size();++i)if(ImGui::Selectable(m_localization.languages[i].c_str(),m_languageIndex==static_cast<int>(i))){m_languageIndex=static_cast<int>(i);m_fonts.clear();}ImGui::EndCombo();}}
    if(ImGui::BeginCombo("Resolution",kResolutions[m_resolutionIndex].name)){for(int i=0;i<static_cast<int>(std::size(kResolutions));++i)if(ImGui::Selectable(kResolutions[i].name,m_resolutionIndex==i))m_resolutionIndex=i;ImGui::EndCombo();}if(kResolutions[m_resolutionIndex].width==0){ImGui::InputInt("Width",&m_customWidth);ImGui::InputInt("Height",&m_customHeight);m_customWidth=std::clamp(m_customWidth,320,16384);m_customHeight=std::clamp(m_customHeight,200,16384);}const float dpiValues[]={0.75f,1.0f,1.25f,1.5f,2.0f};ImGui::SetNextItemWidth(110);const std::string dpiPreview=std::to_string(m_dpiScale)+"x";if(ImGui::BeginCombo("DPI Scale",dpiPreview.c_str())){for(float value:dpiValues){const std::string label=std::to_string(value)+"x";if(ImGui::Selectable(label.c_str(),m_dpiScale==value))m_dpiScale=value;}ImGui::EndCombo();}float safeXPercent=m_safeAreaX*100.0f,safeYPercent=m_safeAreaY*100.0f;if(ImGui::SliderFloat("Horizontal Safe Area",&safeXPercent,0.0f,20.0f,"%.1f%%"))m_safeAreaX=safeXPercent/100.0f;if(ImGui::SliderFloat("Vertical Safe Area",&safeYPercent,0.0f,20.0f,"%.1f%%"))m_safeAreaY=safeYPercent/100.0f;ImGui::SliderFloat("Text Expansion",&m_expansion,1.0f,3.0f,"%.2fx");ImGui::Checkbox("Pseudo-localize",&m_pseudoLocalization);ImGui::SameLine();ImGui::Checkbox("Auto RTL",&m_autoRtl);ImGui::SameLine();ImGui::Checkbox("Force RTL",&m_forceRtl);ImGui::SameLine();ImGui::Checkbox("Safe area",&m_showSafeArea);ImGui::SameLine();ImGui::Checkbox("Diagnostics",&m_showDiagnostics);
    ImGui::TextDisabled("The canvas uses the editor display font; glyph coverage is checked against the assigned engine font assets.");ImGui::Separator();const float diagnosticWidth=m_showDiagnostics?360.0f:0.0f;ImGui::BeginChild("UiResolutionPreviewCanvas",{std::max(100.0f,ImGui::GetContentRegionAvail().x-diagnosticWidth-8.0f),0},true);DrawPreview(hud,context,textureLookup,contentRoot,ImGui::GetContentRegionAvail());ImGui::EndChild();if(m_showDiagnostics){ImGui::SameLine();ImGui::BeginChild("UiResolutionPreviewDiagnostics",{0,0},true);const auto& resolution=kResolutions[m_resolutionIndex];const int width=resolution.width?resolution.width:m_customWidth,height=resolution.height?resolution.height:m_customHeight;const auto issues=Inspect(hud,context,width,height,contentRoot);int errors=0,warnings=0;for(const auto& issue:issues){errors+=issue.severity==Issue::Severity::Error;warnings+=issue.severity==Issue::Severity::Warning;}ImGui::Text("%d error(s), %d warning(s)",errors,warnings);ImGui::TextDisabled("Red = screen/clipping error; amber = review.");ImGui::SeparatorText("Current Resolution");if(issues.empty())ImGui::TextColored({.35f,1,.55f,1},"No layout issues found.");for(std::size_t i=0;i<issues.size();++i){ImGui::PushID(static_cast<int>(i));const auto color=issues[i].severity==Issue::Severity::Error?ImVec4(1,.3f,.25f,1):ImVec4(1,.7f,.2f,1);ImGui::TextColored(color,"%s",issues[i].widget.c_str());ImGui::TextWrapped("%s",issues[i].detail.c_str());ImGui::PopID();}ImGui::SeparatorText("Resolution Matrix");if(ImGui::BeginTable("##ui_resolution_matrix",3,ImGuiTableFlags_Borders|ImGuiTableFlags_RowBg)){ImGui::TableSetupColumn("Resolution");ImGui::TableSetupColumn("Errors");ImGui::TableSetupColumn("Warnings");ImGui::TableHeadersRow();for(int i=0;i<static_cast<int>(std::size(kResolutions))-1;++i){const auto matrix=Inspect(hud,context,kResolutions[i].width,kResolutions[i].height,contentRoot);int e=0,w=0;for(const auto& issue:matrix){e+=issue.severity==Issue::Severity::Error;w+=issue.severity==Issue::Severity::Warning;}ImGui::TableNextRow();ImGui::TableSetColumnIndex(0);if(ImGui::Selectable(kResolutions[i].name,m_resolutionIndex==i,ImGuiSelectableFlags_SpanAllColumns))m_resolutionIndex=i;ImGui::TableSetColumnIndex(1);ImGui::Text("%d",e);ImGui::TableSetColumnIndex(2);ImGui::Text("%d",w);}ImGui::EndTable();}if((m_forceRtl||(m_autoRtl&&IsRtlLanguage())))ImGui::TextWrapped("RTL preview mirrors anchors and right-aligns text. Complex-script shaping still follows the runtime font pipeline.");if(!m_status.empty())ImGui::TextWrapped("%s",m_status.c_str());ImGui::EndChild();}ImGui::End();
}
