#include "WeatherEditorPanel.h"

#include <imgui.h>
#include <imgui_stdlib.h>

#include <algorithm>
#include <cctype>
#include <cmath>
#include <filesystem>

namespace {
const char* PrecipitationName(engine::PrecipitationType type){switch(type){case engine::PrecipitationType::None:return "None";case engine::PrecipitationType::Rain:return "Rain";case engine::PrecipitationType::Snow:return "Snow";}return "None";}
std::string Safe(std::string value){for(char& c:value)if(!(std::isalnum(static_cast<unsigned char>(c))||c=='_'||c=='-'))c='_';return value.empty()?"Weather":value;}
float Hash(unsigned x){x^=x>>16;x*=0x7feb352du;x^=x>>15;x*=0x846ca68bu;x^=x>>16;return static_cast<float>(x&0xffffu)/65535.f;}
}

bool WeatherEditorPanel::SaveForShutdown(const std::string& root,std::string* error){
    if(m_path.empty())m_path=(std::filesystem::path(root)/"Assets"/"Weather"/(Safe(m_weather.name)+".3dgweather")).string();
    if(!engine::SaveWeatherAsset(m_path,m_weather,error))return false;
    m_dirty=false;return true;
}

void WeatherEditorPanel::Capture(const EditorScene::Environment& e){m_weather.timeOfDay=e.timeOfDay;m_weather.skyLightIntensity=e.skyLightIntensity;m_weather.sunIntensity=e.sunIntensity;m_weather.clouds=e.clouds;m_weather.cloudCoverage=e.cloudCoverage;m_weather.cloudDensity=e.cloudDensity;m_weather.cloudScale=e.cloudScale;m_weather.cloudSoftness=e.cloudSoftness;m_weather.cloudWindSpeed=e.cloudWindSpeed;m_weather.cloudWindDirection=e.cloudWindDirection;m_weather.cloudColor=e.cloudColor;m_weather.cloudShadows=e.cloudShadows;m_weather.cloudShadowStrength=e.cloudShadowStrength;m_weather.fog=e.fog;m_weather.fogColor=e.fogColor;m_weather.fogDensity=e.fogDensity;m_weather.fogHeight=e.fogHeight;m_weather.fogHeightFalloff=e.fogHeightFalloff;engine::NormalizeWeather(m_weather);m_dirty=true;}
void WeatherEditorPanel::Apply(EditorScene& scene)const{auto e=scene.GetEnvironment();e.timeOfDay=m_weather.timeOfDay;e.skyLightIntensity=m_weather.skyLightIntensity;e.sunIntensity=m_weather.sunIntensity;e.clouds=m_weather.clouds;e.cloudCoverage=m_weather.cloudCoverage;e.cloudDensity=m_weather.cloudDensity;e.cloudScale=m_weather.cloudScale;e.cloudSoftness=m_weather.cloudSoftness;e.cloudWindSpeed=m_weather.cloudWindSpeed;e.cloudWindDirection=m_weather.cloudWindDirection;e.cloudColor=m_weather.cloudColor;e.cloudShadows=m_weather.cloudShadows;e.cloudShadowStrength=m_weather.cloudShadowStrength;e.fog=m_weather.fog;e.fogColor=m_weather.fogColor;e.fogDensity=m_weather.fogDensity;e.fogHeight=m_weather.fogHeight;e.fogHeightFalloff=m_weather.fogHeightFalloff;scene.SetEnvironment(e);}

void WeatherEditorPanel::Preset(engine::PrecipitationType type){m_weather=engine::WeatherAssetData{};m_weather.precipitation=type;if(type==engine::PrecipitationType::Rain){m_weather.name="Rain";m_weather.precipitationIntensity=.72f;m_weather.cloudCoverage=.24f;m_weather.cloudDensity=1.3f;m_weather.cloudSoftness=.25f;m_weather.cloudColor={.58f,.64f,.72f};m_weather.cloudShadowStrength=.75f;m_weather.fog=true;m_weather.fogColor={.48f,.56f,.64f};m_weather.fogDensity=.018f;m_weather.windStrength=.45f;m_weather.surfaceWetness=.85f;m_weather.puddleAmount=.5f;m_weather.lightning=false;}else if(type==engine::PrecipitationType::Snow){m_weather.name="Snow";m_weather.precipitationIntensity=.55f;m_weather.precipitationSize=.65f;m_weather.precipitationSpeed=3.2f;m_weather.cloudCoverage=.3f;m_weather.cloudDensity=1.1f;m_weather.cloudColor={.82f,.86f,.9f};m_weather.fog=true;m_weather.fogColor={.78f,.84f,.9f};m_weather.fogDensity=.014f;m_weather.windStrength=.25f;m_weather.surfaceWetness=.15f;}else m_weather.name="Clear";engine::NormalizeWeather(m_weather);m_dirty=true;}

void WeatherEditorPanel::DrawPreview(const engine::WeatherAssetData& w){const ImVec2 size(ImGui::GetContentRegionAvail().x,std::max(220.f,ImGui::GetContentRegionAvail().y));ImGui::InvisibleButton("##WeatherPreview",size);const ImVec2 p=ImGui::GetItemRectMin();ImDrawList* d=ImGui::GetWindowDrawList();const float daylight=.18f+.82f*std::max(0.f,std::sin(w.timeOfDay*6.2831853f));ImVec4 sky(w.fogColor.r*.35f+daylight*.38f,w.fogColor.g*.35f+daylight*.48f,w.fogColor.b*.35f+daylight*.72f,1);d->AddRectFilled(p,{p.x+size.x,p.y+size.y},ImGui::ColorConvertFloat4ToU32(sky));const float horizon=p.y+size.y*.68f;d->AddRectFilled({p.x,horizon},{p.x+size.x,p.y+size.y},IM_COL32(45,58,48,255));if(w.clouds){const int count=static_cast<int>(10+w.cloudDensity*18);for(int i=0;i<count;++i){float x=p.x+Hash(w.previewSeed+i*7)*size.x,y=p.y+Hash(w.previewSeed+i*11+3)*size.y*.48f,r=18+Hash(w.previewSeed+i*17)*55;ImVec4 c(w.cloudColor.r,w.cloudColor.g,w.cloudColor.b,std::clamp((1.f-w.cloudCoverage)*.65f,0.f,.8f));d->AddCircleFilled({x,y},r,ImGui::ColorConvertFloat4ToU32(c),18);}}if(w.precipitation!=engine::PrecipitationType::None){const int count=static_cast<int>(w.precipitationIntensity*180);for(int i=0;i<count;++i){float x=p.x+Hash(w.previewSeed+i*19)*size.x,y=p.y+Hash(w.previewSeed+i*31)*size.y;const ImU32 c=w.precipitation==engine::PrecipitationType::Rain?IM_COL32(155,200,240,185):IM_COL32(245,250,255,220);if(w.precipitation==engine::PrecipitationType::Rain)d->AddLine({x,y},{x-3-w.windStrength*8,y+8+w.precipitationSize*14},c,1.2f);else d->AddCircleFilled({x,y},1.2f+w.precipitationSize*1.5f,c);}}d->AddText({p.x+10,p.y+10},IM_COL32_WHITE,(w.name+" | "+PrecipitationName(w.precipitation)).c_str());}

WeatherEditorPanel::Result WeatherEditorPanel::Draw(EditorScene& scene,EditorAssets& assets,const std::string& root,bool* open){Result result;if(!m_pendingOpen.empty()){std::string error;if(engine::LoadWeatherAsset(m_pendingOpen,&m_weather,&error)){m_path=m_pendingOpen;m_dirty=false;m_status="Loaded "+m_pendingOpen;}else m_status=error;m_pendingOpen.clear();}
    if(!ImGui::Begin("Weather Editor",open)){ImGui::End();return result;}if(ImGui::Button("New")){m_weather={};m_path.clear();m_dirty=true;}ImGui::SameLine();if(ImGui::Button("Capture Level"))Capture(scene.GetEnvironment());ImGui::SameLine();if(ImGui::Button("Apply to Level")){Apply(scene);result.applied=true;result.message="Applied weather to the active level.";}ImGui::SameLine();if(ImGui::Button("Save")){if(m_path.empty())m_path=(std::filesystem::path(root)/"Assets"/"Weather"/(Safe(m_weather.name)+".3dgweather")).string();std::string error;if(engine::SaveWeatherAsset(m_path,m_weather,&error)){m_dirty=false;result.saved=true;result.message="Saved weather: "+m_path;}else result.message=error;}ImGui::SameLine();ImGui::TextDisabled("%s",m_dirty?"Unsaved":"Saved");
    ImGui::TextWrapped("%s",m_path.empty()?"New weather asset":m_path.c_str());ImGui::Separator();ImGui::BeginChild("WeatherProperties",{390,0},true);m_dirty|=ImGui::InputText("Name",&m_weather.name);if(ImGui::Button("Clear"))Preset(engine::PrecipitationType::None);ImGui::SameLine();if(ImGui::Button("Rain"))Preset(engine::PrecipitationType::Rain);ImGui::SameLine();if(ImGui::Button("Snow"))Preset(engine::PrecipitationType::Snow);
    if(ImGui::CollapsingHeader("Lighting & Sky",ImGuiTreeNodeFlags_DefaultOpen)){m_dirty|=ImGui::SliderFloat("Time of Day",&m_weather.timeOfDay,0,1);m_dirty|=ImGui::SliderFloat("Sky Light",&m_weather.skyLightIntensity,0,8);m_dirty|=ImGui::SliderFloat("Sun Intensity",&m_weather.sunIntensity,0,8);}
    if(ImGui::CollapsingHeader("Clouds",ImGuiTreeNodeFlags_DefaultOpen)){m_dirty|=ImGui::Checkbox("Enabled##Clouds",&m_weather.clouds);m_dirty|=ImGui::SliderFloat("Coverage",&m_weather.cloudCoverage,.05f,.95f);m_dirty|=ImGui::SliderFloat("Density",&m_weather.cloudDensity,0,2);m_dirty|=ImGui::SliderFloat("Scale",&m_weather.cloudScale,.1f,6);m_dirty|=ImGui::SliderFloat("Softness",&m_weather.cloudSoftness,.01f,.45f);m_dirty|=ImGui::SliderFloat("Cloud Wind",&m_weather.cloudWindSpeed,-.25f,.25f);m_dirty|=ImGui::SliderFloat("Cloud Direction",&m_weather.cloudWindDirection,-180,180);m_dirty|=ImGui::ColorEdit3("Cloud Color",&m_weather.cloudColor.x);m_dirty|=ImGui::Checkbox("Cloud Shadows",&m_weather.cloudShadows);m_dirty|=ImGui::SliderFloat("Shadow Strength",&m_weather.cloudShadowStrength,0,1);}
    if(ImGui::CollapsingHeader("Fog",ImGuiTreeNodeFlags_DefaultOpen)){m_dirty|=ImGui::Checkbox("Enabled##Fog",&m_weather.fog);m_dirty|=ImGui::ColorEdit3("Fog Color",&m_weather.fogColor.x);m_dirty|=ImGui::SliderFloat("Fog Density",&m_weather.fogDensity,0,.2f,"%.4f");m_dirty|=ImGui::SliderFloat("Fog Height",&m_weather.fogHeight,-20,20);m_dirty|=ImGui::SliderFloat("Fog Falloff",&m_weather.fogHeightFalloff,.001f,2);}
    if(ImGui::CollapsingHeader("Precipitation",ImGuiTreeNodeFlags_DefaultOpen)){if(ImGui::BeginCombo("Type",PrecipitationName(m_weather.precipitation))){for(int i=0;i<=2;++i)if(ImGui::Selectable(PrecipitationName(static_cast<engine::PrecipitationType>(i)),i==static_cast<int>(m_weather.precipitation))){m_weather.precipitation=static_cast<engine::PrecipitationType>(i);m_dirty=true;}ImGui::EndCombo();}m_dirty|=ImGui::SliderFloat("Intensity",&m_weather.precipitationIntensity,0,1);m_dirty|=ImGui::SliderFloat("Drop / Flake Size",&m_weather.precipitationSize,.02f,3);m_dirty|=ImGui::SliderFloat("Fall Speed",&m_weather.precipitationSpeed,.1f,100);m_dirty|=ImGui::SliderFloat("Wind Strength",&m_weather.windStrength,0,1);m_dirty|=ImGui::SliderFloat("Wind Direction",&m_weather.windDirection,-180,180);}
    if(ImGui::CollapsingHeader("Storm & Surfaces")){m_dirty|=ImGui::Checkbox("Lightning",&m_weather.lightning);m_dirty|=ImGui::SliderFloat("Lightning Frequency",&m_weather.lightningFrequency,0,2);m_dirty|=ImGui::SliderFloat("Lightning Intensity",&m_weather.lightningIntensity,0,10);m_dirty|=ImGui::SliderFloat("Surface Wetness",&m_weather.surfaceWetness,0,1);m_dirty|=ImGui::SliderFloat("Puddle Amount",&m_weather.puddleAmount,0,1);}
    if(ImGui::CollapsingHeader("Effects & Transition")){const auto particles=assets.ContentAssetPaths(EditorAssets::Type::Particle);if(ImGui::BeginCombo("Particle Asset",m_weather.particleAssetPath.empty()?"None":std::filesystem::path(m_weather.particleAssetPath).filename().string().c_str())){if(ImGui::Selectable("None",m_weather.particleAssetPath.empty())){m_weather.particleAssetPath.clear();m_weather.particleAssetId={};m_dirty=true;}for(const auto& p:particles)if(ImGui::Selectable(std::filesystem::path(p).filename().string().c_str(),p==m_weather.particleAssetPath)){m_weather.particleAssetPath=p;m_weather.particleAssetId=assets.AssetIdForPath(p);m_dirty=true;}ImGui::EndCombo();}const auto audio=assets.ContentAssetPaths(EditorAssets::Type::Audio);if(ImGui::BeginCombo("Ambient Audio",m_weather.ambientAudioPath.empty()?"None":std::filesystem::path(m_weather.ambientAudioPath).filename().string().c_str())){if(ImGui::Selectable("None",m_weather.ambientAudioPath.empty())){m_weather.ambientAudioPath.clear();m_weather.ambientAudioId={};m_dirty=true;}for(const auto& p:audio)if(ImGui::Selectable(std::filesystem::path(p).filename().string().c_str(),p==m_weather.ambientAudioPath)){m_weather.ambientAudioPath=p;m_weather.ambientAudioId=assets.AssetIdForPath(p);m_dirty=true;}ImGui::EndCombo();}m_dirty|=ImGui::SliderFloat("Default Blend Time",&m_weather.defaultTransitionSeconds,0,120,"%.1f s");int seed=static_cast<int>(m_weather.previewSeed);if(ImGui::InputInt("Preview Seed",&seed)){m_weather.previewSeed=static_cast<unsigned>(std::max(seed,0));m_dirty=true;}}
    engine::NormalizeWeather(m_weather);ImGui::EndChild();ImGui::SameLine();ImGui::BeginChild("WeatherPreview",{0,0},true);if(ImGui::Button(m_playTransition?"Stop Transition":"Preview Transition")){if(!m_playTransition){m_transitionFrom=m_weather;m_transitionFrom.precipitation=engine::PrecipitationType::None;m_transitionFrom.precipitationIntensity=0;m_transitionFrom.cloudCoverage=.82f;m_transitionAlpha=0;}m_playTransition=!m_playTransition;}ImGui::SameLine();ImGui::SliderFloat("Blend",&m_transitionAlpha,0,1);if(m_playTransition){m_transitionAlpha=std::min(1.f,m_transitionAlpha+ImGui::GetIO().DeltaTime/std::max(m_weather.defaultTransitionSeconds,.01f));if(m_transitionAlpha>=1)m_playTransition=false;}DrawPreview(engine::BlendWeather(m_transitionFrom,m_weather,m_transitionAlpha));ImGui::EndChild();if(!m_status.empty())ImGui::TextWrapped("%s",m_status.c_str());ImGui::End();return result;}
