#include "engine/assets/CombatAsset.h"
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <unordered_set>
namespace engine {namespace{void Error(std::string*e,const std::string&m){if(e)*e=m;}void Dep(std::vector<AssetHandle>&d,AssetHandle id){if(id.Valid()&&std::find(d.begin(),d.end(),id)==d.end())d.push_back(id);}}
void NormalizeCombatAsset(CombatAssetData&a){if(a.name.empty())a.name="CombatProfile";a.team=std::clamp(a.team,0,32);a.poise=std::max(a.poise,0.f);a.staggerRecovery=std::max(a.staggerRecovery,0.f);a.blockReduction=std::clamp(a.blockReduction,0.f,1.f);a.blockStaminaCost=std::max(a.blockStaminaCost,0.f);a.parryWindow=std::max(a.parryWindow,0.f);a.immunityAfterHit=std::max(a.immunityAfterHit,0.f);a.targetingRange=std::max(a.targetingRange,0.f);if(a.damageTypes.empty())a.damageTypes.push_back({});for(auto&s:a.combo){if(s.name.empty())s.name="Attack";if(s.damageType.empty())s.damageType=a.damageTypes.front().name;s.damage=std::max(s.damage,0.f);s.staminaCost=std::max(s.staminaCost,0.f);s.duration=std::max(s.duration,.001f);s.hitTime=std::clamp(s.hitTime,0.f,s.duration);s.inputWindowStart=std::clamp(s.inputWindowStart,0.f,s.duration);s.inputWindowEnd=std::clamp(s.inputWindowEnd,s.inputWindowStart,s.duration);s.range=std::max(s.range,0.f);s.radius=std::max(s.radius,0.f);}}
bool ValidateCombatAsset(const CombatAssetData&a,std::string*e){if(a.name.empty()){Error(e,"Combat profile needs a name.");return false;}if(a.damageTypes.empty()){Error(e,"Combat profile needs a damage type.");return false;}if(a.combo.empty()){Error(e,"Combat profile needs at least one combo step.");return false;}std::unordered_set<std::string> types;for(const auto&t:a.damageTypes)if(t.name.empty()||!types.insert(t.name).second){Error(e,"Damage type names must be unique.");return false;}for(const auto&s:a.combo)if(!types.count(s.damageType)){Error(e,"Combo step references a missing damage type: "+s.damageType);return false;}return true;}
bool SaveCombatAsset(const std::string&path,CombatAssetData a,std::string*e){NormalizeCombatAsset(a);if(!ValidateCombatAsset(a,e))return false;a.header.type=AssetType::Combat;a.header.assetVersion=kCombatAssetVersion;if(!a.header.id.Valid())a.header.id=AssetHandle::Generate();a.header.dependencies.clear();for(const auto&s:a.combo)for(auto id:{s.actionClipId,s.particleId,s.audioId})Dep(a.header.dependencies,id);std::error_code ec;std::filesystem::create_directories(std::filesystem::path(path).parent_path(),ec);std::ofstream out(path);if(!out){Error(e,"Could not create combat asset: "+path);return false;}out<<"3DG_COMBAT "<<kCombatAssetVersion<<' '<<a.header.id.ToString()<<'\n'<<"ASSET_DEPS "<<a.header.dependencies.size();for(auto id:a.header.dependencies)out<<' '<<id.ToString();out<<'\n';out<<"PROFILE "<<std::quoted(a.name)<<' '<<a.team<<' '<<a.friendlyFire<<' '<<a.poise<<' '<<a.staggerRecovery<<' '<<a.blockReduction<<' '<<a.blockStaminaCost<<' '<<a.parryWindow<<' '<<a.immunityAfterHit<<' '<<a.targetingRange<<' '<<a.autoFaceTarget<<'\n';for(const auto&t:a.damageTypes)out<<"DAMAGE_TYPE "<<std::quoted(t.name)<<' '<<t.damageMultiplier<<' '<<t.staggerMultiplier<<' '<<t.armorPenetration<<'\n';for(const auto&r:a.resistances)out<<"RESISTANCE "<<std::quoted(r.damageType)<<' '<<r.multiplier<<'\n';for(const auto&s:a.combo)out<<"COMBO "<<std::quoted(s.name)<<' '<<std::quoted(s.actionClipPath)<<' '<<(s.actionClipId.Valid()?s.actionClipId.ToString():"-")<<' '<<std::quoted(s.damageType)<<' '<<s.damage<<' '<<s.staminaCost<<' '<<s.duration<<' '<<s.hitTime<<' '<<s.inputWindowStart<<' '<<s.inputWindowEnd<<' '<<s.range<<' '<<s.radius<<' '<<std::quoted(s.hitReaction)<<' '<<std::quoted(s.particlePath)<<' '<<(s.particleId.Valid()?s.particleId.ToString():"-")<<' '<<std::quoted(s.audioPath)<<' '<<(s.audioId.Valid()?s.audioId.ToString():"-")<<'\n';out<<"END\n";return static_cast<bool>(out);}
bool LoadCombatAsset(const std::string&path,CombatAssetData*output,std::string*e){if(!output){Error(e,"Combat output is null.");return false;}std::ifstream in(path);CombatAssetData a;std::string magic,id,record;std::uint32_t version=0;if(!(in>>magic>>version>>id)||magic!="3DG_COMBAT"||version!=kCombatAssetVersion||!AssetHandle::Parse(id,&a.header.id)){Error(e,"Invalid combat asset header.");return false;}std::size_t count=0;if(!(in>>record>>count)||record!="ASSET_DEPS"||count>4096){Error(e,"Invalid combat dependencies.");return false;}a.header.dependencies.resize(count);for(auto&d:a.header.dependencies){in>>id;if(!AssetHandle::Parse(id,&d)){Error(e,"Invalid combat dependency.");return false;}}while(in>>record&&record!="END"){if(record=="PROFILE")in>>std::quoted(a.name)>>a.team>>a.friendlyFire>>a.poise>>a.staggerRecovery>>a.blockReduction>>a.blockStaminaCost>>a.parryWindow>>a.immunityAfterHit>>a.targetingRange>>a.autoFaceTarget;else if(record=="DAMAGE_TYPE"){CombatDamageType t;in>>std::quoted(t.name)>>t.damageMultiplier>>t.staggerMultiplier>>t.armorPenetration;a.damageTypes.push_back(std::move(t));}else if(record=="RESISTANCE"){CombatResistance r;in>>std::quoted(r.damageType)>>r.multiplier;a.resistances.push_back(std::move(r));}else if(record=="COMBO"){CombatComboStep s;std::string clipId,particleId,audioId;in>>std::quoted(s.name)>>std::quoted(s.actionClipPath)>>clipId>>std::quoted(s.damageType)>>s.damage>>s.staminaCost>>s.duration>>s.hitTime>>s.inputWindowStart>>s.inputWindowEnd>>s.range>>s.radius>>std::quoted(s.hitReaction)>>std::quoted(s.particlePath)>>particleId>>std::quoted(s.audioPath)>>audioId;if(clipId!="-"&&!AssetHandle::Parse(clipId,&s.actionClipId))in.setstate(std::ios::failbit);if(particleId!="-"&&!AssetHandle::Parse(particleId,&s.particleId))in.setstate(std::ios::failbit);if(audioId!="-"&&!AssetHandle::Parse(audioId,&s.audioId))in.setstate(std::ios::failbit);a.combo.push_back(std::move(s));}else{Error(e,"Unknown combat record: "+record);return false;}if(!in){Error(e,"Combat asset is truncated or corrupt.");return false;}}a.header.type=AssetType::Combat;a.header.assetVersion=version;NormalizeCombatAsset(a);if(!ValidateCombatAsset(a,e))return false;*output=std::move(a);return true;}
} // namespace engine
