#include "engine/assets/EquipmentAsset.h"
#include <algorithm>
#include <cmath>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <unordered_set>

namespace engine { namespace {void Err(std::string*e,const std::string&m){if(e)*e=m;}bool finite(glm::vec3 v){return std::isfinite(v.x)&&std::isfinite(v.y)&&std::isfinite(v.z);}}
void NormalizeEquipmentAsset(EquipmentAssetData&a){if(!a.header.id.Valid())a.header.id=AssetHandle::Generate();if(a.name.empty())a.name="NewEquipmentSet";a.header.dependencies.clear();auto dep=[&](AssetHandle id){if(id.Valid()&&std::find(a.header.dependencies.begin(),a.header.dependencies.end(),id)==a.header.dependencies.end())a.header.dependencies.push_back(id);};dep(a.characterId);for(auto&i:a.items){if(i.name.empty())i.name="NewItem";if(i.slot.empty())i.slot="Equipment";i.scale=glm::max(i.scale,glm::vec3(.0001f));std::sort(i.tags.begin(),i.tags.end());i.tags.erase(std::unique(i.tags.begin(),i.tags.end()),i.tags.end());dep(i.modelId);dep(i.materialId);dep(i.audioId);dep(i.effectId);}}
bool ValidateEquipmentAsset(const EquipmentAssetData&a,std::string*e){if(!a.header.id.Valid()){Err(e,"Equipment set has no stable asset ID.");return false;}std::unordered_set<std::string>names;for(const auto&i:a.items){if(i.name.empty()||!names.insert(i.name).second){Err(e,"Equipment item names must be non-empty and unique.");return false;}if(i.slot.empty()||i.socketName.empty()){Err(e,"Every equipment item needs a slot and socket.");return false;}if(i.modelPath.empty()){Err(e,"Every equipment item needs a model.");return false;}if(!finite(i.position)||!finite(i.eulerDegrees)||!finite(i.scale)){Err(e,"Equipment transform is invalid.");return false;}}return true;}
bool SaveEquipmentAsset(const std::string&p,EquipmentAssetData a,std::string*e){NormalizeEquipmentAsset(a);if(!ValidateEquipmentAsset(a,e))return false;std::error_code ec;const auto parent=std::filesystem::path(p).parent_path();if(!parent.empty())std::filesystem::create_directories(parent,ec);std::ofstream o(p);if(!o){Err(e,"Could not create equipment set: "+p);return false;}o<<"3DG_EQUIPMENT_SET "<<kEquipmentAssetVersion<<' '<<a.header.id.ToString()<<'\n'<<"NAME "<<std::quoted(a.name)<<'\n'<<"CHARACTER "<<a.characterId.ToString()<<' '<<std::quoted(a.characterPath)<<'\n'<<"ITEMS "<<a.items.size()<<'\n'<<std::setprecision(9);for(const auto&i:a.items){o<<"ITEM "<<std::quoted(i.name)<<' '<<std::quoted(i.slot)<<' '<<std::quoted(i.socketName)<<' '<<i.tags.size()<<'\n';o<<"ASSETS "<<i.modelId.ToString()<<' '<<std::quoted(i.modelPath)<<' '<<i.materialId.ToString()<<' '<<std::quoted(i.materialPath)<<' '<<i.audioId.ToString()<<' '<<std::quoted(i.equipAudioPath)<<' '<<i.effectId.ToString()<<' '<<std::quoted(i.equipEffectPath)<<'\n';o<<"TRANSFORM "<<i.position.x<<' '<<i.position.y<<' '<<i.position.z<<' '<<i.eulerDegrees.x<<' '<<i.eulerDegrees.y<<' '<<i.eulerDegrees.z<<' '<<i.scale.x<<' '<<i.scale.y<<' '<<i.scale.z<<'\n';for(const auto&t:i.tags)o<<"TAG "<<std::quoted(t)<<'\n';}o<<"ASSET_DEPS "<<a.header.dependencies.size();for(const auto&id:a.header.dependencies)o<<' '<<id.ToString();o<<'\n';if(!o){Err(e,"Failed writing equipment set: "+p);return false;}return true;}
bool LoadEquipmentAsset(const std::string&p,EquipmentAssetData*out,std::string*e){if(!out){Err(e,"Equipment output is null.");return false;}std::ifstream in(p);EquipmentAssetData a;std::string token,id,magic;std::uint32_t version=0;std::size_t count=0;if(!(in>>magic>>version>>id)||magic!="3DG_EQUIPMENT_SET"||version!=kEquipmentAssetVersion||!AssetHandle::Parse(id,&a.header.id)){Err(e,"Invalid equipment set: "+p);return false;}if(!(in>>token>>std::quoted(a.name))||token!="NAME"||!(in>>token>>id>>std::quoted(a.characterPath))||token!="CHARACTER"){Err(e,"Equipment header is malformed.");return false;}AssetHandle::Parse(id,&a.characterId);if(!(in>>token>>count)||token!="ITEMS"||count>100000){Err(e,"Equipment item count is invalid.");return false;}a.items.resize(count);for(auto&i:a.items){std::size_t tags=0;if(!(in>>token>>std::quoted(i.name)>>std::quoted(i.slot)>>std::quoted(i.socketName)>>tags)||token!="ITEM"||tags>4096){Err(e,"Equipment item is malformed.");return false;}std::string modelId,matId,audioId,effectId;if(!(in>>token>>modelId>>std::quoted(i.modelPath)>>matId>>std::quoted(i.materialPath)>>audioId>>std::quoted(i.equipAudioPath)>>effectId>>std::quoted(i.equipEffectPath))||token!="ASSETS"){Err(e,"Equipment assets are malformed.");return false;}AssetHandle::Parse(modelId,&i.modelId);AssetHandle::Parse(matId,&i.materialId);AssetHandle::Parse(audioId,&i.audioId);AssetHandle::Parse(effectId,&i.effectId);if(!(in>>token>>i.position.x>>i.position.y>>i.position.z>>i.eulerDegrees.x>>i.eulerDegrees.y>>i.eulerDegrees.z>>i.scale.x>>i.scale.y>>i.scale.z)||token!="TRANSFORM"){Err(e,"Equipment transform is malformed.");return false;}i.tags.resize(tags);for(auto&t:i.tags)if(!(in>>token>>std::quoted(t))||token!="TAG"){Err(e,"Equipment tag is malformed.");return false;}}a.header.type=AssetType::EquipmentSet;a.header.assetVersion=version;NormalizeEquipmentAsset(a);if(!ValidateEquipmentAsset(a,e))return false;*out=std::move(a);return true;}
const EquipmentItem* FindEquipmentItem(const EquipmentAssetData&a,const std::string&name){const auto it=std::find_if(a.items.begin(),a.items.end(),[&](const auto&i){return i.name==name;});return it==a.items.end()?nullptr:&*it;}
} // namespace engine
