#include "engine/assets/ItemAsset.h"

#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <unordered_set>

namespace engine { namespace {void Error(std::string* e,const std::string& m){if(e)*e=m;}void Dep(std::vector<AssetHandle>& d,AssetHandle id){if(id.Valid()&&std::find(d.begin(),d.end(),id)==d.end())d.push_back(id);}}
const char* ItemTypeName(ItemType t){switch(t){case ItemType::Miscellaneous:return"Miscellaneous";case ItemType::Weapon:return"Weapon";case ItemType::Armor:return"Armor";case ItemType::Consumable:return"Consumable";case ItemType::Currency:return"Currency";case ItemType::Quest:return"Quest Item";case ItemType::Crafting:return"Crafting Material";}return"Item";}
const char* EquipmentSlotName(EquipmentSlot s){switch(s){case EquipmentSlot::None:return"None";case EquipmentSlot::MainHand:return"Main Hand";case EquipmentSlot::OffHand:return"Off Hand";case EquipmentSlot::Head:return"Head";case EquipmentSlot::Chest:return"Chest";case EquipmentSlot::Hands:return"Hands";case EquipmentSlot::Legs:return"Legs";case EquipmentSlot::Feet:return"Feet";case EquipmentSlot::Accessory:return"Accessory";}return"None";}
void NormalizeItemAsset(ItemAssetData& a){if(a.name.empty())a.name="Item";if(a.displayName.empty())a.displayName=a.name;a.maximumStack=std::clamp(a.maximumStack,1,100000000);a.value=std::max(a.value,0);a.weight=std::max(a.weight,0.0f);if(a.unique)a.maximumStack=1;if(a.type==ItemType::Consumable)a.consumable=true;if(a.type==ItemType::Currency)a.weight=0.0f;for(auto& s:a.statistics)if(s.name.empty())s.name="Stat";}
bool ValidateItemAsset(const ItemAssetData& a,std::string* e){if(a.name.empty()){Error(e,"Item needs an internal name.");return false;}if(a.maximumStack<1){Error(e,"Maximum stack must be at least one.");return false;}std::unordered_set<std::string> stats;for(const auto& s:a.statistics)if(s.name.empty()||!stats.insert(s.name).second){Error(e,"Item statistic names must be unique.");return false;}return true;}
bool SaveItemAsset(const std::string& path,ItemAssetData a,std::string* e){NormalizeItemAsset(a);if(!ValidateItemAsset(a,e))return false;a.header.type=AssetType::Item;a.header.assetVersion=kItemAssetVersion;if(!a.header.id.Valid())a.header.id=AssetHandle::Generate();a.header.dependencies.clear();for(auto id:{a.iconId,a.meshId,a.pickupPrefabId,a.abilityId,a.useAnimationId,a.useAudioId,a.useParticleId})Dep(a.header.dependencies,id);for(const auto& effect:a.effects)Dep(a.header.dependencies,effect.assetId);std::error_code ec;std::filesystem::create_directories(std::filesystem::path(path).parent_path(),ec);std::ofstream out(path);if(!out){Error(e,"Could not create item asset: "+path);return false;}out<<"3DG_ITEM "<<kItemAssetVersion<<' '<<a.header.id.ToString()<<'\n'<<"ASSET_DEPS "<<a.header.dependencies.size();for(auto id:a.header.dependencies)out<<' '<<id.ToString();out<<'\n';out<<"ITEM "<<std::quoted(a.name)<<' '<<std::quoted(a.displayName)<<' '<<std::quoted(a.description)<<' '<<std::quoted(a.localizationKey)<<' '<<static_cast<int>(a.type)<<' '<<static_cast<int>(a.equipmentSlot)<<' '<<a.maximumStack<<' '<<a.value<<' '<<a.weight<<' '<<a.consumable<<' '<<a.droppable<<' '<<a.unique<<'\n';
    const auto ref=[&](const char* tag,const std::string& p,AssetHandle id){out<<tag<<' '<<std::quoted(p)<<' '<<(id.Valid()?id.ToString():"-")<<'\n';};ref("ICON",a.iconPath,a.iconId);ref("MESH",a.meshPath,a.meshId);ref("PICKUP",a.pickupPrefabPath,a.pickupPrefabId);ref("ABILITY",a.abilityPath,a.abilityId);ref("ANIMATION",a.useAnimation,a.useAnimationId);ref("AUDIO",a.useAudio,a.useAudioId);ref("PARTICLE",a.useParticle,a.useParticleId);for(const auto& s:a.statistics)out<<"STAT "<<std::quoted(s.name)<<' '<<s.value<<'\n';for(const auto& effect:a.effects)out<<"EFFECT "<<std::quoted(effect.event)<<' '<<effect.magnitude<<' '<<std::quoted(effect.assetPath)<<' '<<(effect.assetId.Valid()?effect.assetId.ToString():"-")<<'\n';for(const auto& tag:a.tags)out<<"TAG "<<std::quoted(tag)<<'\n';out<<"END\n";if(!out){Error(e,"Failed while writing item asset.");return false;}return true;}
bool LoadItemAsset(const std::string& path,ItemAssetData* output,std::string* e){if(!output){Error(e,"Item output is null.");return false;}std::ifstream in(path);ItemAssetData a;std::string magic,id,record;std::uint32_t version=0;if(!(in>>magic>>version>>id)||magic!="3DG_ITEM"||version!=kItemAssetVersion||!AssetHandle::Parse(id,&a.header.id)){Error(e,"Invalid item asset header.");return false;}std::size_t count=0;if(!(in>>record>>count)||record!="ASSET_DEPS"||count>4096){Error(e,"Invalid item dependencies.");return false;}a.header.dependencies.resize(count);for(auto& d:a.header.dependencies){in>>id;if(!AssetHandle::Parse(id,&d)){Error(e,"Invalid item dependency ID.");return false;}}auto ref=[&](std::string& p,AssetHandle& h){in>>std::quoted(p)>>id;if(id!="-"&&!AssetHandle::Parse(id,&h))in.setstate(std::ios::failbit);};while(in>>record&&record!="END"){if(record=="ITEM"){int type=0,slot=0;in>>std::quoted(a.name)>>std::quoted(a.displayName)>>std::quoted(a.description)>>std::quoted(a.localizationKey)>>type>>slot>>a.maximumStack>>a.value>>a.weight>>a.consumable>>a.droppable>>a.unique;a.type=static_cast<ItemType>(std::clamp(type,0,6));a.equipmentSlot=static_cast<EquipmentSlot>(std::clamp(slot,0,8));}else if(record=="ICON")ref(a.iconPath,a.iconId);else if(record=="MESH")ref(a.meshPath,a.meshId);else if(record=="PICKUP")ref(a.pickupPrefabPath,a.pickupPrefabId);else if(record=="ABILITY")ref(a.abilityPath,a.abilityId);else if(record=="ANIMATION")ref(a.useAnimation,a.useAnimationId);else if(record=="AUDIO")ref(a.useAudio,a.useAudioId);else if(record=="PARTICLE")ref(a.useParticle,a.useParticleId);else if(record=="STAT"){ItemStatistic s;in>>std::quoted(s.name)>>s.value;a.statistics.push_back(std::move(s));}else if(record=="EFFECT"){ItemEffect effect;in>>std::quoted(effect.event)>>effect.magnitude>>std::quoted(effect.assetPath)>>id;if(id!="-"&&!AssetHandle::Parse(id,&effect.assetId))in.setstate(std::ios::failbit);a.effects.push_back(std::move(effect));}else if(record=="TAG"){std::string tag;in>>std::quoted(tag);a.tags.push_back(std::move(tag));}else{Error(e,"Unknown item record: "+record);return false;}if(!in){Error(e,"Item asset is truncated or corrupt.");return false;}}a.header.type=AssetType::Item;a.header.assetVersion=version;NormalizeItemAsset(a);if(!ValidateItemAsset(a,e))return false;*output=std::move(a);return true;}
} // namespace engine
