#include "engine/assets/SpawnAsset.h"
#include <algorithm>
#include <filesystem>
#include <fstream>
#include <iomanip>
#include <unordered_set>
namespace engine{namespace{void Error(std::string*e,const std::string&m){if(e)*e=m;}void Dep(std::vector<AssetHandle>&d,AssetHandle id){if(id.Valid()&&std::find(d.begin(),d.end(),id)==d.end())d.push_back(id);}}
const char* SpawnShapeName(SpawnShape s){switch(s){case SpawnShape::Point:return"Point";case SpawnShape::Box:return"Box";case SpawnShape::Sphere:return"Sphere";}return"Point";}
void NormalizeSpawnAsset(SpawnAssetData&a){if(a.name.empty())a.name="SpawnEncounter";a.radius=std::max(a.radius,.1f);a.height=std::max(a.height,0.f);a.boxExtents=glm::max(a.boxExtents,glm::vec3(.1f));a.retriggerCooldown=std::max(a.retriggerCooldown,0.f);a.maximumConcurrent=std::max(a.maximumConcurrent,1);a.maximumTotal=std::max(a.maximumTotal,a.maximumConcurrent);for(auto&e:a.entries){if(e.name.empty())e.name="Enemy";if(e.group.empty())e.group="Default";e.weight=std::max(e.weight,0.f);e.minimumDifficulty=std::max(e.minimumDifficulty,0.f);e.maximumDifficulty=std::max(e.maximumDifficulty,e.minimumDifficulty);e.maximumAlive=std::max(e.maximumAlive,1);e.poolLimit=std::max(e.poolLimit,0);}for(std::size_t i=0;i<a.waves.size();++i){auto&w=a.waves[i];if(w.name.empty())w.name="Wave "+std::to_string(i+1);if(w.group.empty())w.group="Default";w.count=std::max(w.count,1);w.delayBefore=std::max(w.delayBefore,0.f);w.spawnInterval=std::max(w.spawnInterval,0.f);w.delayAfter=std::max(w.delayAfter,0.f);}}
bool ValidateSpawnAsset(const SpawnAssetData&a,std::string*e){if(a.name.empty()){Error(e,"Spawn encounter needs a name.");return false;}if(a.entries.empty()){Error(e,"Spawn encounter needs at least one weighted entry.");return false;}if(a.waves.empty()){Error(e,"Spawn encounter needs at least one wave.");return false;}std::unordered_set<std::string>groups;for(const auto&x:a.entries){if(x.prototypeName.empty()){Error(e,"Spawn entry needs a scene prototype name.");return false;}if(x.weight>0)groups.insert(x.group);}for(const auto&w:a.waves)if(!groups.count(w.group)){Error(e,"Wave references a group without weighted entries: "+w.group);return false;}return true;}
bool SaveSpawnAsset(const std::string&p,SpawnAssetData a,std::string*e){NormalizeSpawnAsset(a);if(!ValidateSpawnAsset(a,e))return false;a.header.type=AssetType::Spawn;a.header.assetVersion=kSpawnAssetVersion;if(!a.header.id.Valid())a.header.id=AssetHandle::Generate();a.header.dependencies.clear();for(const auto&x:a.entries)Dep(a.header.dependencies,x.prefabId);std::error_code ec;std::filesystem::create_directories(std::filesystem::path(p).parent_path(),ec);std::ofstream out(p);if(!out){Error(e,"Could not create spawn asset: "+p);return false;}out<<"3DG_SPAWN "<<kSpawnAssetVersion<<' '<<a.header.id.ToString()<<'\n'<<"ASSET_DEPS "<<a.header.dependencies.size();for(auto id:a.header.dependencies)out<<' '<<id.ToString();out<<'\n'<<"PROFILE "<<std::quoted(a.name)<<' '<<static_cast<int>(a.shape)<<' '<<a.radius<<' '<<a.height<<' '<<a.boxExtents.x<<' '<<a.boxExtents.y<<' '<<a.boxExtents.z<<' '<<a.autoStart<<' '<<a.triggerOnPlayerEnter<<' '<<a.oneShot<<' '<<a.loopWaves<<' '<<a.randomYaw<<' '<<a.recycleDead<<' '<<a.retriggerCooldown<<' '<<a.maximumConcurrent<<' '<<a.maximumTotal<<' '<<a.seed<<'\n';for(const auto&x:a.entries)out<<"ENTRY "<<std::quoted(x.name)<<' '<<std::quoted(x.group)<<' '<<std::quoted(x.prototypeName)<<' '<<std::quoted(x.prefabPath)<<' '<<(x.prefabId.Valid()?x.prefabId.ToString():"-")<<' '<<x.weight<<' '<<x.minimumDifficulty<<' '<<x.maximumDifficulty<<' '<<x.maximumAlive<<' '<<x.poolLimit<<'\n';for(const auto&w:a.waves)out<<"WAVE "<<std::quoted(w.name)<<' '<<std::quoted(w.group)<<' '<<w.count<<' '<<w.delayBefore<<' '<<w.spawnInterval<<' '<<w.delayAfter<<' '<<w.waitForClear<<'\n';out<<"END\n";return static_cast<bool>(out);}
bool LoadSpawnAsset(const std::string&p,SpawnAssetData*o,std::string*e){if(!o){Error(e,"Spawn output is null.");return false;}std::ifstream in(p);SpawnAssetData a;std::string magic,id,r;std::uint32_t v=0;if(!(in>>magic>>v>>id)||magic!="3DG_SPAWN"||v!=kSpawnAssetVersion||!AssetHandle::Parse(id,&a.header.id)){Error(e,"Invalid spawn asset header.");return false;}std::size_t n=0;if(!(in>>r>>n)||r!="ASSET_DEPS"||n>4096){Error(e,"Invalid spawn dependencies.");return false;}a.header.dependencies.resize(n);for(auto&d:a.header.dependencies){in>>id;if(!AssetHandle::Parse(id,&d)){Error(e,"Invalid spawn dependency.");return false;}}while(in>>r&&r!="END"){if(r=="PROFILE"){int shape=0;in>>std::quoted(a.name)>>shape>>a.radius>>a.height>>a.boxExtents.x>>a.boxExtents.y>>a.boxExtents.z>>a.autoStart>>a.triggerOnPlayerEnter>>a.oneShot>>a.loopWaves>>a.randomYaw>>a.recycleDead>>a.retriggerCooldown>>a.maximumConcurrent>>a.maximumTotal>>a.seed;a.shape=static_cast<SpawnShape>(std::clamp(shape,0,2));}else if(r=="ENTRY"){SpawnEntry x;std::string assetId;in>>std::quoted(x.name)>>std::quoted(x.group)>>std::quoted(x.prototypeName)>>std::quoted(x.prefabPath)>>assetId>>x.weight>>x.minimumDifficulty>>x.maximumDifficulty>>x.maximumAlive>>x.poolLimit;if(assetId!="-"&&!AssetHandle::Parse(assetId,&x.prefabId))in.setstate(std::ios::failbit);a.entries.push_back(std::move(x));}else if(r=="WAVE"){SpawnWave w;in>>std::quoted(w.name)>>std::quoted(w.group)>>w.count>>w.delayBefore>>w.spawnInterval>>w.delayAfter>>w.waitForClear;a.waves.push_back(std::move(w));}else{Error(e,"Unknown spawn record: "+r);return false;}if(!in){Error(e,"Spawn asset is truncated or corrupt.");return false;}}a.header.type=AssetType::Spawn;a.header.assetVersion=v;NormalizeSpawnAsset(a);if(!ValidateSpawnAsset(a,e))return false;*o=std::move(a);return true;}
}
