#pragma once

#include <glm/glm.hpp>

#include <engine/ecs/Entity.h>

#include <cstdint>
#include <unordered_map>
#include <vector>

namespace engine {
namespace ecs { class Registry; }

// A ray for scene queries. direction is normalized by Raycast if needed.
struct Ray {
    glm::vec3 origin{0.0f};
    glm::vec3 direction{0.0f, 0.0f, -1.0f};
};

// Result of a raycast. On a miss, hit == false and entity == ecs::kNull.
struct RaycastHit {
    bool        hit      = false;
    ecs::Entity entity   = ecs::kNull;
    float       distance = 0.0f;
    glm::vec3   point{0.0f};
    glm::vec3   normal{0.0f};
};

// A collision/overlap event emitted by a step. Enter on the first step a pair
// touches, Stay while they keep touching, Exit on the step they separate.
// trigger is true when either collider is a trigger (overlap-only) volume.
struct CollisionEvent {
    enum class Phase { Enter, stay, Exit };
    ecs::Entity a = ecs::kNull;
    ecs::Entity b = ecs::kNull;
    Phase       phase = Phase::Enter;
    bool        trigger = false;
};

// A constraint between two bodies' centres, or between one body and a fixed world
// anchor (when b == ecs::kNull, the 'anchor' point is used). Distance keeps them
// exactly restLength apart (or, as a rope, only stops them stretching past it);
// Spring pulls softly toward restLength with stiffness + damping. With no angular
// dynamics yet, joints attach at body centres (rods, pendulums, ropes, springs).
struct Joint {
    enum class Type { Distace, Spring };
    Type       type = Type::Distace;
    ecs::Entity a = ecs::kNull;
    ecs::Entity b = ecs::kNull;      // kNull => attached to 'anchor'
    glm::vec3   anchor{0.0f};
    float       restLength = 1.0f;
    bool        rope = false;        // Distance only: resist stretch, allow slack
    float       stiffness = 100.0f;  // Spring only
    float       damping   = 1.0f;    // Spring only
};

// The physics solver. Step() integrates every RigidBody under gravity, detects
// contacts between Collider entities, and resolves them with impulses plus
// positional correction. Call it from the fixed-timestep OnFixedUpdate so the
// simulation is deterministic and frame-rate independent.
class PhysicsWorld {
public:
    glm::vec3 gravity{0.0f, -9.81f, 0.0f};
    int       solverIterations = 4;   // sequential-impulse passes per step
    
    // Broad phase: a uniform spatial hash culls the O(n^2) pair test. Disable to
    // fall back to brute-force all-pairs (identical results; used for testing).
    bool     broadPhase = true;
    float    cellSize   = 2.0f;             // grid cell edge length (world units)

    // Below this closing speed a contact does not bounce (restitution slop) --
    // stops resting stacks from micro-bouncing so they can settle and sleep.
    float    restitutionThreshold = 0.5f;

    // Sleeping: a body moving slower than sleepLinearVelocity for timeToSleep
    // seconds is put to sleep; a fast contact wakes it.
    bool     allowSleeping       = true;
    float    sleepLinearVelocity = 0.06f;
    float    timeToSleep         = 0.5f;

    void Step(ecs::Registry& registry, float dt);

    // Cast a ray through all colliders and return the closest hit within
    // maxDistance (sphere / plane / box). direction need not be pre-normalized.
    RaycastHit Raycast(ecs::Registry& registry, const Ray& ray, float maxDistance = 1.0e30f) const;

    // Enter/Stay/Exit events generated by the most recent Step (both solid
    // contacts and trigger overlaps). Valid until the next Step.
    const std::vector<CollisionEvent>& Events() const { return m_events; }

    // --- Joints -----------------------------------------------------------
    void AddJoint(const Joint& j) { m_joints.push_back(j); }
    void AddDistanceJoint(ecs::Entity a, ecs::Entity b, float restLength, bool rope = false) {
        Joint j; j.type = Joint::Type::Distace; j.a = a; j.b = b; j.restLength = restLength; j.rope = rope;
        m_joints.push_back(j);
    }
    void AddDistanceJointToWorld(ecs::Entity a, const glm::vec3& anchor, float restLength, bool rope = false) {
        Joint j; j.type = Joint::Type::Distace; j.a = a; j.anchor = anchor; j.restLength = restLength; j.rope = rope;
        m_joints.push_back(j);
    }
    void AddSpringJoint(ecs::Entity a, ecs::Entity b, float restLength, float stiffness, float damping) {
        Joint j; j.type = Joint::Type::Spring; j.a = a; j.b = b; j.restLength = restLength;
        j.stiffness = stiffness; j.damping = damping; m_joints.push_back(j);
    }
    void AddSpringJointToWorld(ecs::Entity a, const glm::vec3& anchor, float restLength, float stiffness, float damping) {
        Joint j; j.type = Joint::Type::Spring; j.a = a; j.anchor = anchor; j.restLength = restLength;
        j.stiffness = stiffness; j.damping = damping; m_joints.push_back(j);
    }
    void ClearJoints() { m_joints.clear(); }

private:
    std::vector<CollisionEvent>             m_events;   // events from the last step
    std::unordered_map<std::uint64_t, bool> m_touching; // pair key -> wasTrigger (persists)
    std::vector<Joint>                      m_joints;
};

} // namespace engine