#pragma once

#include <engine/gameplay/Script.h>
#include <memory>
#include <Scripts/Coin.h>
#include <Scripts/GoalTracker.h>

// Generated by the editor. Changes are replaced when scripts are created.
inline void RegisterEditorGeneratedScripts(engine::ScriptRegistry& scripts) {
    scripts.Register("Coin", [] { return std::make_unique<Coin>(); });
    scripts.Register("GoalTracker", [] { return std::make_unique<GoalTracker>(); });
}
