#pragma once

#include <engine/gameplay/Script.h>
#include <engine/ai/BtScript.h>
#include <memory>
#include "D:/3DGEditorGame/FirstGame/Content/Scripts/PlayerAttack.h"
#include "D:/3DGEditorGame/FirstGame/Content/Scripts/WizardCastSpell.h"
#include "D:/3DGEditorGame/FirstGame/Content/Scripts/WizardLifeReactions.h"

// Generated by the editor. Changes are replaced when scripts are created.
inline void RegisterEditorGeneratedScripts(engine::ScriptRegistry& scripts) {
    scripts.Register("PlayerAttack", [] { return std::make_unique<PlayerAttack>(); });
    scripts.Register("WizardLifeReactions", [] { return std::make_unique<WizardLifeReactions>(); });
}

inline void RegisterEditorGeneratedBtScripts(engine::ai::BtScriptRegistry& scripts) {
    scripts.Register("WizardCastSpell", [] { return std::make_unique<WizardCastSpell>(); });
}
