#pragma once

#include <engine/gameplay/Script.h>
#include <engine/ai/BtScript.h>
#include <memory>

// Generated by the editor. Changes are replaced when scripts are created.
inline void RegisterEditorGeneratedScripts(engine::ScriptRegistry& scripts) {
    (void)scripts;
}

inline void RegisterEditorGeneratedBtScripts(engine::ai::BtScriptRegistry& scripts) {
    (void)scripts;
}
